// Code generated by oapi-codegen; DO NOT EDIT.

package output

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"
	"sync"

	oapiCodegenHelpersPkg "github.com/oapi-codegen/oapi-codegen-exp/runtime/helpers"
)

// #/components/schemas/Severity
// How urgent a problem is.
type Severity int

const (
	// An urgent problem
	HIGH   Severity = 2
	MEDIUM Severity = 1
	// Can wait forever
	LOW Severity = 0
)

// #/components/schemas/Color
type Color string

const (
	// Warm, high-energy
	Red   Color = "r"
	Green Color = "g"
	// Cool, calm
	Blue Color = "b"
)

// #/components/schemas/MixedOneOf

type MixedOneOf struct {
	union json.RawMessage
}

// AsAny0 returns the union data inside the MixedOneOf as a any.
func (t MixedOneOf) AsAny0() (any, error) {
	var body any
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAny0 overwrites any union data inside the MixedOneOf as the provided any.
func (t *MixedOneOf) FromAny0(v any) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAny0 performs a merge with any union data inside the MixedOneOf, using the provided any.
func (t *MixedOneOf) MergeAny0(v any) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAny1 returns the union data inside the MixedOneOf as a any.
func (t MixedOneOf) AsAny1() (any, error) {
	var body any
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAny1 overwrites any union data inside the MixedOneOf as the provided any.
func (t *MixedOneOf) FromAny1(v any) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAny1 performs a merge with any union data inside the MixedOneOf, using the provided any.
func (t *MixedOneOf) MergeAny1(v any) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MixedOneOf) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MixedOneOf) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *MixedOneOf) ApplyDefaults() {
}

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/5RTwWrcShC86ysK9vIe8S7r5Kab4xjbEGdDQvBVvVKvZshMt5hprbOEQD4iX5gvCZJ2",
	"jY0wITfNUFPVVepa4Er6uNx7WqrwZof/Nh3LxcdbvFmd/1+CkGvHkfDgzY0nCpRQ2aHjCl3oM6rxYVUs",
	"sE0kteMMc2Rgqh1qSumAqlbJVuEVKvMWuEJ22ocGW0bLwomMG1AG4VqLBVj6OCkKRW4wPiexDJIGHafl",
	"nkLPaLRGrTGyWF4V2rFQ58th9NW68LLTsgBGxXL0ib0nTD6NsxXAnlP2KiXOV+vVuujIXC7x/UdRa+xU",
	"BuKBYwph/AQ+856Tt8N0AhrOdfKdjTw3+oA+tSwGQpd0GzjC59URO+RWwotxy+l4Nw50IgOWp4lvbq9v",
	"Hm8xhVDi9ZOrZ8oXchI+ys4Z767e3X65m3Oez6HvN/dz3Pol7UsSPJA37DQN6RQj8FKDpvKZ82zJS/sX",
	"45+4mWunl7TvKcUzON+65bBK7WFOeJ2YZU7ZzpFvQ89z4PZF36rhDDWFODle4AO3ZH7PGFapHCwea4FA",
	"9dd8KsAZssIcwzdeI2KfDaKGSFY7/P7560hnzudTBXcUwtCtpH3rYNP7xG0/NHLa6l68yqlSmqatu/Pf",
	"uNk8zfof/sVF6BzNE6EnyMeQ/gQAAP//fcizEU0EAAA=",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}
