// Code generated by oapi-codegen; DO NOT EDIT.

package output

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"
	"sync"

	oapiCodegenHelpersPkg "github.com/oapi-codegen/oapi-codegen-exp/runtime/helpers"
)

// #/components/schemas/BasePrompt
type BasePrompt struct {
	Name    string `form:"name" json:"name"`
	Version int    `form:"version" json:"version"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *BasePrompt) ApplyDefaults() {
}

// #/components/schemas/TextPrompt
type TextPrompt struct {
	Prompt  string `form:"prompt" json:"prompt"`
	Name    string `form:"name" json:"name"`
	Version int    `form:"version" json:"version"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *TextPrompt) ApplyDefaults() {
}

// #/components/schemas/ChatMessage
type ChatMessage struct {
	Role    string `form:"role" json:"role"`
	Content string `form:"content" json:"content"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ChatMessage) ApplyDefaults() {
}

// #/components/schemas/ChatPrompt
type ChatPrompt struct {
	Prompt  []ChatMessage `form:"prompt" json:"prompt"`
	Name    string        `form:"name" json:"name"`
	Version int           `form:"version" json:"version"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ChatPrompt) ApplyDefaults() {
}

// #/components/schemas/ChatPrompt/properties/prompt
type ChatPromptPrompt = []ChatMessage

// #/components/schemas/Prompt

type Prompt struct {
	union json.RawMessage
}

// AsPromptOneOf0 returns the union data inside the Prompt as a PromptOneOf0.
func (t Prompt) AsPromptOneOf0() (PromptOneOf0, error) {
	var body PromptOneOf0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPromptOneOf0 overwrites any union data inside the Prompt as the provided PromptOneOf0.
func (t *Prompt) FromPromptOneOf0(v PromptOneOf0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePromptOneOf0 performs a merge with any union data inside the Prompt, using the provided PromptOneOf0.
func (t *Prompt) MergePromptOneOf0(v PromptOneOf0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPromptOneOf1 returns the union data inside the Prompt as a PromptOneOf1.
func (t Prompt) AsPromptOneOf1() (PromptOneOf1, error) {
	var body PromptOneOf1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPromptOneOf1 overwrites any union data inside the Prompt as the provided PromptOneOf1.
func (t *Prompt) FromPromptOneOf1(v PromptOneOf1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePromptOneOf1 performs a merge with any union data inside the Prompt, using the provided PromptOneOf1.
func (t *Prompt) MergePromptOneOf1(v PromptOneOf1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Prompt) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Prompt) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *Prompt) ApplyDefaults() {
}

// #/components/schemas/Prompt/oneOf/0
type PromptOneOf0 struct {
	Type    *string       `form:"type,omitempty" json:"type,omitempty"`
	Prompt  []ChatMessage `form:"prompt" json:"prompt"`
	Name    string        `form:"name" json:"name"`
	Version int           `form:"version" json:"version"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *PromptOneOf0) ApplyDefaults() {
}

// #/components/schemas/Prompt/oneOf/0/allOf/0/properties/type
type PromptOneOf0AllOf0Type string

const (
	Chat PromptOneOf0AllOf0Type = "chat"
)

// #/components/schemas/Prompt/oneOf/1
type PromptOneOf1 struct {
	Type    *string `form:"type,omitempty" json:"type,omitempty"`
	Prompt  string  `form:"prompt" json:"prompt"`
	Name    string  `form:"name" json:"name"`
	Version int     `form:"version" json:"version"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *PromptOneOf1) ApplyDefaults() {
}

// #/components/schemas/Prompt/oneOf/1/allOf/0/properties/type
type PromptOneOf1AllOf0Type string

const (
	Text PromptOneOf1AllOf0Type = "text"
)

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/9SUT4/TMBDF7/kUIwWpFzZpxQEpRzhxQMuhEmc3eYmNEtt4JvtHiO+O4qYbh2132RVC",
	"oqfO68zzm5+b5PSJeQTt3u+2FbUGfUO9YyFjyYIFDam+v27JWVy3WU5axHNVlp0RPR6K2g2lU95c1a5B",
	"B7suzOTN5WSe5VlOXzUsjWxstza/NaKPJ7ydlGMOJtZu7Bs6gHwAI9ygKbKc9hq08cENXjZz5FvFdMDk",
	"O4UvMudhlTcVvSu2xTYztnVVRiRGelTJyrQHS0Z0g8DG2Yp2sd8r0VzRj59Z7QbvLKzwNM+1xqDiV6IP",
	"ivElpjjWRHLvUZE7fEMts+SD8whiwKcmIqsGLNVpjCUY2z3Ip0SP+owVdAizHvB9NAHN0ncV/ZNydorK",
	"Hnfyqsx+NXQh9bkwx8FZiLed/vomoK1ok5cL53KGXC58N3Hio1byGcyqwwvDB9c/D7x2VmBfs+Jkn5Sz",
	"0UPmv8pbhaDuE9UIBk7b6EmmCcPNP7m09fLxEU+tztA4c+STvZcIrrg9Ui/8CZYP7DicG4s3rJX8Fu45",
	"6CmTS9yXNf97QoK7lxBaXkt/TOhXAAAA//+WRkFKuQYAAA==",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}
