// Code generated by oapi-codegen; DO NOT EDIT.

package output

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"
	"sync"

	oapiCodegenHelpersPkg "github.com/oapi-codegen/oapi-codegen-exp/runtime/helpers"
)

// #/components/schemas/ArrayOfAnyOf
type ArrayOfAnyOf = []ArrayOfAnyOfItem

// #/components/schemas/ArrayOfAnyOf/items

type ArrayOfAnyOfItem struct {
	union json.RawMessage
}

// AsString0 returns the union data inside the ArrayOfAnyOfItem as a string.
func (t ArrayOfAnyOfItem) AsString0() (string, error) {
	var body string
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromString0 overwrites any union data inside the ArrayOfAnyOfItem as the provided string.
func (t *ArrayOfAnyOfItem) FromString0(v string) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeString0 performs a merge with any union data inside the ArrayOfAnyOfItem, using the provided string.
func (t *ArrayOfAnyOfItem) MergeString0(v string) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsArrayOfAnyOfAnyOf1 returns the union data inside the ArrayOfAnyOfItem as a ArrayOfAnyOfAnyOf1.
func (t ArrayOfAnyOfItem) AsArrayOfAnyOfAnyOf1() (ArrayOfAnyOfAnyOf1, error) {
	var body ArrayOfAnyOfAnyOf1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromArrayOfAnyOfAnyOf1 overwrites any union data inside the ArrayOfAnyOfItem as the provided ArrayOfAnyOfAnyOf1.
func (t *ArrayOfAnyOfItem) FromArrayOfAnyOfAnyOf1(v ArrayOfAnyOfAnyOf1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeArrayOfAnyOfAnyOf1 performs a merge with any union data inside the ArrayOfAnyOfItem, using the provided ArrayOfAnyOfAnyOf1.
func (t *ArrayOfAnyOfItem) MergeArrayOfAnyOfAnyOf1(v ArrayOfAnyOfAnyOf1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ArrayOfAnyOfItem) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ArrayOfAnyOfItem) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *ArrayOfAnyOfItem) ApplyDefaults() {
}

// #/components/schemas/ArrayOfAnyOf/items/anyOf/1
type ArrayOfAnyOfAnyOf1 struct {
	ID *int `form:"id,omitempty" json:"id,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ArrayOfAnyOfAnyOf1) ApplyDefaults() {
}

// #/components/schemas/ObjectWithAnyOfProperty
type ObjectWithAnyOfProperty struct {
	Value *ObjectWithAnyOfPropertyValue `form:"value,omitempty" json:"value,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ObjectWithAnyOfProperty) ApplyDefaults() {
}

// #/components/schemas/ObjectWithAnyOfProperty/properties/value

type ObjectWithAnyOfPropertyValue struct {
	union json.RawMessage
}

// AsString0 returns the union data inside the ObjectWithAnyOfPropertyValue as a string.
func (t ObjectWithAnyOfPropertyValue) AsString0() (string, error) {
	var body string
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromString0 overwrites any union data inside the ObjectWithAnyOfPropertyValue as the provided string.
func (t *ObjectWithAnyOfPropertyValue) FromString0(v string) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeString0 performs a merge with any union data inside the ObjectWithAnyOfPropertyValue, using the provided string.
func (t *ObjectWithAnyOfPropertyValue) MergeString0(v string) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInt1 returns the union data inside the ObjectWithAnyOfPropertyValue as a int.
func (t ObjectWithAnyOfPropertyValue) AsInt1() (int, error) {
	var body int
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInt1 overwrites any union data inside the ObjectWithAnyOfPropertyValue as the provided int.
func (t *ObjectWithAnyOfPropertyValue) FromInt1(v int) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInt1 performs a merge with any union data inside the ObjectWithAnyOfPropertyValue, using the provided int.
func (t *ObjectWithAnyOfPropertyValue) MergeInt1(v int) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ObjectWithAnyOfPropertyValue) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ObjectWithAnyOfPropertyValue) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *ObjectWithAnyOfPropertyValue) ApplyDefaults() {
}

// #/components/schemas/ObjectWithOneOfProperty
type ObjectWithOneOfProperty struct {
	Variant *ObjectWithOneOfPropertyVariant `form:"variant,omitempty" json:"variant,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ObjectWithOneOfProperty) ApplyDefaults() {
}

// #/components/schemas/ObjectWithOneOfProperty/properties/variant

type ObjectWithOneOfPropertyVariant struct {
	union json.RawMessage
}

// AsObjectWithOneOfPropertyVariantOneOf0 returns the union data inside the ObjectWithOneOfPropertyVariant as a ObjectWithOneOfPropertyVariantOneOf0.
func (t ObjectWithOneOfPropertyVariant) AsObjectWithOneOfPropertyVariantOneOf0() (ObjectWithOneOfPropertyVariantOneOf0, error) {
	var body ObjectWithOneOfPropertyVariantOneOf0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromObjectWithOneOfPropertyVariantOneOf0 overwrites any union data inside the ObjectWithOneOfPropertyVariant as the provided ObjectWithOneOfPropertyVariantOneOf0.
func (t *ObjectWithOneOfPropertyVariant) FromObjectWithOneOfPropertyVariantOneOf0(v ObjectWithOneOfPropertyVariantOneOf0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeObjectWithOneOfPropertyVariantOneOf0 performs a merge with any union data inside the ObjectWithOneOfPropertyVariant, using the provided ObjectWithOneOfPropertyVariantOneOf0.
func (t *ObjectWithOneOfPropertyVariant) MergeObjectWithOneOfPropertyVariantOneOf0(v ObjectWithOneOfPropertyVariantOneOf0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsObjectWithOneOfPropertyVariantOneOf1 returns the union data inside the ObjectWithOneOfPropertyVariant as a ObjectWithOneOfPropertyVariantOneOf1.
func (t ObjectWithOneOfPropertyVariant) AsObjectWithOneOfPropertyVariantOneOf1() (ObjectWithOneOfPropertyVariantOneOf1, error) {
	var body ObjectWithOneOfPropertyVariantOneOf1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromObjectWithOneOfPropertyVariantOneOf1 overwrites any union data inside the ObjectWithOneOfPropertyVariant as the provided ObjectWithOneOfPropertyVariantOneOf1.
func (t *ObjectWithOneOfPropertyVariant) FromObjectWithOneOfPropertyVariantOneOf1(v ObjectWithOneOfPropertyVariantOneOf1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeObjectWithOneOfPropertyVariantOneOf1 performs a merge with any union data inside the ObjectWithOneOfPropertyVariant, using the provided ObjectWithOneOfPropertyVariantOneOf1.
func (t *ObjectWithOneOfPropertyVariant) MergeObjectWithOneOfPropertyVariantOneOf1(v ObjectWithOneOfPropertyVariantOneOf1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ObjectWithOneOfPropertyVariant) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ObjectWithOneOfPropertyVariant) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *ObjectWithOneOfPropertyVariant) ApplyDefaults() {
}

// #/components/schemas/ObjectWithOneOfProperty/properties/variant/oneOf/0
type ObjectWithOneOfPropertyVariantOneOf0 struct {
	Kind *string `form:"kind,omitempty" json:"kind,omitempty"`
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ObjectWithOneOfPropertyVariantOneOf0) ApplyDefaults() {
}

// #/components/schemas/ObjectWithOneOfProperty/properties/variant/oneOf/1
type ObjectWithOneOfPropertyVariantOneOf1 struct {
	Kind  *string `form:"kind,omitempty" json:"kind,omitempty"`
	Count *int    `form:"count,omitempty" json:"count,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ObjectWithOneOfPropertyVariantOneOf1) ApplyDefaults() {
}

// #/components/schemas/AllOfWithOneOf
type AllOfWithOneOf struct {
	Base                 *string               `form:"base,omitempty" json:"base,omitempty"`
	AllOfWithOneOfAllOf1 *AllOfWithOneOfAllOf1 `json:"-"`
}

func (s AllOfWithOneOf) MarshalJSON() ([]byte, error) {
	result := make(map[string]any)

	if s.Base != nil {
		result["base"] = s.Base
	}

	if s.AllOfWithOneOfAllOf1 != nil {
		unionData, err := json.Marshal(s.AllOfWithOneOfAllOf1)
		if err != nil {
			return nil, err
		}
		var unionMap map[string]any
		if err := json.Unmarshal(unionData, &unionMap); err == nil {
			for k, v := range unionMap {
				result[k] = v
			}
		}
	}

	return json.Marshal(result)
}

func (s *AllOfWithOneOf) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	if v, ok := raw["base"]; ok {
		var val string
		if err := json.Unmarshal(v, &val); err != nil {
			return err
		}
		s.Base = &val
	}

	var AllOfWithOneOfAllOf1Val AllOfWithOneOfAllOf1
	if err := json.Unmarshal(data, &AllOfWithOneOfAllOf1Val); err != nil {
		return err
	}
	s.AllOfWithOneOfAllOf1 = &AllOfWithOneOfAllOf1Val

	return nil
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AllOfWithOneOf) ApplyDefaults() {
}

// #/components/schemas/AllOfWithOneOf/allOf/1

type AllOfWithOneOfAllOf1 struct {
	union json.RawMessage
}

// AsAllOfWithOneOfAllOf1OneOf0 returns the union data inside the AllOfWithOneOfAllOf1 as a AllOfWithOneOfAllOf1OneOf0.
func (t AllOfWithOneOfAllOf1) AsAllOfWithOneOfAllOf1OneOf0() (AllOfWithOneOfAllOf1OneOf0, error) {
	var body AllOfWithOneOfAllOf1OneOf0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAllOfWithOneOfAllOf1OneOf0 overwrites any union data inside the AllOfWithOneOfAllOf1 as the provided AllOfWithOneOfAllOf1OneOf0.
func (t *AllOfWithOneOfAllOf1) FromAllOfWithOneOfAllOf1OneOf0(v AllOfWithOneOfAllOf1OneOf0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAllOfWithOneOfAllOf1OneOf0 performs a merge with any union data inside the AllOfWithOneOfAllOf1, using the provided AllOfWithOneOfAllOf1OneOf0.
func (t *AllOfWithOneOfAllOf1) MergeAllOfWithOneOfAllOf1OneOf0(v AllOfWithOneOfAllOf1OneOf0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAllOfWithOneOfAllOf1OneOf1 returns the union data inside the AllOfWithOneOfAllOf1 as a AllOfWithOneOfAllOf1OneOf1.
func (t AllOfWithOneOfAllOf1) AsAllOfWithOneOfAllOf1OneOf1() (AllOfWithOneOfAllOf1OneOf1, error) {
	var body AllOfWithOneOfAllOf1OneOf1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAllOfWithOneOfAllOf1OneOf1 overwrites any union data inside the AllOfWithOneOfAllOf1 as the provided AllOfWithOneOfAllOf1OneOf1.
func (t *AllOfWithOneOfAllOf1) FromAllOfWithOneOfAllOf1OneOf1(v AllOfWithOneOfAllOf1OneOf1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAllOfWithOneOfAllOf1OneOf1 performs a merge with any union data inside the AllOfWithOneOfAllOf1, using the provided AllOfWithOneOfAllOf1OneOf1.
func (t *AllOfWithOneOfAllOf1) MergeAllOfWithOneOfAllOf1OneOf1(v AllOfWithOneOfAllOf1OneOf1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AllOfWithOneOfAllOf1) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AllOfWithOneOfAllOf1) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *AllOfWithOneOfAllOf1) ApplyDefaults() {
}

// #/components/schemas/AllOfWithOneOf/allOf/1/oneOf/0
type AllOfWithOneOfAllOf1OneOf0 struct {
	OptionA *bool `form:"optionA,omitempty" json:"optionA,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AllOfWithOneOfAllOf1OneOf0) ApplyDefaults() {
}

// #/components/schemas/AllOfWithOneOf/allOf/1/oneOf/1
type AllOfWithOneOfAllOf1OneOf1 struct {
	OptionB *int `form:"optionB,omitempty" json:"optionB,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AllOfWithOneOfAllOf1OneOf1) ApplyDefaults() {
}

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/7yTQY/TMBCF7/kVT+W8K5bl5FvgTjggcXbTSTKQjC17WlQh/juKk9KkTVqBKnpq5nnG",
	"75uXOE9iPRtsXp9fnt9uMpbKmQxQ1pYMPlFU2iGv60C1VcIXipoBBwqRnRhsUpe32kSDn7+y0nXeCYnG",
	"fkosG+ps+gu8wUcbCS8GeQj2iB+sDawciwqs1MV0KElFlffloQ3QoycD2ytjJZ0/yRiGnB+Bp7EnamCp",
	"FwS3/UalTgTAB+cpKFM0szrAu8vKyROLUk0hm/K9MyjS9CngOHzwP8hfWZuE+XnU5rgzh0veDrbd09TY",
	"1RZu7OEsLSG8zhGc0AQBpRO1LCw1WFoWGr3GC7iib/tnuMBWdEqTXCzjLaR5K0/gO8tCpljfVv8T29Ff",
	"Nf1fe6Xbzxd2/1V9b2DbtqimkaY1D59iL/0J8jQ5NZyvWWVc49vaeLXFRa6nhybuvLKTfH0/W+dasvLI",
	"2z7cT+N3AAAA//8nzKKtgAUAAA==",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}
