// Code generated by oapi-codegen; DO NOT EDIT.

package client

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"
)

// #/components/schemas/Object
type Object struct {
	Role      string `form:"role" json:"role"`
	FirstName string `form:"firstName" json:"firstName"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Object) ApplyDefaults() {
}

// #/components/schemas/ComplexObject
type ComplexObject struct {
	Object  Object `form:"Object" json:"Object"`
	ID      int    `form:"Id" json:"Id"`
	IsAdmin bool   `form:"IsAdmin" json:"IsAdmin"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ComplexObject) ApplyDefaults() {
}

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/9xazY7bNhC++ykIt0CAAP5JclNOi7RFF0jTbZpDrlxxvGYqkQxJB7so+u6FRNkmJdki",
	"ZdOSfVtRHHLmm79P4+UCGBY0QdN38+X8zXRC2YonE4R+gFSUswS9mS/nywlCmuoMEvSAJc5Bg0Sf+YYR",
	"LalAX0DpCUIZTYEpKKQRYjiHBN0JnK5h9na+nAis16p4t1A0Fxk8SJpTTX/A4l9RnPmfkXsCbf5AiAuQ",
	"WFPO7klSrP/tylW7xFYhtZVDaFZdX77brSJEWbGm19aShO8bKoEkSMsNWC+UfinsNcra6+kacpxYKwjp",
	"FwEJokzDE0jnzYrLHOvy3bu3k+2VSnCmwFL41dvl8pV95s8SVgma/rRIeS44A6bVYie3MEh8rp6ne1A/",
	"8V+fRcYJ3EmJXwKRdYUHgheMCgla4Uz54Y4tdStFNOTK3XrMSRd3U4uTXvt6aUw+qu+/IRftkuHPx2+Q",
	"6r6pZKSvIZfacDL71MJYMb1YYjiYh2bGOCD3SI0xId63G9fFr6YiDdqsM/wImQX53BPzj47cZbAudT2t",
	"QQ+PdTPK57615WOb/MDQX1GU1xlpUKgPwUjPEO/XxHbs9HBcFJgaY/DQTdJRN4u2zKhfGl2SGp2URwNT",
	"IzspXMQDs2IUgI+fiuZYS/psdef3lHQD/Ycr5YEyJadBbPS8YjJkDGiyofeUvPYFvAcXiof7dTAho3+D",
	"CvkHeTARGkOkX1OXdRJj75/QpBjePTfJgWr5s2vJPRLIuyMPm0GjaMhNuEPzYQRoj5/9pJxpYDpw0PzB",
	"lorMMCsNXdSwEBlNS5UW3xRn9crRhnQX2h94gc7zBUAXWKkva8k3T2tvyB/2MkMAruFZL0SGqTfUpngr",
	"LSl7ignm9w3Il9+4zDsh/Gu70wNAwJZOBFQqqdDlb9JVcpNGEyswLpVpBblReE3tWO3VGVUr3SNxEIio",
	"9g/O9KxQ4J2hwO1CGI5FnH6xt+CgAefS+7yswoJedEIvap+CcdEP+56z6vEhO86o/vnHAJb+qtMAt9T3",
	"KAgH1a0dvNUpPRjWqenkp4b3DTKP0vhfAIS5q7Nl7rd69ExiNh/ySvE61CXthJvUtTpnEfV1BoEV3mT6",
	"JHesAROQnV74vdzm4YGvs4eWeuJVcNb2HSOoOJYps+qDjnTXIGju7GtcxG7wdVbOajrtOko1o9oUnVRV",
	"EIRwy7gRegGLTUnx93prrYzk9j7sbGtRELuM5cV+BlTFvsOQo3wiwKDREYpz9LCU838oeIyMim0+o4vQ",
	"zpXaJ4+gc53w0dLHlIh9qucQJKoV45p3xI290Y42Ink4/mwjlr/6aN7z+zXAhNvrN/tNxRnV9eY4+4sW",
	"ISGLBqSpfbvkGdhXt04XVlQq/alw0KRjll2hbvm1uMB63B1VrjkYHVPT3REaXfekqXi9NNyrO5K7k3yz",
	"8ZHzDDA7YmKNKM3QPbEfzMGThvNdP24PdIL+rvrP6p2oG/6NWG7/RaJzivR/AAAA///CjtKydTYAAA==",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}

// RequestEditorFn is the function signature for the RequestEditor callback function.
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// HttpRequestDoer performs HTTP requests.
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the OpenAPI spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction.
type ClientOption func(*Client) error

// NewClient creates a new Client with reasonable defaults.
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	client := Client{
		Server: server,
	}
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// Ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// Create httpClient if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientInterface is the interface specification for the client.
type ClientInterface interface {
	// GetContentObject makes a GET request to /contentObject/{param}
	GetContentObject(ctx context.Context, param string, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetCookie makes a GET request to /cookie
	GetCookie(ctx context.Context, params *GetCookieParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetHeader makes a GET request to /header
	GetHeader(ctx context.Context, params *GetHeaderParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetLabelExplodeArray makes a GET request to /labelExplodeArray/{.param*}
	GetLabelExplodeArray(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetLabelExplodeObject makes a GET request to /labelExplodeObject/{.param*}
	GetLabelExplodeObject(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetLabelExplodePrimitive makes a GET request to /labelExplodePrimitive/{.param*}
	GetLabelExplodePrimitive(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetLabelNoExplodeArray makes a GET request to /labelNoExplodeArray/{.param}
	GetLabelNoExplodeArray(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetLabelNoExplodeObject makes a GET request to /labelNoExplodeObject/{.param}
	GetLabelNoExplodeObject(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetLabelPrimitive makes a GET request to /labelPrimitive/{.param}
	GetLabelPrimitive(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetMatrixExplodeArray makes a GET request to /matrixExplodeArray/{.id*}
	GetMatrixExplodeArray(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetMatrixExplodeObject makes a GET request to /matrixExplodeObject/{.id*}
	GetMatrixExplodeObject(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetMatrixExplodePrimitive makes a GET request to /matrixExplodePrimitive/{;id*}
	GetMatrixExplodePrimitive(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetMatrixNoExplodeArray makes a GET request to /matrixNoExplodeArray/{.id}
	GetMatrixNoExplodeArray(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetMatrixNoExplodeObject makes a GET request to /matrixNoExplodeObject/{.id}
	GetMatrixNoExplodeObject(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetMatrixPrimitive makes a GET request to /matrixPrimitive/{;id}
	GetMatrixPrimitive(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetPassThrough makes a GET request to /passThrough/{param}
	GetPassThrough(ctx context.Context, param string, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetDeepObject makes a GET request to /queryDeepObject
	GetDeepObject(ctx context.Context, params *GetDeepObjectParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetQueryForm makes a GET request to /queryForm
	GetQueryForm(ctx context.Context, params *GetQueryFormParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetSimpleExplodeArray makes a GET request to /simpleExplodeArray/{param*}
	GetSimpleExplodeArray(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetSimpleExplodeObject makes a GET request to /simpleExplodeObject/{param*}
	GetSimpleExplodeObject(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetSimpleExplodePrimitive makes a GET request to /simpleExplodePrimitive/{param}
	GetSimpleExplodePrimitive(ctx context.Context, param int32, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetSimpleNoExplodeArray makes a GET request to /simpleNoExplodeArray/{param}
	GetSimpleNoExplodeArray(ctx context.Context, param []int32, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetSimpleNoExplodeObject makes a GET request to /simpleNoExplodeObject/{param}
	GetSimpleNoExplodeObject(ctx context.Context, param any, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetSimplePrimitive makes a GET request to /simplePrimitive/{param}
	GetSimplePrimitive(ctx context.Context, param int32, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetCookieParams defines parameters for GetCookie.
type GetCookieParams struct {
	// p (cookie)
	P *int32
	// ep (cookie)
	Ep *int32
	// ea (cookie)
	Ea *[]int32
	// a (cookie)
	A *[]int32
	// eo (cookie)
	Eo *any
	// o (cookie)
	O *any
	// co (cookie)
	Co *string
}

// GetHeaderParams defines parameters for GetHeader.
type GetHeaderParams struct {
	// X-Primitive (header)
	XPrimitive *int32
	// X-Primitive-Exploded (header)
	XPrimitiveExploded *int32
	// X-Array-Exploded (header)
	XArrayExploded *[]int32
	// X-Array (header)
	XArray *[]int32
	// X-Object-Exploded (header)
	XObjectExploded *any
	// X-Object (header)
	XObject *any
	// X-Complex-Object (header)
	XComplexObject *string
}

// GetDeepObjectParams defines parameters for GetDeepObject.
type GetDeepObjectParams struct {
	// deepObj (required)
	DeepObj any `form:"deepObj" json:"deepObj"`
}

// GetQueryFormParams defines parameters for GetQueryForm.
type GetQueryFormParams struct {
	// ea (optional)
	Ea *[]int32 `form:"ea" json:"ea"`
	// a (optional)
	A *[]int32 `form:"a" json:"a"`
	// eo (optional)
	Eo *any `form:"eo" json:"eo"`
	// o (optional)
	O *any `form:"o" json:"o"`
	// ep (optional)
	Ep *int32 `form:"ep" json:"ep"`
	// p (optional)
	P *int32 `form:"p" json:"p"`
	// ps (optional)
	Ps *string `form:"ps" json:"ps"`
	// co (optional)
	Co *string `form:"co" json:"co"`
}

// GetContentObject makes a GET request to /contentObject/{param}

func (c *Client) GetContentObject(ctx context.Context, param string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetContentObjectRequest(c.Server, param)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetCookie makes a GET request to /cookie

func (c *Client) GetCookie(ctx context.Context, params *GetCookieParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCookieRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetHeader makes a GET request to /header

func (c *Client) GetHeader(ctx context.Context, params *GetHeaderParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHeaderRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetLabelExplodeArray makes a GET request to /labelExplodeArray/{.param*}

func (c *Client) GetLabelExplodeArray(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetLabelExplodeArrayRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetLabelExplodeObject makes a GET request to /labelExplodeObject/{.param*}

func (c *Client) GetLabelExplodeObject(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetLabelExplodeObjectRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetLabelExplodePrimitive makes a GET request to /labelExplodePrimitive/{.param*}

func (c *Client) GetLabelExplodePrimitive(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetLabelExplodePrimitiveRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetLabelNoExplodeArray makes a GET request to /labelNoExplodeArray/{.param}

func (c *Client) GetLabelNoExplodeArray(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetLabelNoExplodeArrayRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetLabelNoExplodeObject makes a GET request to /labelNoExplodeObject/{.param}

func (c *Client) GetLabelNoExplodeObject(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetLabelNoExplodeObjectRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetLabelPrimitive makes a GET request to /labelPrimitive/{.param}

func (c *Client) GetLabelPrimitive(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetLabelPrimitiveRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetMatrixExplodeArray makes a GET request to /matrixExplodeArray/{.id*}

func (c *Client) GetMatrixExplodeArray(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMatrixExplodeArrayRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetMatrixExplodeObject makes a GET request to /matrixExplodeObject/{.id*}

func (c *Client) GetMatrixExplodeObject(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMatrixExplodeObjectRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetMatrixExplodePrimitive makes a GET request to /matrixExplodePrimitive/{;id*}

func (c *Client) GetMatrixExplodePrimitive(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMatrixExplodePrimitiveRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetMatrixNoExplodeArray makes a GET request to /matrixNoExplodeArray/{.id}

func (c *Client) GetMatrixNoExplodeArray(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMatrixNoExplodeArrayRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetMatrixNoExplodeObject makes a GET request to /matrixNoExplodeObject/{.id}

func (c *Client) GetMatrixNoExplodeObject(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMatrixNoExplodeObjectRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetMatrixPrimitive makes a GET request to /matrixPrimitive/{;id}

func (c *Client) GetMatrixPrimitive(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMatrixPrimitiveRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetPassThrough makes a GET request to /passThrough/{param}

func (c *Client) GetPassThrough(ctx context.Context, param string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPassThroughRequest(c.Server, param)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetDeepObject makes a GET request to /queryDeepObject

func (c *Client) GetDeepObject(ctx context.Context, params *GetDeepObjectParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDeepObjectRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetQueryForm makes a GET request to /queryForm

func (c *Client) GetQueryForm(ctx context.Context, params *GetQueryFormParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetQueryFormRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetSimpleExplodeArray makes a GET request to /simpleExplodeArray/{param*}

func (c *Client) GetSimpleExplodeArray(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSimpleExplodeArrayRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetSimpleExplodeObject makes a GET request to /simpleExplodeObject/{param*}

func (c *Client) GetSimpleExplodeObject(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSimpleExplodeObjectRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetSimpleExplodePrimitive makes a GET request to /simpleExplodePrimitive/{param}

func (c *Client) GetSimpleExplodePrimitive(ctx context.Context, param int32, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSimpleExplodePrimitiveRequest(c.Server, param)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetSimpleNoExplodeArray makes a GET request to /simpleNoExplodeArray/{param}

func (c *Client) GetSimpleNoExplodeArray(ctx context.Context, param []int32, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSimpleNoExplodeArrayRequest(c.Server, param)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetSimpleNoExplodeObject makes a GET request to /simpleNoExplodeObject/{param}

func (c *Client) GetSimpleNoExplodeObject(ctx context.Context, param any, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSimpleNoExplodeObjectRequest(c.Server, param)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetSimplePrimitive makes a GET request to /simplePrimitive/{param}

func (c *Client) GetSimplePrimitive(ctx context.Context, param int32, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSimplePrimitiveRequest(c.Server, param)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetContentObjectRequest creates a GET request for /contentObject/{param}
func NewGetContentObjectRequest(server string, param string) (*http.Request, error) {
	var err error

	var pathParam0 string
	var pathParamBuf0 []byte
	pathParamBuf0, err = json.Marshal(param)
	if err != nil {
		return nil, err
	}
	pathParam0 = string(pathParamBuf0)

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/contentObject/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCookieRequest creates a GET request for /cookie
func NewGetCookieRequest(server string, params *GetCookieParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/cookie")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {
		if params.P != nil {
			var cookieParam0 string
			cookieParam0, err = StyleSimpleParam("p", ParamLocationCookie, *params.P)
			if err != nil {
				return nil, err
			}
			cookie0 := &http.Cookie{
				Name:  "p",
				Value: cookieParam0,
			}
			req.AddCookie(cookie0)
		}
		if params.Ep != nil {
			var cookieParam1 string
			cookieParam1, err = StyleSimpleParam("ep", ParamLocationCookie, *params.Ep)
			if err != nil {
				return nil, err
			}
			cookie1 := &http.Cookie{
				Name:  "ep",
				Value: cookieParam1,
			}
			req.AddCookie(cookie1)
		}
		if params.Ea != nil {
			var cookieParam2 string
			cookieParam2, err = StyleSimpleParam("ea", ParamLocationCookie, *params.Ea)
			if err != nil {
				return nil, err
			}
			cookie2 := &http.Cookie{
				Name:  "ea",
				Value: cookieParam2,
			}
			req.AddCookie(cookie2)
		}
		if params.A != nil {
			var cookieParam3 string
			cookieParam3, err = StyleSimpleParam("a", ParamLocationCookie, *params.A)
			if err != nil {
				return nil, err
			}
			cookie3 := &http.Cookie{
				Name:  "a",
				Value: cookieParam3,
			}
			req.AddCookie(cookie3)
		}
		if params.Eo != nil {
			var cookieParam4 string
			cookieParam4, err = StyleSimpleParam("eo", ParamLocationCookie, *params.Eo)
			if err != nil {
				return nil, err
			}
			cookie4 := &http.Cookie{
				Name:  "eo",
				Value: cookieParam4,
			}
			req.AddCookie(cookie4)
		}
		if params.O != nil {
			var cookieParam5 string
			cookieParam5, err = StyleSimpleParam("o", ParamLocationCookie, *params.O)
			if err != nil {
				return nil, err
			}
			cookie5 := &http.Cookie{
				Name:  "o",
				Value: cookieParam5,
			}
			req.AddCookie(cookie5)
		}
		if params.Co != nil {
			var cookieParam6 string
			var cookieParamBuf6 []byte
			cookieParamBuf6, err = json.Marshal(*params.Co)
			if err != nil {
				return nil, err
			}
			cookieParam6 = url.QueryEscape(string(cookieParamBuf6))
			cookie6 := &http.Cookie{
				Name:  "co",
				Value: cookieParam6,
			}
			req.AddCookie(cookie6)
		}
	}

	return req, nil
}

// NewGetHeaderRequest creates a GET request for /header
func NewGetHeaderRequest(server string, params *GetHeaderParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/header")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {
		if params.XPrimitive != nil {
			var headerParam0 string
			headerParam0, err = StyleSimpleParam("X-Primitive", ParamLocationHeader, *params.XPrimitive)
			if err != nil {
				return nil, err
			}
			req.Header.Set("X-Primitive", headerParam0)
		}
		if params.XPrimitiveExploded != nil {
			var headerParam1 string
			headerParam1, err = StyleSimpleExplodeParam("X-Primitive-Exploded", ParamLocationHeader, *params.XPrimitiveExploded)
			if err != nil {
				return nil, err
			}
			req.Header.Set("X-Primitive-Exploded", headerParam1)
		}
		if params.XArrayExploded != nil {
			var headerParam2 string
			headerParam2, err = StyleSimpleExplodeParam("X-Array-Exploded", ParamLocationHeader, *params.XArrayExploded)
			if err != nil {
				return nil, err
			}
			req.Header.Set("X-Array-Exploded", headerParam2)
		}
		if params.XArray != nil {
			var headerParam3 string
			headerParam3, err = StyleSimpleParam("X-Array", ParamLocationHeader, *params.XArray)
			if err != nil {
				return nil, err
			}
			req.Header.Set("X-Array", headerParam3)
		}
		if params.XObjectExploded != nil {
			var headerParam4 string
			headerParam4, err = StyleSimpleExplodeParam("X-Object-Exploded", ParamLocationHeader, *params.XObjectExploded)
			if err != nil {
				return nil, err
			}
			req.Header.Set("X-Object-Exploded", headerParam4)
		}
		if params.XObject != nil {
			var headerParam5 string
			headerParam5, err = StyleSimpleParam("X-Object", ParamLocationHeader, *params.XObject)
			if err != nil {
				return nil, err
			}
			req.Header.Set("X-Object", headerParam5)
		}
		if params.XComplexObject != nil {
			var headerParam6 string
			var headerParamBuf6 []byte
			headerParamBuf6, err = json.Marshal(*params.XComplexObject)
			if err != nil {
				return nil, err
			}
			headerParam6 = string(headerParamBuf6)
			req.Header.Set("X-Complex-Object", headerParam6)
		}
	}

	return req, nil
}

// NewGetLabelExplodeArrayRequest creates a GET request for /labelExplodeArray/{.param*}
func NewGetLabelExplodeArrayRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/labelExplodeArray/%s")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetLabelExplodeObjectRequest creates a GET request for /labelExplodeObject/{.param*}
func NewGetLabelExplodeObjectRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/labelExplodeObject/%s")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetLabelExplodePrimitiveRequest creates a GET request for /labelExplodePrimitive/{.param*}
func NewGetLabelExplodePrimitiveRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/labelExplodePrimitive/%s")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetLabelNoExplodeArrayRequest creates a GET request for /labelNoExplodeArray/{.param}
func NewGetLabelNoExplodeArrayRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/labelNoExplodeArray/%s")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetLabelNoExplodeObjectRequest creates a GET request for /labelNoExplodeObject/{.param}
func NewGetLabelNoExplodeObjectRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/labelNoExplodeObject/%s")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetLabelPrimitiveRequest creates a GET request for /labelPrimitive/{.param}
func NewGetLabelPrimitiveRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/labelPrimitive/%s")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMatrixExplodeArrayRequest creates a GET request for /matrixExplodeArray/{.id*}
func NewGetMatrixExplodeArrayRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/matrixExplodeArray/%s")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMatrixExplodeObjectRequest creates a GET request for /matrixExplodeObject/{.id*}
func NewGetMatrixExplodeObjectRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/matrixExplodeObject/%s")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMatrixExplodePrimitiveRequest creates a GET request for /matrixExplodePrimitive/{;id*}
func NewGetMatrixExplodePrimitiveRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/matrixExplodePrimitive/%s")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMatrixNoExplodeArrayRequest creates a GET request for /matrixNoExplodeArray/{.id}
func NewGetMatrixNoExplodeArrayRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/matrixNoExplodeArray/%s")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMatrixNoExplodeObjectRequest creates a GET request for /matrixNoExplodeObject/{.id}
func NewGetMatrixNoExplodeObjectRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/matrixNoExplodeObject/%s")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMatrixPrimitiveRequest creates a GET request for /matrixPrimitive/{;id}
func NewGetMatrixPrimitiveRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/matrixPrimitive/%s")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPassThroughRequest creates a GET request for /passThrough/{param}
func NewGetPassThroughRequest(server string, param string) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0 = param

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/passThrough/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDeepObjectRequest creates a GET request for /queryDeepObject
func NewGetDeepObjectRequest(server string, params *GetDeepObjectParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/queryDeepObject")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if queryFrag, err := StyleDeepObjectParam("deepObj", ParamLocationQuery, params.DeepObj); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetQueryFormRequest creates a GET request for /queryForm
func NewGetQueryFormRequest(server string, params *GetQueryFormParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/queryForm")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.Ea != nil {
			if queryFrag, err := StyleFormExplodeParam("ea", ParamLocationQuery, *params.Ea); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.A != nil {
			if queryFrag, err := StyleFormParam("a", ParamLocationQuery, *params.A); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.Eo != nil {
			if queryFrag, err := StyleFormExplodeParam("eo", ParamLocationQuery, *params.Eo); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.O != nil {
			if queryFrag, err := StyleFormParam("o", ParamLocationQuery, *params.O); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.Ep != nil {
			if queryFrag, err := StyleFormExplodeParam("ep", ParamLocationQuery, *params.Ep); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.P != nil {
			if queryFrag, err := StyleFormParam("p", ParamLocationQuery, *params.P); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.Ps != nil {
			if queryFrag, err := StyleFormExplodeParam("ps", ParamLocationQuery, *params.Ps); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.Co != nil {
			if queryParamBuf, err := json.Marshal(*params.Co); err != nil {
				return nil, err
			} else {
				queryValues.Add("co", string(queryParamBuf))
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSimpleExplodeArrayRequest creates a GET request for /simpleExplodeArray/{param*}
func NewGetSimpleExplodeArrayRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/simpleExplodeArray/%s")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSimpleExplodeObjectRequest creates a GET request for /simpleExplodeObject/{param*}
func NewGetSimpleExplodeObjectRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/simpleExplodeObject/%s")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSimpleExplodePrimitiveRequest creates a GET request for /simpleExplodePrimitive/{param}
func NewGetSimpleExplodePrimitiveRequest(server string, param int32) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = StyleSimpleExplodeParam("param", ParamLocationPath, param)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/simpleExplodePrimitive/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSimpleNoExplodeArrayRequest creates a GET request for /simpleNoExplodeArray/{param}
func NewGetSimpleNoExplodeArrayRequest(server string, param []int32) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = StyleSimpleParam("param", ParamLocationPath, param)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/simpleNoExplodeArray/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSimpleNoExplodeObjectRequest creates a GET request for /simpleNoExplodeObject/{param}
func NewGetSimpleNoExplodeObjectRequest(server string, param any) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = StyleSimpleParam("param", ParamLocationPath, param)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/simpleNoExplodeObject/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSimplePrimitiveRequest creates a GET request for /simplePrimitive/{param}
func NewGetSimplePrimitiveRequest(server string, param int32) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = StyleSimpleParam("param", ParamLocationPath, param)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/simplePrimitive/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

const DateFormat = "2006-01-02"

type Date struct {
	time.Time
}

func (d Date) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.Format(DateFormat))
}

func (d *Date) UnmarshalJSON(data []byte) error {
	var dateStr string
	err := json.Unmarshal(data, &dateStr)
	if err != nil {
		return err
	}
	parsed, err := time.Parse(DateFormat, dateStr)
	if err != nil {
		return err
	}
	d.Time = parsed
	return nil
}

func (d Date) String() string {
	return d.Format(DateFormat)
}

func (d *Date) UnmarshalText(data []byte) error {
	parsed, err := time.Parse(DateFormat, string(data))
	if err != nil {
		return err
	}
	d.Time = parsed
	return nil
}

// MarshalText implements encoding.TextMarshaler for Date.
func (d Date) MarshalText() ([]byte, error) {
	return []byte(d.Format(DateFormat)), nil
}

// Format returns the date formatted according to layout.
func (d Date) Format(layout string) string {
	return d.Time.Format(layout)
}

// ErrValidationEmail is the sentinel error returned when an email fails validation

// Email represents an email address.
// It is a string type that must pass regex validation before being marshalled
// to JSON or unmarshalled from JSON.

// Nullable is a generic type that can distinguish between:
// - Field not provided (unspecified)
// - Field explicitly set to null
// - Field has a value
//
// This is implemented as a map[bool]T where:
// - Empty map: unspecified
// - map[false]T: explicitly null
// - map[true]T: has a value

// NewNullableWithValue creates a Nullable with the given value.

// NewNullNullable creates a Nullable that is explicitly null.

// Get returns the value if set, or an error if null or unspecified.

// MustGet returns the value or panics if null or unspecified.

// Set assigns a value.

// SetNull marks the field as explicitly null.

// SetUnspecified clears the field (as if it was never set).

// IsNull returns true if the field is explicitly null.

// IsSpecified returns true if the field was provided (either null or a value).

// MarshalJSON implements json.Marshaler.

// Unspecified - this shouldn't be called if omitempty is used correctly

// UnmarshalJSON implements json.Unmarshaler.

// ErrNullableIsNull is returned when trying to get a value from a null Nullable.

// ErrNullableNotSpecified is returned when trying to get a value from an unspecified Nullable.

type UUID = uuid.UUID

// BindDeepObjectParam binds a deepObject-style parameter to a destination.
// DeepObject style is only valid for query parameters and must be exploded.
// Objects: ?paramName[key1]=value1&paramName[key2]=value2 -> struct{Key1, Key2}
// Nested: ?paramName[outer][inner]=value -> struct{Outer: {Inner: value}}

// UnmarshalDeepObject unmarshals deepObject-style query parameters to a destination.

// Find all params that look like "paramName[..."

// Trim the parameter name prefix

// Reconstruct subscript paths

// Check for Binder interface

// Handle Date type

// Handle time.Time type

// Regular struct

// BindFormParam binds a form-style parameter without explode to a destination.
// Form style is the default for query and cookie parameters.
// This function handles a single query parameter value (not url.Values).
// Arrays: a,b,c -> []string{"a", "b", "c"}
// Objects: key1,value1,key2,value2 -> struct{Key1, Key2}

// Unescape based on location

// Check for TextUnmarshaler

// BindFormExplodeParam binds a form-style parameter with explode to a destination.
// Form style is the default for query and cookie parameters.
// This handles the exploded case where arrays come as multiple query params.
// Arrays: ?param=a&param=b -> []string{"a", "b"} (values passed as slice)
// Objects: ?key1=value1&key2=value2 -> struct{Key1, Key2} (queryParams passed)

// For optional parameters, allocate if nil

// For exploded objects, fields are spread across query params

// Primitive

// bindParamsToExplodedObject binds query params to struct fields for exploded objects.

// indirectBinder checks if dest implements Binder and returns reflect values.

// Handle special types like time.Time and Date

// BindLabelParam binds a label-style parameter without explode to a destination.
// Label style values are prefixed with a dot.
// Primitives: .value -> "value"
// Arrays: .a,b,c -> []string{"a", "b", "c"}
// Objects: .key1,value1,key2,value2 -> struct{Key1, Key2}

// Unescape based on location

// Label style requires leading dot

// Strip the leading dot and split on comma

// Check for TextUnmarshaler

// BindLabelExplodeParam binds a label-style parameter with explode to a destination.
// Label style values are prefixed with a dot.
// Primitives: .value -> "value"
// Arrays: .a.b.c -> []string{"a", "b", "c"}
// Objects: .key1=value1.key2=value2 -> struct{Key1, Key2}

// Unescape based on location

// Label style requires leading dot

// Check for TextUnmarshaler

// Split on dot (skip first empty part)

// Split on dot (skip first empty part)

// BindMatrixParam binds a matrix-style parameter without explode to a destination.
// Matrix style values are prefixed with ;paramName=.
// Primitives: ;paramName=value -> "value"
// Arrays: ;paramName=a,b,c -> []string{"a", "b", "c"}
// Objects: ;paramName=key1,value1,key2,value2 -> struct{Key1, Key2}

// Unescape based on location

// Matrix style requires ;paramName= prefix

// Strip the prefix

// Check for TextUnmarshaler

// BindMatrixExplodeParam binds a matrix-style parameter with explode to a destination.
// Matrix style values are prefixed with semicolons.
// Primitives: ;paramName=value -> "value"
// Arrays: ;paramName=a;paramName=b;paramName=c -> []string{"a", "b", "c"}
// Objects: ;key1=value1;key2=value2 -> struct{Key1, Key2}

// Unescape based on location

// Break up on semicolon

// First part should be empty since we start with ;

// Check for TextUnmarshaler

// For primitives, should be ;paramName=value

// For objects, we have key1=value1, key2=value2

// For arrays, strip paramName= prefix from each part

// Primitive: ;paramName=value

// BindPipeDelimitedParam binds a pipeDelimited-style parameter without explode.
// Pipe-delimited style uses pipe as the separator.
// Arrays: a|b|c -> []string{"a", "b", "c"}

// Unescape based on location

// Check for TextUnmarshaler

// BindPipeDelimitedExplodeParam binds a pipeDelimited-style parameter with explode.
// When exploded, arrays come as multiple query params (same as form explode).
// Arrays: ?param=a&param=b -> []string{"a", "b"}

// Exploded pipe-delimited is same as exploded form

// BindSimpleParam binds a simple-style parameter without explode to a destination.
// Simple style is the default for path and header parameters.
// Arrays: a,b,c -> []string{"a", "b", "c"}
// Objects: key1,value1,key2,value2 -> struct{Key1, Key2}

// Unescape based on location

// Check for TextUnmarshaler

// Split on comma and bind as key,value pairs

// BindSimpleExplodeParam binds a simple-style parameter with explode to a destination.
// Simple style is the default for path and header parameters.
// Arrays: a,b,c -> []string{"a", "b", "c"} (same as non-explode)
// Objects: key1=value1,key2=value2 -> struct{Key1, Key2}

// Unescape based on location

// Check for TextUnmarshaler

// Split on comma and bind as key=value pairs

// BindSpaceDelimitedParam binds a spaceDelimited-style parameter without explode.
// Space-delimited style uses space as the separator.
// Arrays: a b c -> []string{"a", "b", "c"}

// Unescape based on location

// Check for TextUnmarshaler

// BindSpaceDelimitedExplodeParam binds a spaceDelimited-style parameter with explode.
// When exploded, arrays come as multiple query params (same as form explode).
// Arrays: ?param=a&param=b -> []string{"a", "b"}

// Exploded space-delimited is same as exploded form

// ParamLocation indicates where a parameter is located in an HTTP request.
type ParamLocation int

const (
	ParamLocationUndefined ParamLocation = iota
	ParamLocationQuery
	ParamLocationPath
	ParamLocationHeader
	ParamLocationCookie
)

// Binder is an interface for types that can bind themselves from a string value.

// primitiveToString converts a primitive value to a string representation.
// It handles basic Go types, time.Time, Date, and types that implement
// json.Marshaler or fmt.Stringer.
func primitiveToString(value any) (string, error) {
	// Check for known types first (time, date, uuid)
	if res, ok := marshalKnownTypes(value); ok {
		return res, nil
	}

	// Dereference pointers for optional values
	v := reflect.Indirect(reflect.ValueOf(value))
	t := v.Type()
	kind := t.Kind()

	switch kind {
	case reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64, reflect.Int:
		return strconv.FormatInt(v.Int(), 10), nil
	case reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uint:
		return strconv.FormatUint(v.Uint(), 10), nil
	case reflect.Float64:
		return strconv.FormatFloat(v.Float(), 'f', -1, 64), nil
	case reflect.Float32:
		return strconv.FormatFloat(v.Float(), 'f', -1, 32), nil
	case reflect.Bool:
		if v.Bool() {
			return "true", nil
		}
		return "false", nil
	case reflect.String:
		return v.String(), nil
	case reflect.Struct:
		// Check if it's a UUID
		if u, ok := value.(uuid.UUID); ok {
			return u.String(), nil
		}
		// Check if it implements json.Marshaler
		if m, ok := value.(json.Marshaler); ok {
			buf, err := m.MarshalJSON()
			if err != nil {
				return "", fmt.Errorf("failed to marshal to JSON: %w", err)
			}
			e := json.NewDecoder(bytes.NewReader(buf))
			e.UseNumber()
			var i2 any
			if err = e.Decode(&i2); err != nil {
				return "", fmt.Errorf("failed to decode JSON: %w", err)
			}
			return primitiveToString(i2)
		}
		fallthrough
	default:
		if s, ok := value.(fmt.Stringer); ok {
			return s.String(), nil
		}
		return "", fmt.Errorf("unsupported type %s", reflect.TypeOf(value).String())
	}
}

// marshalKnownTypes checks for special types (time.Time, Date, UUID) and marshals them.
func marshalKnownTypes(value any) (string, bool) {
	v := reflect.Indirect(reflect.ValueOf(value))
	t := v.Type()

	if t.ConvertibleTo(reflect.TypeOf(time.Time{})) {
		tt := v.Convert(reflect.TypeOf(time.Time{}))
		timeVal := tt.Interface().(time.Time)
		return timeVal.Format(time.RFC3339Nano), true
	}

	if t.ConvertibleTo(reflect.TypeOf(Date{})) {
		d := v.Convert(reflect.TypeOf(Date{}))
		dateVal := d.Interface().(Date)
		return dateVal.Format(DateFormat), true
	}

	if t.ConvertibleTo(reflect.TypeOf(uuid.UUID{})) {
		u := v.Convert(reflect.TypeOf(uuid.UUID{}))
		uuidVal := u.Interface().(uuid.UUID)
		return uuidVal.String(), true
	}

	return "", false
}

// escapeParameterString escapes a parameter value based on its location.
// Query and path parameters need URL escaping; headers and cookies do not.
func escapeParameterString(value string, paramLocation ParamLocation) string {
	switch paramLocation {
	case ParamLocationQuery:
		return url.QueryEscape(value)
	case ParamLocationPath:
		return url.PathEscape(value)
	default:
		return value
	}
}

// unescapeParameterString unescapes a parameter value based on its location.

// sortedKeys returns the keys of a map in sorted order.
func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// BindStringToObject binds a string value to a destination object.
// It handles primitives, encoding.TextUnmarshaler, and the Binder interface.

// Check for TextUnmarshaler

// Check for Binder interface

// Try JSON unmarshal as a fallback

// bindSplitPartsToDestinationArray binds a slice of string parts to a destination slice.

// bindSplitPartsToDestinationStruct binds string parts to a destination struct via JSON.

// structToFieldDict converts a struct to a map of field names to string values.
func structToFieldDict(value any) (map[string]string, error) {
	v := reflect.ValueOf(value)
	t := reflect.TypeOf(value)
	fieldDict := make(map[string]string)

	for i := 0; i < t.NumField(); i++ {
		fieldT := t.Field(i)
		tag := fieldT.Tag.Get("json")
		fieldName := fieldT.Name
		if tag != "" {
			tagParts := strings.Split(tag, ",")
			if tagParts[0] != "" {
				fieldName = tagParts[0]
			}
		}
		f := v.Field(i)

		// Skip nil optional fields
		if f.Type().Kind() == reflect.Ptr && f.IsNil() {
			continue
		}
		str, err := primitiveToString(f.Interface())
		if err != nil {
			return nil, fmt.Errorf("error formatting field '%s': %w", fieldName, err)
		}
		fieldDict[fieldName] = str
	}
	return fieldDict, nil
}

// StyleDeepObjectParam serializes a value using deepObject style.
// DeepObject style is only valid for query parameters with object values and must be exploded.
// Objects: paramName[key1]=value1&paramName[key2]=value2
// Nested: paramName[outer][inner]=value
func StyleDeepObjectParam(paramName string, paramLocation ParamLocation, value any) (string, error) {
	// deepObject always requires explode=true
	return MarshalDeepObject(value, paramName)
}

// MarshalDeepObject marshals an object to deepObject style query parameters.
func MarshalDeepObject(i any, paramName string) (string, error) {
	// Marshal to JSON first to handle all field annotations
	buf, err := json.Marshal(i)
	if err != nil {
		return "", fmt.Errorf("failed to marshal input to JSON: %w", err)
	}
	var i2 any
	err = json.Unmarshal(buf, &i2)
	if err != nil {
		return "", fmt.Errorf("failed to unmarshal JSON: %w", err)
	}
	fields, err := marshalDeepObjectRecursive(i2, nil)
	if err != nil {
		return "", fmt.Errorf("error traversing JSON structure: %w", err)
	}

	// Prefix the param name to each subscripted field
	for idx := range fields {
		fields[idx] = paramName + fields[idx]
	}
	return strings.Join(fields, "&"), nil
}

func marshalDeepObjectRecursive(in any, path []string) ([]string, error) {
	var result []string

	switch t := in.(type) {
	case []any:
		// Arrays use numerical subscripts [0], [1], etc.
		for i, iface := range t {
			newPath := append(path, strconv.Itoa(i))
			fields, err := marshalDeepObjectRecursive(iface, newPath)
			if err != nil {
				return nil, fmt.Errorf("error traversing array: %w", err)
			}
			result = append(result, fields...)
		}
	case map[string]any:
		// Maps use key subscripts [key1], [key2], etc.
		keys := make([]string, 0, len(t))
		for k := range t {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		for _, k := range keys {
			newPath := append(path, k)
			fields, err := marshalDeepObjectRecursive(t[k], newPath)
			if err != nil {
				return nil, fmt.Errorf("error traversing map: %w", err)
			}
			result = append(result, fields...)
		}
	default:
		// Concrete value: turn path into [a][b][c] format
		prefix := "[" + strings.Join(path, "][") + "]"
		result = []string{
			prefix + fmt.Sprintf("=%v", t),
		}
	}
	return result, nil
}

// StyleFormParam serializes a value using form style (RFC 6570) without exploding.
// Form style is the default for query and cookie parameters.
// Primitives: paramName=value
// Arrays: paramName=a,b,c
// Objects: paramName=key1,value1,key2,value2
func StyleFormParam(paramName string, paramLocation ParamLocation, value any) (string, error) {
	t := reflect.TypeOf(value)
	v := reflect.ValueOf(value)

	// Dereference pointers
	if t.Kind() == reflect.Ptr {
		if v.IsNil() {
			return "", fmt.Errorf("value is a nil pointer")
		}
		v = reflect.Indirect(v)
		t = v.Type()
	}

	// Check for TextMarshaler (but not time.Time or Date)
	if tu, ok := value.(encoding.TextMarshaler); ok {
		innerT := reflect.Indirect(reflect.ValueOf(value)).Type()
		if !innerT.ConvertibleTo(reflect.TypeOf(time.Time{})) && !innerT.ConvertibleTo(reflect.TypeOf(Date{})) {
			b, err := tu.MarshalText()
			if err != nil {
				return "", fmt.Errorf("error marshaling '%s' as text: %w", value, err)
			}
			return fmt.Sprintf("%s=%s", paramName, escapeParameterString(string(b), paramLocation)), nil
		}
	}

	switch t.Kind() {
	case reflect.Slice:
		n := v.Len()
		sliceVal := make([]any, n)
		for i := 0; i < n; i++ {
			sliceVal[i] = v.Index(i).Interface()
		}
		return styleFormSlice(paramName, paramLocation, sliceVal)
	case reflect.Struct:
		return styleFormStruct(paramName, paramLocation, value)
	case reflect.Map:
		return styleFormMap(paramName, paramLocation, value)
	default:
		return styleFormPrimitive(paramName, paramLocation, value)
	}
}

func styleFormPrimitive(paramName string, paramLocation ParamLocation, value any) (string, error) {
	strVal, err := primitiveToString(value)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("%s=%s", paramName, escapeParameterString(strVal, paramLocation)), nil
}

func styleFormSlice(paramName string, paramLocation ParamLocation, values []any) (string, error) {
	// Form without explode: paramName=a,b,c
	prefix := fmt.Sprintf("%s=", paramName)
	parts := make([]string, len(values))
	for i, v := range values {
		part, err := primitiveToString(v)
		if err != nil {
			return "", fmt.Errorf("error formatting '%s': %w", paramName, err)
		}
		parts[i] = escapeParameterString(part, paramLocation)
	}
	return prefix + strings.Join(parts, ","), nil
}

func styleFormStruct(paramName string, paramLocation ParamLocation, value any) (string, error) {
	// Check for known types first
	if timeVal, ok := marshalKnownTypes(value); ok {
		return fmt.Sprintf("%s=%s", paramName, escapeParameterString(timeVal, paramLocation)), nil
	}

	// Check for json.Marshaler
	if m, ok := value.(json.Marshaler); ok {
		buf, err := m.MarshalJSON()
		if err != nil {
			return "", fmt.Errorf("failed to marshal to JSON: %w", err)
		}
		var i2 any
		e := json.NewDecoder(bytes.NewReader(buf))
		e.UseNumber()
		if err = e.Decode(&i2); err != nil {
			return "", fmt.Errorf("failed to unmarshal JSON: %w", err)
		}
		return StyleFormParam(paramName, paramLocation, i2)
	}

	// Build field dictionary
	fieldDict, err := structToFieldDict(value)
	if err != nil {
		return "", err
	}

	// Form style without explode: paramName=key1,value1,key2,value2
	prefix := fmt.Sprintf("%s=", paramName)
	var parts []string
	for _, k := range sortedKeys(fieldDict) {
		v := escapeParameterString(fieldDict[k], paramLocation)
		parts = append(parts, k, v)
	}
	return prefix + strings.Join(parts, ","), nil
}

func styleFormMap(paramName string, paramLocation ParamLocation, value any) (string, error) {
	dict, ok := value.(map[string]any)
	if !ok {
		return "", errors.New("map not of type map[string]any")
	}

	fieldDict := make(map[string]string)
	for fieldName, val := range dict {
		str, err := primitiveToString(val)
		if err != nil {
			return "", fmt.Errorf("error formatting '%s': %w", paramName, err)
		}
		fieldDict[fieldName] = str
	}

	// Form style without explode: paramName=key1,value1,key2,value2
	prefix := fmt.Sprintf("%s=", paramName)
	var parts []string
	for _, k := range sortedKeys(fieldDict) {
		v := escapeParameterString(fieldDict[k], paramLocation)
		parts = append(parts, k, v)
	}
	return prefix + strings.Join(parts, ","), nil
}

// StyleFormExplodeParam serializes a value using form style (RFC 6570) with exploding.
// Form style is the default for query and cookie parameters.
// Primitives: paramName=value
// Arrays: paramName=a&paramName=b&paramName=c
// Objects: key1=value1&key2=value2
func StyleFormExplodeParam(paramName string, paramLocation ParamLocation, value any) (string, error) {
	t := reflect.TypeOf(value)
	v := reflect.ValueOf(value)

	// Dereference pointers
	if t.Kind() == reflect.Ptr {
		if v.IsNil() {
			return "", fmt.Errorf("value is a nil pointer")
		}
		v = reflect.Indirect(v)
		t = v.Type()
	}

	// Check for TextMarshaler (but not time.Time or Date)
	if tu, ok := value.(encoding.TextMarshaler); ok {
		innerT := reflect.Indirect(reflect.ValueOf(value)).Type()
		if !innerT.ConvertibleTo(reflect.TypeOf(time.Time{})) && !innerT.ConvertibleTo(reflect.TypeOf(Date{})) {
			b, err := tu.MarshalText()
			if err != nil {
				return "", fmt.Errorf("error marshaling '%s' as text: %w", value, err)
			}
			return fmt.Sprintf("%s=%s", paramName, escapeParameterString(string(b), paramLocation)), nil
		}
	}

	switch t.Kind() {
	case reflect.Slice:
		n := v.Len()
		sliceVal := make([]any, n)
		for i := 0; i < n; i++ {
			sliceVal[i] = v.Index(i).Interface()
		}
		return styleFormExplodeSlice(paramName, paramLocation, sliceVal)
	case reflect.Struct:
		return styleFormExplodeStruct(paramName, paramLocation, value)
	case reflect.Map:
		return styleFormExplodeMap(paramName, paramLocation, value)
	default:
		return styleFormExplodePrimitive(paramName, paramLocation, value)
	}
}

func styleFormExplodePrimitive(paramName string, paramLocation ParamLocation, value any) (string, error) {
	strVal, err := primitiveToString(value)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("%s=%s", paramName, escapeParameterString(strVal, paramLocation)), nil
}

func styleFormExplodeSlice(paramName string, paramLocation ParamLocation, values []any) (string, error) {
	// Form with explode: paramName=a&paramName=b&paramName=c
	prefix := fmt.Sprintf("%s=", paramName)
	parts := make([]string, len(values))
	for i, v := range values {
		part, err := primitiveToString(v)
		if err != nil {
			return "", fmt.Errorf("error formatting '%s': %w", paramName, err)
		}
		parts[i] = escapeParameterString(part, paramLocation)
	}
	return prefix + strings.Join(parts, "&"+prefix), nil
}

func styleFormExplodeStruct(paramName string, paramLocation ParamLocation, value any) (string, error) {
	// Check for known types first
	if timeVal, ok := marshalKnownTypes(value); ok {
		return fmt.Sprintf("%s=%s", paramName, escapeParameterString(timeVal, paramLocation)), nil
	}

	// Check for json.Marshaler
	if m, ok := value.(json.Marshaler); ok {
		buf, err := m.MarshalJSON()
		if err != nil {
			return "", fmt.Errorf("failed to marshal to JSON: %w", err)
		}
		var i2 any
		e := json.NewDecoder(bytes.NewReader(buf))
		e.UseNumber()
		if err = e.Decode(&i2); err != nil {
			return "", fmt.Errorf("failed to unmarshal JSON: %w", err)
		}
		return StyleFormExplodeParam(paramName, paramLocation, i2)
	}

	// Build field dictionary
	fieldDict, err := structToFieldDict(value)
	if err != nil {
		return "", err
	}

	// Form style with explode: key1=value1&key2=value2
	var parts []string
	for _, k := range sortedKeys(fieldDict) {
		v := escapeParameterString(fieldDict[k], paramLocation)
		parts = append(parts, k+"="+v)
	}
	return strings.Join(parts, "&"), nil
}

func styleFormExplodeMap(paramName string, paramLocation ParamLocation, value any) (string, error) {
	dict, ok := value.(map[string]any)
	if !ok {
		return "", errors.New("map not of type map[string]any")
	}

	fieldDict := make(map[string]string)
	for fieldName, val := range dict {
		str, err := primitiveToString(val)
		if err != nil {
			return "", fmt.Errorf("error formatting '%s': %w", paramName, err)
		}
		fieldDict[fieldName] = str
	}

	// Form style with explode: key1=value1&key2=value2
	var parts []string
	for _, k := range sortedKeys(fieldDict) {
		v := escapeParameterString(fieldDict[k], paramLocation)
		parts = append(parts, k+"="+v)
	}
	return strings.Join(parts, "&"), nil
}

// StyleLabelParam serializes a value using label style (RFC 6570) without exploding.
// Label style prefixes values with a dot.
// Primitives: .value
// Arrays: .a,b,c
// Objects: .key1,value1,key2,value2

// Dereference pointers

// Check for TextMarshaler (but not time.Time or Date)

// Label without explode: .a,b,c

// Check for known types first

// Check for json.Marshaler

// Build field dictionary

// Label style without explode: .key1,value1,key2,value2

// Label style without explode: .key1,value1,key2,value2

// StyleLabelExplodeParam serializes a value using label style (RFC 6570) with exploding.
// Label style prefixes values with a dot.
// Primitives: .value
// Arrays: .a.b.c
// Objects: .key1=value1.key2=value2

// Dereference pointers

// Check for TextMarshaler (but not time.Time or Date)

// Label with explode: .a.b.c

// Check for known types first

// Check for json.Marshaler

// Build field dictionary

// Label style with explode: .key1=value1.key2=value2

// Label style with explode: .key1=value1.key2=value2

// StyleMatrixParam serializes a value using matrix style (RFC 6570) without exploding.
// Matrix style prefixes values with ;paramName=.
// Primitives: ;paramName=value
// Arrays: ;paramName=a,b,c
// Objects: ;paramName=key1,value1,key2,value2

// Dereference pointers

// Check for TextMarshaler (but not time.Time or Date)

// Matrix without explode: ;paramName=a,b,c

// Check for known types first

// Check for json.Marshaler

// Build field dictionary

// Matrix style without explode: ;paramName=key1,value1,key2,value2

// Matrix style without explode: ;paramName=key1,value1,key2,value2

// StyleMatrixExplodeParam serializes a value using matrix style (RFC 6570) with exploding.
// Matrix style prefixes values with ;paramName=.
// Primitives: ;paramName=value
// Arrays: ;paramName=a;paramName=b;paramName=c
// Objects: ;key1=value1;key2=value2

// Dereference pointers

// Check for TextMarshaler (but not time.Time or Date)

// Matrix with explode: ;paramName=a;paramName=b;paramName=c

// Check for known types first

// Check for json.Marshaler

// Build field dictionary

// Matrix style with explode: ;key1=value1;key2=value2

// Matrix style with explode: ;key1=value1;key2=value2

// StylePipeDelimitedParam serializes a value using pipeDelimited style without exploding.
// Pipe-delimited style is used for query parameters with array values.
// Arrays: paramName=a|b|c
// Note: Only valid for arrays; objects should use other styles.

// Dereference pointers

// Check for TextMarshaler (but not time.Time or Date)

// For primitives, fall back to form style

// Pipe-delimited without explode: paramName=a|b|c

// StylePipeDelimitedExplodeParam serializes a value using pipeDelimited style with exploding.
// Pipe-delimited style is used for query parameters with array values.
// Arrays: paramName=a&paramName=b&paramName=c (same as form explode)
// Note: Only valid for arrays; objects should use other styles.

// Dereference pointers

// Check for TextMarshaler (but not time.Time or Date)

// For primitives, fall back to form style

// Pipe-delimited with explode: paramName=a&paramName=b&paramName=c

// StyleSimpleParam serializes a value using simple style (RFC 6570) without exploding.
// Simple style is the default for path and header parameters.
// Arrays are comma-separated: a,b,c
// Objects are key,value pairs: key1,value1,key2,value2
func StyleSimpleParam(paramName string, paramLocation ParamLocation, value any) (string, error) {
	t := reflect.TypeOf(value)
	v := reflect.ValueOf(value)

	// Dereference pointers
	if t.Kind() == reflect.Ptr {
		if v.IsNil() {
			return "", fmt.Errorf("value is a nil pointer")
		}
		v = reflect.Indirect(v)
		t = v.Type()
	}

	// Check for TextMarshaler (but not time.Time or Date)
	if tu, ok := value.(encoding.TextMarshaler); ok {
		innerT := reflect.Indirect(reflect.ValueOf(value)).Type()
		if !innerT.ConvertibleTo(reflect.TypeOf(time.Time{})) && !innerT.ConvertibleTo(reflect.TypeOf(Date{})) {
			b, err := tu.MarshalText()
			if err != nil {
				return "", fmt.Errorf("error marshaling '%s' as text: %w", value, err)
			}
			return escapeParameterString(string(b), paramLocation), nil
		}
	}

	switch t.Kind() {
	case reflect.Slice:
		n := v.Len()
		sliceVal := make([]any, n)
		for i := 0; i < n; i++ {
			sliceVal[i] = v.Index(i).Interface()
		}
		return styleSimpleSlice(paramName, paramLocation, sliceVal)
	case reflect.Struct:
		return styleSimpleStruct(paramName, paramLocation, value)
	case reflect.Map:
		return styleSimpleMap(paramName, paramLocation, value)
	default:
		return styleSimplePrimitive(paramLocation, value)
	}
}

func styleSimplePrimitive(paramLocation ParamLocation, value any) (string, error) {
	strVal, err := primitiveToString(value)
	if err != nil {
		return "", err
	}
	return escapeParameterString(strVal, paramLocation), nil
}

func styleSimpleSlice(paramName string, paramLocation ParamLocation, values []any) (string, error) {
	parts := make([]string, len(values))
	for i, v := range values {
		part, err := primitiveToString(v)
		if err != nil {
			return "", fmt.Errorf("error formatting '%s': %w", paramName, err)
		}
		parts[i] = escapeParameterString(part, paramLocation)
	}
	return strings.Join(parts, ","), nil
}

func styleSimpleStruct(paramName string, paramLocation ParamLocation, value any) (string, error) {
	// Check for known types first
	if timeVal, ok := marshalKnownTypes(value); ok {
		return escapeParameterString(timeVal, paramLocation), nil
	}

	// Check for json.Marshaler
	if m, ok := value.(json.Marshaler); ok {
		buf, err := m.MarshalJSON()
		if err != nil {
			return "", fmt.Errorf("failed to marshal to JSON: %w", err)
		}
		var i2 any
		e := json.NewDecoder(bytes.NewReader(buf))
		e.UseNumber()
		if err = e.Decode(&i2); err != nil {
			return "", fmt.Errorf("failed to unmarshal JSON: %w", err)
		}
		return StyleSimpleParam(paramName, paramLocation, i2)
	}

	// Build field dictionary
	fieldDict, err := structToFieldDict(value)
	if err != nil {
		return "", err
	}

	// Simple style without explode: key1,value1,key2,value2
	var parts []string
	for _, k := range sortedKeys(fieldDict) {
		v := escapeParameterString(fieldDict[k], paramLocation)
		parts = append(parts, k, v)
	}
	return strings.Join(parts, ","), nil
}

func styleSimpleMap(paramName string, paramLocation ParamLocation, value any) (string, error) {
	dict, ok := value.(map[string]any)
	if !ok {
		return "", errors.New("map not of type map[string]any")
	}

	fieldDict := make(map[string]string)
	for fieldName, val := range dict {
		str, err := primitiveToString(val)
		if err != nil {
			return "", fmt.Errorf("error formatting '%s': %w", paramName, err)
		}
		fieldDict[fieldName] = str
	}

	// Simple style without explode: key1,value1,key2,value2
	var parts []string
	for _, k := range sortedKeys(fieldDict) {
		v := escapeParameterString(fieldDict[k], paramLocation)
		parts = append(parts, k, v)
	}
	return strings.Join(parts, ","), nil
}

// StyleSimpleExplodeParam serializes a value using simple style (RFC 6570) with exploding.
// Simple style is the default for path and header parameters.
// Arrays are comma-separated: a,b,c (same as non-explode)
// Objects are key=value pairs: key1=value1,key2=value2
func StyleSimpleExplodeParam(paramName string, paramLocation ParamLocation, value any) (string, error) {
	t := reflect.TypeOf(value)
	v := reflect.ValueOf(value)

	// Dereference pointers
	if t.Kind() == reflect.Ptr {
		if v.IsNil() {
			return "", fmt.Errorf("value is a nil pointer")
		}
		v = reflect.Indirect(v)
		t = v.Type()
	}

	// Check for TextMarshaler (but not time.Time or Date)
	if tu, ok := value.(encoding.TextMarshaler); ok {
		innerT := reflect.Indirect(reflect.ValueOf(value)).Type()
		if !innerT.ConvertibleTo(reflect.TypeOf(time.Time{})) && !innerT.ConvertibleTo(reflect.TypeOf(Date{})) {
			b, err := tu.MarshalText()
			if err != nil {
				return "", fmt.Errorf("error marshaling '%s' as text: %w", value, err)
			}
			return escapeParameterString(string(b), paramLocation), nil
		}
	}

	switch t.Kind() {
	case reflect.Slice:
		n := v.Len()
		sliceVal := make([]any, n)
		for i := 0; i < n; i++ {
			sliceVal[i] = v.Index(i).Interface()
		}
		return styleSimpleExplodeSlice(paramName, paramLocation, sliceVal)
	case reflect.Struct:
		return styleSimpleExplodeStruct(paramName, paramLocation, value)
	case reflect.Map:
		return styleSimpleExplodeMap(paramName, paramLocation, value)
	default:
		return styleSimpleExplodePrimitive(paramLocation, value)
	}
}

func styleSimpleExplodePrimitive(paramLocation ParamLocation, value any) (string, error) {
	strVal, err := primitiveToString(value)
	if err != nil {
		return "", err
	}
	return escapeParameterString(strVal, paramLocation), nil
}

func styleSimpleExplodeSlice(paramName string, paramLocation ParamLocation, values []any) (string, error) {
	// Exploded simple array is same as non-exploded: comma-separated
	parts := make([]string, len(values))
	for i, v := range values {
		part, err := primitiveToString(v)
		if err != nil {
			return "", fmt.Errorf("error formatting '%s': %w", paramName, err)
		}
		parts[i] = escapeParameterString(part, paramLocation)
	}
	return strings.Join(parts, ","), nil
}

func styleSimpleExplodeStruct(paramName string, paramLocation ParamLocation, value any) (string, error) {
	// Check for known types first
	if timeVal, ok := marshalKnownTypes(value); ok {
		return escapeParameterString(timeVal, paramLocation), nil
	}

	// Check for json.Marshaler
	if m, ok := value.(json.Marshaler); ok {
		buf, err := m.MarshalJSON()
		if err != nil {
			return "", fmt.Errorf("failed to marshal to JSON: %w", err)
		}
		var i2 any
		e := json.NewDecoder(bytes.NewReader(buf))
		e.UseNumber()
		if err = e.Decode(&i2); err != nil {
			return "", fmt.Errorf("failed to unmarshal JSON: %w", err)
		}
		return StyleSimpleExplodeParam(paramName, paramLocation, i2)
	}

	// Build field dictionary
	fieldDict, err := structToFieldDict(value)
	if err != nil {
		return "", err
	}

	// Simple style with explode: key1=value1,key2=value2
	var parts []string
	for _, k := range sortedKeys(fieldDict) {
		v := escapeParameterString(fieldDict[k], paramLocation)
		parts = append(parts, k+"="+v)
	}
	return strings.Join(parts, ","), nil
}

func styleSimpleExplodeMap(paramName string, paramLocation ParamLocation, value any) (string, error) {
	dict, ok := value.(map[string]any)
	if !ok {
		return "", errors.New("map not of type map[string]any")
	}

	fieldDict := make(map[string]string)
	for fieldName, val := range dict {
		str, err := primitiveToString(val)
		if err != nil {
			return "", fmt.Errorf("error formatting '%s': %w", paramName, err)
		}
		fieldDict[fieldName] = str
	}

	// Simple style with explode: key1=value1,key2=value2
	var parts []string
	for _, k := range sortedKeys(fieldDict) {
		v := escapeParameterString(fieldDict[k], paramLocation)
		parts = append(parts, k+"="+v)
	}
	return strings.Join(parts, ","), nil
}

// StyleSpaceDelimitedParam serializes a value using spaceDelimited style without exploding.
// Space-delimited style is used for query parameters with array values.
// Arrays: paramName=a b c (space-separated)
// Note: Only valid for arrays; objects should use other styles.

// Dereference pointers

// Check for TextMarshaler (but not time.Time or Date)

// For primitives, fall back to form style

// Space-delimited without explode: paramName=a b c (space becomes %20 when encoded)

// StyleSpaceDelimitedExplodeParam serializes a value using spaceDelimited style with exploding.
// Space-delimited style is used for query parameters with array values.
// Arrays: paramName=a&paramName=b&paramName=c (same as form explode)
// Note: Only valid for arrays; objects should use other styles.

// Dereference pointers

// Check for TextMarshaler (but not time.Time or Date)

// For primitives, fall back to form style

// Space-delimited with explode: paramName=a&paramName=b&paramName=c

// JSONMerge merges two JSON-encoded objects. Fields from patch override
// fields in base. Both arguments must be valid JSON objects (or nil/null).

// MarshalForm marshals a struct into url.Values using the struct's json tags
// as field names. It handles nested structs, slices, pointers, and
// AdditionalProperties maps.
