// Code generated by oapi-codegen; DO NOT EDIT.

package output

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"
	"sync"

	oapiCodegenHelpersPkg "github.com/oapi-codegen/oapi-codegen-exp/runtime/helpers"
	oapiCodegenTypesPkg "github.com/oapi-codegen/oapi-codegen-exp/runtime/types"
)

// #/components/schemas/OptionalClaims
type OptionalClaims struct {
	IDToken     *string `form:"idToken,omitempty" json:"idToken,omitempty"`
	AccessToken *string `form:"accessToken,omitempty" json:"accessToken,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *OptionalClaims) ApplyDefaults() {
}

// #/components/schemas/Application
type Application struct {
	Name *string `form:"name,omitempty" json:"name,omitempty"`
	// Optional claims configuration
	OptionalClaims oapiCodegenTypesPkg.Nullable[ApplicationOptionalClaims] `form:"optionalClaims,omitempty" json:"optionalClaims,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Application) ApplyDefaults() {
}

// #/components/schemas/Application/properties/optionalClaims

// Optional claims configuration
type ApplicationOptionalClaims struct {
	union json.RawMessage
}

// AsOptionalClaims returns the union data inside the ApplicationOptionalClaims as a OptionalClaims.
func (t ApplicationOptionalClaims) AsOptionalClaims() (OptionalClaims, error) {
	var body OptionalClaims
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOptionalClaims overwrites any union data inside the ApplicationOptionalClaims as the provided OptionalClaims.
func (t *ApplicationOptionalClaims) FromOptionalClaims(v OptionalClaims) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOptionalClaims performs a merge with any union data inside the ApplicationOptionalClaims, using the provided OptionalClaims.
func (t *ApplicationOptionalClaims) MergeOptionalClaims(v OptionalClaims) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ApplicationOptionalClaims) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ApplicationOptionalClaims) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *ApplicationOptionalClaims) ApplyDefaults() {
}

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/5RRvYocPRDM9RQF88Eldzv7nblEmXHkaJMDx1pNz6htTbeQemwW43c3M7feHzAczqRS",
	"laq6usPn1hbCy/7ZI8jpMPYh58OIH2wJKvkEFUKlEXYqhImEajBqK9l1SGal+b6f2NJy3EWdew2Fn6IO",
	"NJHcX3i1av3L/tl1rsOXRPLmCa14s02h3blSJYn0CDa0pEseLglcB0s3nGEL+AhRWz/dOS0kobDHh91+",
	"t3cso3oHGFsmfx0br9TMAd+pNlbx+H+jl2Cpefz85aLORYXE2ipvMdEctiNwKMYqIX/Kgeczhi2Hhx6/",
	"UrQzVKoWqsZ0IQE8vOo3kivwR9msskwXOMRIrb3P/VhK5hjWRP+YRMJM78bQv866BVxXeAsAT/iv0ujx",
	"0PXX+vpzd/19bQ83yoFarLw9+0u7iBsPUWXkaanbiDciWXIOx3WpVhdyvwMAAP//35X1R9MCAAA=",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}
