// Code generated by oapi-codegen; DO NOT EDIT.

package output

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"
	"sync"
)

// #/components/schemas/WithAnyAdditional1
type WithAnyAdditional1 struct {
	Field1               *int           `form:"field1,omitempty" json:"field1,omitempty"`
	Field2               *string        `form:"field2,omitempty" json:"field2,omitempty"`
	AdditionalProperties map[string]any `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a WithAnyAdditional1) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *WithAnyAdditional1) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *WithAnyAdditional1) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["field1"]; found {
		var val int
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'field1': %w", err)
		}
		a.Field1 = &val
		delete(object, "field1")
	}

	if raw, found := object["field2"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'field2': %w", err)
		}
		a.Field2 = &val
		delete(object, "field2")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a WithAnyAdditional1) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Field1 != nil {
		object["field1"], err = json.Marshal(a.Field1)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'field1': %w", err)
		}
	}

	if a.Field2 != nil {
		object["field2"], err = json.Marshal(a.Field2)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'field2': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *WithAnyAdditional1) ApplyDefaults() {
}

// #/components/schemas/WithAnyAdditional2
type WithAnyAdditional2 struct {
	FieldA               *int           `form:"fieldA,omitempty" json:"fieldA,omitempty"`
	FieldB               *string        `form:"fieldB,omitempty" json:"fieldB,omitempty"`
	AdditionalProperties map[string]any `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a WithAnyAdditional2) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *WithAnyAdditional2) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *WithAnyAdditional2) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["fieldA"]; found {
		var val int
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'fieldA': %w", err)
		}
		a.FieldA = &val
		delete(object, "fieldA")
	}

	if raw, found := object["fieldB"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'fieldB': %w", err)
		}
		a.FieldB = &val
		delete(object, "fieldB")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a WithAnyAdditional2) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.FieldA != nil {
		object["fieldA"], err = json.Marshal(a.FieldA)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fieldA': %w", err)
		}
	}

	if a.FieldB != nil {
		object["fieldB"], err = json.Marshal(a.FieldB)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fieldB': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *WithAnyAdditional2) ApplyDefaults() {
}

// #/components/schemas/WithStringAdditional1
type WithStringAdditional1 struct {
	Field1               *int              `form:"field1,omitempty" json:"field1,omitempty"`
	Field2               *string           `form:"field2,omitempty" json:"field2,omitempty"`
	AdditionalProperties map[string]string `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a WithStringAdditional1) Get(fieldName string) (value string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *WithStringAdditional1) Set(fieldName string, value string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]string)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *WithStringAdditional1) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["field1"]; found {
		var val int
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'field1': %w", err)
		}
		a.Field1 = &val
		delete(object, "field1")
	}

	if raw, found := object["field2"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'field2': %w", err)
		}
		a.Field2 = &val
		delete(object, "field2")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]string)
		for fieldName, fieldBuf := range object {
			var fieldVal string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a WithStringAdditional1) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Field1 != nil {
		object["field1"], err = json.Marshal(a.Field1)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'field1': %w", err)
		}
	}

	if a.Field2 != nil {
		object["field2"], err = json.Marshal(a.Field2)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'field2': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *WithStringAdditional1) ApplyDefaults() {
}

// #/components/schemas/WithStringAdditional2
type WithStringAdditional2 struct {
	FieldA               *int              `form:"fieldA,omitempty" json:"fieldA,omitempty"`
	FieldB               *string           `form:"fieldB,omitempty" json:"fieldB,omitempty"`
	AdditionalProperties map[string]string `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a WithStringAdditional2) Get(fieldName string) (value string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *WithStringAdditional2) Set(fieldName string, value string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]string)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *WithStringAdditional2) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["fieldA"]; found {
		var val int
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'fieldA': %w", err)
		}
		a.FieldA = &val
		delete(object, "fieldA")
	}

	if raw, found := object["fieldB"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'fieldB': %w", err)
		}
		a.FieldB = &val
		delete(object, "fieldB")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]string)
		for fieldName, fieldBuf := range object {
			var fieldVal string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a WithStringAdditional2) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.FieldA != nil {
		object["fieldA"], err = json.Marshal(a.FieldA)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fieldA': %w", err)
		}
	}

	if a.FieldB != nil {
		object["fieldB"], err = json.Marshal(a.FieldB)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fieldB': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *WithStringAdditional2) ApplyDefaults() {
}

// #/components/schemas/WithoutAdditional1
type WithoutAdditional1 struct {
	Field1               *int           `form:"field1,omitempty" json:"field1,omitempty"`
	Field2               *string        `form:"field2,omitempty" json:"field2,omitempty"`
	AdditionalProperties map[string]any `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a WithoutAdditional1) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *WithoutAdditional1) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *WithoutAdditional1) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["field1"]; found {
		var val int
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'field1': %w", err)
		}
		a.Field1 = &val
		delete(object, "field1")
	}

	if raw, found := object["field2"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'field2': %w", err)
		}
		a.Field2 = &val
		delete(object, "field2")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a WithoutAdditional1) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Field1 != nil {
		object["field1"], err = json.Marshal(a.Field1)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'field1': %w", err)
		}
	}

	if a.Field2 != nil {
		object["field2"], err = json.Marshal(a.Field2)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'field2': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *WithoutAdditional1) ApplyDefaults() {
}

// #/components/schemas/WithoutAdditional2
type WithoutAdditional2 struct {
	FieldA               *int           `form:"fieldA,omitempty" json:"fieldA,omitempty"`
	FieldB               *string        `form:"fieldB,omitempty" json:"fieldB,omitempty"`
	AdditionalProperties map[string]any `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a WithoutAdditional2) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *WithoutAdditional2) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *WithoutAdditional2) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["fieldA"]; found {
		var val int
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'fieldA': %w", err)
		}
		a.FieldA = &val
		delete(object, "fieldA")
	}

	if raw, found := object["fieldB"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'fieldB': %w", err)
		}
		a.FieldB = &val
		delete(object, "fieldB")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a WithoutAdditional2) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.FieldA != nil {
		object["fieldA"], err = json.Marshal(a.FieldA)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fieldA': %w", err)
		}
	}

	if a.FieldB != nil {
		object["fieldB"], err = json.Marshal(a.FieldB)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fieldB': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *WithoutAdditional2) ApplyDefaults() {
}

// #/components/schemas/DefaultAdditional1
type DefaultAdditional1 struct {
	Field1 *int    `form:"field1,omitempty" json:"field1,omitempty"`
	Field2 *string `form:"field2,omitempty" json:"field2,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *DefaultAdditional1) ApplyDefaults() {
}

// #/components/schemas/DefaultAdditional2
type DefaultAdditional2 struct {
	FieldA *int    `form:"fieldA,omitempty" json:"fieldA,omitempty"`
	FieldB *string `form:"fieldB,omitempty" json:"fieldB,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *DefaultAdditional2) ApplyDefaults() {
}

// #/components/schemas/MergeWithoutWithout
type MergeWithoutWithout struct {
	Field1 *int    `form:"field1,omitempty" json:"field1,omitempty"`
	Field2 *string `form:"field2,omitempty" json:"field2,omitempty"`
	FieldA *int    `form:"fieldA,omitempty" json:"fieldA,omitempty"`
	FieldB *string `form:"fieldB,omitempty" json:"fieldB,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *MergeWithoutWithout) ApplyDefaults() {
}

// #/components/schemas/MergeWithoutWithString
type MergeWithoutWithString struct {
	Field1 *int    `form:"field1,omitempty" json:"field1,omitempty"`
	Field2 *string `form:"field2,omitempty" json:"field2,omitempty"`
	FieldA *int    `form:"fieldA,omitempty" json:"fieldA,omitempty"`
	FieldB *string `form:"fieldB,omitempty" json:"fieldB,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *MergeWithoutWithString) ApplyDefaults() {
}

// #/components/schemas/MergeWithoutWithAny
type MergeWithoutWithAny struct {
	Field1 *int    `form:"field1,omitempty" json:"field1,omitempty"`
	Field2 *string `form:"field2,omitempty" json:"field2,omitempty"`
	FieldA *int    `form:"fieldA,omitempty" json:"fieldA,omitempty"`
	FieldB *string `form:"fieldB,omitempty" json:"fieldB,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *MergeWithoutWithAny) ApplyDefaults() {
}

// #/components/schemas/MergeWithoutDefault
type MergeWithoutDefault struct {
	Field1 *int    `form:"field1,omitempty" json:"field1,omitempty"`
	Field2 *string `form:"field2,omitempty" json:"field2,omitempty"`
	FieldA *int    `form:"fieldA,omitempty" json:"fieldA,omitempty"`
	FieldB *string `form:"fieldB,omitempty" json:"fieldB,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *MergeWithoutDefault) ApplyDefaults() {
}

// #/components/schemas/MergeWithStringWithout
type MergeWithStringWithout struct {
	Field1 *int    `form:"field1,omitempty" json:"field1,omitempty"`
	Field2 *string `form:"field2,omitempty" json:"field2,omitempty"`
	FieldA *int    `form:"fieldA,omitempty" json:"fieldA,omitempty"`
	FieldB *string `form:"fieldB,omitempty" json:"fieldB,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *MergeWithStringWithout) ApplyDefaults() {
}

// #/components/schemas/MergeWithStringWithAny
type MergeWithStringWithAny struct {
	Field1 *int    `form:"field1,omitempty" json:"field1,omitempty"`
	Field2 *string `form:"field2,omitempty" json:"field2,omitempty"`
	FieldA *int    `form:"fieldA,omitempty" json:"fieldA,omitempty"`
	FieldB *string `form:"fieldB,omitempty" json:"fieldB,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *MergeWithStringWithAny) ApplyDefaults() {
}

// #/components/schemas/MergeWithStringDefault
type MergeWithStringDefault struct {
	Field1 *int    `form:"field1,omitempty" json:"field1,omitempty"`
	Field2 *string `form:"field2,omitempty" json:"field2,omitempty"`
	FieldA *int    `form:"fieldA,omitempty" json:"fieldA,omitempty"`
	FieldB *string `form:"fieldB,omitempty" json:"fieldB,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *MergeWithStringDefault) ApplyDefaults() {
}

// #/components/schemas/MergeWithAnyWithout
type MergeWithAnyWithout struct {
	Field1 *int    `form:"field1,omitempty" json:"field1,omitempty"`
	Field2 *string `form:"field2,omitempty" json:"field2,omitempty"`
	FieldA *int    `form:"fieldA,omitempty" json:"fieldA,omitempty"`
	FieldB *string `form:"fieldB,omitempty" json:"fieldB,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *MergeWithAnyWithout) ApplyDefaults() {
}

// #/components/schemas/MergeWithAnyWithString
type MergeWithAnyWithString struct {
	Field1 *int    `form:"field1,omitempty" json:"field1,omitempty"`
	Field2 *string `form:"field2,omitempty" json:"field2,omitempty"`
	FieldA *int    `form:"fieldA,omitempty" json:"fieldA,omitempty"`
	FieldB *string `form:"fieldB,omitempty" json:"fieldB,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *MergeWithAnyWithString) ApplyDefaults() {
}

// #/components/schemas/MergeWithAnyWithAny
type MergeWithAnyWithAny struct {
	Field1 *int    `form:"field1,omitempty" json:"field1,omitempty"`
	Field2 *string `form:"field2,omitempty" json:"field2,omitempty"`
	FieldA *int    `form:"fieldA,omitempty" json:"fieldA,omitempty"`
	FieldB *string `form:"fieldB,omitempty" json:"fieldB,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *MergeWithAnyWithAny) ApplyDefaults() {
}

// #/components/schemas/MergeWithAnyDefault
type MergeWithAnyDefault struct {
	Field1 *int    `form:"field1,omitempty" json:"field1,omitempty"`
	Field2 *string `form:"field2,omitempty" json:"field2,omitempty"`
	FieldA *int    `form:"fieldA,omitempty" json:"fieldA,omitempty"`
	FieldB *string `form:"fieldB,omitempty" json:"fieldB,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *MergeWithAnyDefault) ApplyDefaults() {
}

// #/components/schemas/MergeDefaultWithout
type MergeDefaultWithout struct {
	Field1 *int    `form:"field1,omitempty" json:"field1,omitempty"`
	Field2 *string `form:"field2,omitempty" json:"field2,omitempty"`
	FieldA *int    `form:"fieldA,omitempty" json:"fieldA,omitempty"`
	FieldB *string `form:"fieldB,omitempty" json:"fieldB,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *MergeDefaultWithout) ApplyDefaults() {
}

// #/components/schemas/MergeDefaultWithString
type MergeDefaultWithString struct {
	Field1 *int    `form:"field1,omitempty" json:"field1,omitempty"`
	Field2 *string `form:"field2,omitempty" json:"field2,omitempty"`
	FieldA *int    `form:"fieldA,omitempty" json:"fieldA,omitempty"`
	FieldB *string `form:"fieldB,omitempty" json:"fieldB,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *MergeDefaultWithString) ApplyDefaults() {
}

// #/components/schemas/MergeDefaultWithAny
type MergeDefaultWithAny struct {
	Field1 *int    `form:"field1,omitempty" json:"field1,omitempty"`
	Field2 *string `form:"field2,omitempty" json:"field2,omitempty"`
	FieldA *int    `form:"fieldA,omitempty" json:"fieldA,omitempty"`
	FieldB *string `form:"fieldB,omitempty" json:"fieldB,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *MergeDefaultWithAny) ApplyDefaults() {
}

// #/components/schemas/MergeDefaultDefault
type MergeDefaultDefault struct {
	Field1 *int    `form:"field1,omitempty" json:"field1,omitempty"`
	Field2 *string `form:"field2,omitempty" json:"field2,omitempty"`
	FieldA *int    `form:"fieldA,omitempty" json:"fieldA,omitempty"`
	FieldB *string `form:"fieldB,omitempty" json:"fieldB,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *MergeDefaultDefault) ApplyDefaults() {
}

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/8yWwVLCMBBA73zFDnWmJ0Hw1lvVq6MzHjxH2EKcknTS5dC/d6TBUBOKk2VsT8Cym75u",
	"XzfRFSpRyQym97O72WI6WeldpRUqqrMJQL3a4k4cvgK8S9rmqsnXa0lSK1Eu2jgANRVmoD8+cUU2VBld",
	"oSGJ9TEJoJBYrhfu97FQKsINmm7e0s+ryUi1sWHxg/HqLgVk9hiGXcbA5n+EfeDDvh3yx9zcydmCEP/4",
	"+t3Pr/c0arMLUdYYph2h2o72CQuxL8fRW49loM4d4s9oNmifpf04FoiyfClc9S3cGCwySJO5G89zO5vn",
	"vrxpbOUyDZK1r/YAcN5MCfPlqhkArru7+GRWtn8m8xVPf+nWNpVrnLddcaVL4FEopQl236BAW1nbeID8",
	"1Miki5/wbiC5kpqOlWMnq8u9grYrcx2N5rusaa4arqPdw+rVpqIlY07FeLhL6lk+jnfxcL3S5arhGhdH",
	"1q+b/Zejm3/KuYpuJ2QM3Xhwfbqd8MXqxoM7q5tdlqNbPFlIt68AAAD//xNnWtZqDwAA",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}
