// Code generated by oapi-codegen; DO NOT EDIT.

package output

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"strings"
	"sync"
)

// #/components/schemas/Object
type Object struct {
	Role      string `form:"role" json:"role"`
	FirstName string `form:"firstName" json:"firstName"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Object) ApplyDefaults() {
}

// #/components/schemas/ComplexObject
type ComplexObject struct {
	Object  Object `form:"Object" json:"Object"`
	ID      int    `form:"Id" json:"Id"`
	IsAdmin bool   `form:"IsAdmin" json:"IsAdmin"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ComplexObject) ApplyDefaults() {
}

// #/paths//enums/get/parameters/0/schema
type GetEnumsParameter int

const (
	N100 GetEnumsParameter = 100
	N200 GetEnumsParameter = 200
)

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/+RaX2/cNgx/96cQsgEFgt3ZSffkt6DbsABrdlsDtMCwB8XmxepsSZXkLEGx7z7Ysu/k",
	"f7HsRHdukqeeTErkjyJ/NF3GgWJOQnTydh2sz048Qrcs9BC6AyEJoyE6WwfrwENIEZVCiK5BKvQBxB0I",
	"D6GUREAlFAoIUZxBiN5fXnuyfC6L5RXKRRqiRCke+n51nAKp1jEAzzBfY+JxrJJS2pck4ylsBMmIInfg",
	"f+VY4Ow/fcAtKP0PhBgHgRVh9DIOi/UPTb1KqlQGVZmi/1aVneWz3SpChBZrKjGWBHzJiYA4RErkYDyQ",
	"6qHAQhtrrkcJZDg0VhBSDxxCRKiC2xKy/d+WiQyr8tnbc68+UnJGJRgGvzkPgjfmnt8L2Ibo5Ds/Yhln",
	"FKiS/k7P10j8Wf0+2YN6xX6+5ymL4UII/DAR2abykeAFbUKItjiVdrhjw9zKEAWZbIo+FqSDh6knSKe2",
	"UVpSjNryLyhEu2T4/eYzRGpuKmntbyGX+nDSctLXXpwcLDEamE/NjGVAbpEaR0Y8xTeQtgljbXnNf+sq",
	"Hwbx0urXwxelu30hOrWM0YIi9CLZoplFdeGal0aHrFxPyqMlVK5exCdmxSIAXz5TZFgJct+hChKPo/2+",
	"R9UCbxI/DWxt8euhCe1vJz6ntgFaTHheJEe08mdXsmYkkHXFOm4GLaJgdeGemg8LQHv57BAxqoCqie/J",
	"70wtxwxcWdhEDXOekqg0yf8sGW1Xjj6kx9B+xwp07g8AOsdSXieC5beJNeSbvc4xAFdwr3yeYmINtS7e",
	"UglCb53OHhQWitDbj0QlV3l2A8L/emY77+noWmB79orA/ZKDePiFiWwUyj9qSQsEARs2xSAjQbgqv2VU",
	"lTPudAgFxqUxvSB3WE0X5u3enEX1KXskBoFw6v/R22jjKrDRq8BMlpmOhRsy3nsw6MBz2f28LZsBPR+F",
	"nrc+17lFf9qHOIPshvx4RvPtU2aG/XLUgWapn1EQBs1tbVzbFA1e60i3SU+93sdt6ww2HwS/eI7q7gL9",
	"S1SCqNkjOIuCOyb/CYBrIEb5fC9qQeixFh5Csng89b70v2rFbaues8LbvgDEsMV5qp4UjgRwDGI0Cr+W",
	"YhYR+LTa9BQ7q2qYmGcsoBwarqyqV/n4ED45ZKhPq3I4N+rOo+2vU5+cN3oVBFP6XbcX8wAe60piH/Xe",
	"Euko7HM6xtqjSR2vqyjOc6Cq8SOOPNrjTHBoMU3Oqp50rD4Slayu2n3MrMZnAhDzO58nk62ecrJ/CFiM",
	"NQsxm/HaVD6KzJ0XwLFwEA8cMurMEZJTL5Y1LXJ75RY7GHIUYfeTIVfxmmP5zLf/CS68nNf/CU4fkQUR",
	"8oHmdYIOcWAhsil4T9pM8UthlWxan0MaKG7qDTSChQ66w2kO0sEUxZ5GyiyieRaiv9BZEPyAzoMA/T2M",
	"/3nwYzh4UVh9m719KArp6gpqRXPsghAXBe6KmGcIloJ5SO98bkuEVFcF/t7IHargM8JWHGD83G1VrjXy",
	"5DEzmxJTK8xl3DW8HbZLeRFnzW9hWvCGsRQwfcTFVlu/Qpex+UNv7HVC3MyWesNGlC+q/y68U22WwE49",
	"6/+mN1oB/g8AAP//iGcBzu8zAAA=",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}

// MarshalText implements encoding.TextMarshaler for Date.

// Format returns the date formatted according to layout.

// ErrValidationEmail is the sentinel error returned when an email fails validation

// Email represents an email address.
// It is a string type that must pass regex validation before being marshalled
// to JSON or unmarshalled from JSON.

// Nullable is a generic type that can distinguish between:
// - Field not provided (unspecified)
// - Field explicitly set to null
// - Field has a value
//
// This is implemented as a map[bool]T where:
// - Empty map: unspecified
// - map[false]T: explicitly null
// - map[true]T: has a value

// NewNullableWithValue creates a Nullable with the given value.

// NewNullNullable creates a Nullable that is explicitly null.

// Get returns the value if set, or an error if null or unspecified.

// MustGet returns the value or panics if null or unspecified.

// Set assigns a value.

// SetNull marks the field as explicitly null.

// SetUnspecified clears the field (as if it was never set).

// IsNull returns true if the field is explicitly null.

// IsSpecified returns true if the field was provided (either null or a value).

// MarshalJSON implements json.Marshaler.

// Unspecified - this shouldn't be called if omitempty is used correctly

// UnmarshalJSON implements json.Unmarshaler.

// ErrNullableIsNull is returned when trying to get a value from a null Nullable.

// ErrNullableNotSpecified is returned when trying to get a value from an unspecified Nullable.

// BindParameter binds a styled parameter from a single string value to a Go
// object. This is the entry point for path, header, and cookie parameters
// where the HTTP framework has already extracted the raw value.
//
// The Style field in opts selects how the value is split into parts (simple,
// label, matrix, form). If Style is empty, "simple" is assumed.

// Unescape based on parameter location.

// If the destination implements encoding.TextUnmarshaler, use it directly.

// Primitive types need style-specific prefix stripping before binding.
// Label and matrix use splitStyledParameter for their prefix formats.
// Form style adds a "name=" prefix (e.g. "p=5") which is meaningful in
// query strings but must be stripped for cookie/header values. We use
// TrimPrefix instead of splitStyledParameter to avoid splitting on commas,
// which would break string primitives containing literal commas.

// BindQueryParameter binds a query parameter from pre-parsed url.Values.
// The Style field in opts selects parsing behavior. If Style is empty, "form"
// is assumed. Supports form, spaceDelimited, pipeDelimited, and deepObject.

// Destination value management for optional (pointer) parameters.

// Exploded: each value is a separate key=value pair.
// spaceDelimited and pipeDelimited with explode=true are
// serialized identically to form explode=true.

// Non-exploded: single value, delimiter-separated.

// Primitive types: use the raw value as-is without splitting.

// Some struct types (e.g. Date, time.Time) are scalar values
// that should be bound from a single string, not decomposed as
// key-value objects.

// BindRawQueryParameter works like BindQueryParameter but operates on the raw
// (undecoded) query string. This correctly handles form/explode=false
// parameters whose values contain literal commas encoded as %2C — something
// that BindQueryParameter cannot do because url.Values has already decoded
// %2C to ',' before we can split on the delimiter comma.

// For explode, url.ParseQuery is fine — no delimiter commas to
// confuse with literal commas.

// explode=false — use findRawQueryParam to get the still-encoded
// value, split on the style-specific delimiter, then URL-decode
// each resulting part individually.

// Primitive types: decode as-is without splitting.

// ---------------------------------------------------------------------------
// Deep object internals
// ---------------------------------------------------------------------------

// unmarshalDeepObject is the internal implementation of deep object
// unmarshaling that supports the required parameter.

// UnmarshalDeepObject unmarshals deepObject-style query parameters to a
// destination. Exported for use by generated code and tests.

// ---------------------------------------------------------------------------
// Exploded object binding
// ---------------------------------------------------------------------------

// bindParamsToExplodedObject reflects the destination structure and pulls the
// value for each settable field from the given query parameters. Returns
// whether any fields were bound.

// indirectBinder checks if dest implements Binder and returns reflect values.

// ParamLocation indicates where a parameter is located in an HTTP request.

// Binder is an interface for types that can bind themselves from a string value.

// MissingRequiredParameterError is returned when a required parameter is not
// present in the request. Upper layers can use errors.As to detect this and
// produce an appropriate HTTP error response.

// primitiveToString converts a primitive value to a string representation.
// It handles basic Go types, time.Time, Date, and types that implement
// json.Marshaler or fmt.Stringer.

// Check for known types first (time, date, uuid)

// Dereference pointers for optional values

// Check if it's a UUID

// Check if it implements json.Marshaler

// marshalKnownTypes checks for special types (time.Time, Date, UUID) and marshals them.

// escapeParameterName escapes a parameter name for use in query strings and
// paths. This ensures characters like [] in parameter names (e.g. user_ids[])
// are properly percent-encoded per RFC 3986.

// Parameter names should always be encoded regardless of allowReserved,
// which only applies to values per the OpenAPI spec.

// escapeParameterString escapes a parameter value based on its location.
// Query and path parameters need URL escaping; headers and cookies do not.
// When allowReserved is true and the location is query, RFC 3986 reserved
// characters are left unencoded per the OpenAPI allowReserved specification.

// escapeQueryAllowReserved percent-encodes a query parameter value while
// leaving RFC 3986 reserved characters (:/?#[]@!$&'()*+,;=) unencoded, as
// specified by OpenAPI's allowReserved parameter option.

// isUnreserved reports whether the byte is an RFC 3986 unreserved character:
// ALPHA / DIGIT / "-" / "." / "_" / "~"

// unescapeParameterString unescapes a parameter value based on its location.

// sortedKeys returns the keys of a map in sorted order.

// BindStringToObject binds a string value to a destination object.
// It handles primitives, encoding.TextUnmarshaler, and the Binder interface.

// Check for TextUnmarshaler

// Check for Binder interface

// Try JSON unmarshal as a fallback

// bindSplitPartsToDestinationArray binds a slice of string parts to a destination slice.

// bindSplitPartsToDestinationStruct binds string parts to a destination struct via JSON.

// splitStyledParameter splits a styled parameter string value into parts based
// on the OpenAPI style. The object flag indicates whether the destination is a
// struct/map (affects matrix explode handling).

// In the simple case, we always split on comma

// Exploded: .a.b.c or .key=value.key=value

// Unexploded: .a,b,c

// Exploded: ;a;b;c or ;key=value;key=value

// Unexploded: ;paramName=a,b,c

// findRawQueryParam extracts values for a named parameter from a raw
// (undecoded) query string. The parameter key is decoded for comparison
// purposes, but the returned values remain in their original encoded form.

// Skip malformed keys.

// isByteSlice reports whether t is []byte (or equivalently []uint8).

// base64Decode decodes s as base64.
//
// Per OpenAPI 3.0, format: byte uses RFC 4648 Section 4 (standard alphabet,
// padded). We use padding presence to select the right decoder, rather than
// blindly cascading (which can produce corrupt output when RawStdEncoding
// silently accepts padded input and treats '=' as data).

// structToFieldDict converts a struct to a map of field names to string values.

// Skip nil optional fields

// ParameterOptions carries OpenAPI parameter metadata to bind and style
// functions so they can handle style dispatch, explode, required,
// type-aware coercions, and location-aware escaping from a single
// uniform call site. All fields have sensible zero-value defaults.

// OpenAPI style: "simple", "form", "label", "matrix", "deepObject", "pipeDelimited", "spaceDelimited"
// Where the parameter appears: query, path, header, cookie

// OpenAPI type: "string", "integer", "array", "object"
// OpenAPI format: "int32", "date-time", etc.
// When true, reserved characters in query values are not percent-encoded

// StyleParameter serializes a Go value into an OpenAPI-styled parameter string.
// This is the entry point for client-side parameter serialization. The Style
// field in opts selects the serialization format. If Style is empty, "simple"
// is assumed.

// Dereference pointers; error on nil.

// If the value implements encoding.TextMarshaler, use it — but not for
// time.Time or Date which have their own formatting logic.

// ---------------------------------------------------------------------------
// Internal style helpers
// ---------------------------------------------------------------------------

// If input implements json.Marshaler (e.g. objects with additional properties
// or anyOf), marshal to JSON and re-style the generic structure.

// Build a dictionary of the struct's fields.

// Skip nil optional fields.

// ---------------------------------------------------------------------------
// Deep object marshaling
// ---------------------------------------------------------------------------

// MarshalDeepObject marshals an object to deepObject style query parameters.

// JSONMerge merges two JSON-encoded objects. Fields from patch override
// fields in base. Both arguments must be valid JSON objects (or nil/null).

// MarshalForm marshals a struct into url.Values using the struct's json tags
// as field names. It handles nested structs, slices, pointers, and
// AdditionalProperties maps.
