// Code generated by oapi-codegen; DO NOT EDIT.

package treefarm

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"sync"

	"github.com/google/uuid"
)

// #/components/schemas/Tree
// A tree to be planted
type Tree struct {
	// Where to plant the tree (e.g. "north meadow")
	Location string `form:"location" json:"location"`
	// What kind of tree to plant (e.g. "oak")
	Kind string `form:"kind" json:"kind"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Tree) ApplyDefaults() {
}

// #/components/schemas/TreePlantingRequest
// A tree planting request, combining the tree details with a callback URL
// for completion notification.
type TreePlantingRequest struct {
	// Where to plant the tree (e.g. "north meadow")
	Location string `form:"location" json:"location"`
	// What kind of tree to plant (e.g. "oak")
	Kind string `form:"kind" json:"kind"`
	// URL to receive the planting result callback
	CallbackURL string `form:"callbackUrl" json:"callbackUrl"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *TreePlantingRequest) ApplyDefaults() {
}

// #/components/schemas/TreeWithId
// A tree with a server-assigned identifier
type TreeWithID struct {
	// Where to plant the tree (e.g. "north meadow")
	Location string `form:"location" json:"location"`
	// What kind of tree to plant (e.g. "oak")
	Kind string `form:"kind" json:"kind"`
	// Unique identifier for this planting request
	ID UUID `form:"id" json:"id"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *TreeWithID) ApplyDefaults() {
}

// #/components/schemas/TreePlantingResult
// The result of a tree planting operation, sent via callback
type TreePlantingResult struct {
	// Where to plant the tree (e.g. "north meadow")
	Location string `form:"location" json:"location"`
	// What kind of tree to plant (e.g. "oak")
	Kind string `form:"kind" json:"kind"`
	// Unique identifier for this planting request
	ID UUID `form:"id" json:"id"`
	// Whether the tree was successfully planted
	Success bool `form:"success" json:"success"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *TreePlantingResult) ApplyDefaults() {
}

// #/components/schemas/Error
type Error struct {
	// Error code
	Code int32 `form:"code" json:"code"`
	// Error message
	Message string `form:"message" json:"message"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Error) ApplyDefaults() {
}

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/8RXwW7bOBC96ysGaQG3QCO76U23bJEFAhSbIHGQ44IWxxYbilTJUbzG7gL7EfuF+yUL",
	"khJFy4rr9NKcopDzZvhm5s1EN6hYIwo4+5R/zBdnmVBrXWQAz2is0KqAj/kiX2QAJEhiAUuDCL8yU2cA",
	"HG1pREP+3l8ZAMAlkLvQSKZIqA1YNM+iRKCKEXCstbJkGKGFmwbV5e01lEzKFSufbO4BlhVCKQUqAtuu",
	"akEW2AjT4LcWLQGTWm1gK6gCFmHg4e5LQHqsUAFVGKwrZmGFqAIM8g/+yIWHBiwq7vzc3twvgbQ/SgE9",
	"HmlQmsR6F45DjHrtvwzaVpLzK0WJymLhTRSrsYDLhpUVwoWnEaA1soCKqLHFfL7dbnPmz3NtNvPO2s6/",
	"XH+++u3+6vwiX+QV1TJrGFXWoc5ZI+b+Eb+7hwVHjbYUfgOwbV0zsyvgrudpn7/u2kTy3M99JL2nmXQw",
	"7XEYBeoaLMVaIAepS+Zg8giyrIQF4UBcis5Nq5RLnG7Q+Jvw3z//pvyzssSGbEeldxuxmOIgGaEJ7Au0",
	"MT1o4Fkw/9kY/Sw48ok6gMHvNS/g1r3FVXF32Pn7RfNdEZ2+NbguYPZmXuq60QoV2flwUaCdO4TbjtFZ",
	"hLKNdukbgGYXi4vZ8DmifTld154N5IlVqRWhohQIgDWNFIH6+Ver1f4pgC0rrNn4r9OPC3fDsx4FVdd8",
	"lg0hr1kr6cVXtAr/aLAk5IDGaPMz4r5yjvuQo6QMGNSnC3kKPPvzbcd6vtJ892bemz4Y+fdsP4S0x2Ko",
	"fa+NM+nkoCvY8NKR4QvdF7vQactql/bIhCzBdk/iRg0+/Ax955iT6OT3nW3LEq1dt1LuQPvuep9nLxi6",
	"xlkOFI6uTbZQeigM8gLItHhwPFkhp9XJ8Wo5rdb7Fr7zGZsdPOygoZPGXsymvO5l9nOfLYMlimfkkNKe",
	"HdoedNprO+4EXk9l9nvcntSRw4mD6Q4D4jKOLwDaNViAXn3FkqYGVLdXkIYV9iM8GxVYDPM8jqTkT09C",
	"9RaNcYVNIs1rb5E+NgRlyew31V5gjxUaHGZkbMZ3mG9yOFPaUAU1Mq63Z+8jiAvm9Z4YeUO/dHRsBK+d",
	"M82ezt5nkduhtn17FscH/+X0lvXBacZK+PkdH8eRmJB2aveKeGtterlxypNqYS8zTMqbdZq273XrLLk7",
	"UTHT1RCuJ8KenExVQjpBHowcV/8LqeqeXDMqoDXimNw75SbdS0JYX0aTo/c/JDMM5eJIb3TJCOPinFkr",
	"Ngo5CI7K703mJ7Au+AlkC/4jHLeCHyVZiW8tJq/3BUluMR2X+FTH2ESG91e2uO27Nhz/axIH5gf3PwX5",
	"9TTm8gfpH69jr05CN3JOyER3czodK60lsqOLzGOFVLldpReKLbN7Ey9Kt0fxI+LIBJhS9lJzTD5rtJZt",
	"8IiwO4NDqRWKcIPp4OwLSyj6dPGSBvuI92PoInitmgekPvwsXaJi+GlJThfjlGJnR/aug63g2CYwNf1P",
	"36d8LLPs/wAAAP//y9dX5mEQAAA=",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Request a tree planting
	// (POST /api/plant_tree)
	PlantTree(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts HTTP requests to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

// MiddlewareFunc is a middleware function type.
type MiddlewareFunc func(http.Handler) http.Handler

// PlantTree operation middleware
func (siw *ServerInterfaceWrapper) PlantTree(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlantTree(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

// StdHTTPServerOptions configures the StdHTTP server.
type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

// HandlerFromMuxWithBaseURL creates http.Handler with routing and a base URL.
func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options.
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/plant_tree", wrapper.PlantTree)
	return m
}

// UnescapedCookieParamError is returned when a cookie parameter cannot be unescaped.
type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

// UnmarshalingParamError is returned when a parameter cannot be unmarshaled.
type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

// RequiredParamError is returned when a required parameter is missing.
type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

// RequiredHeaderError is returned when a required header is missing.
type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

// InvalidParamFormatError is returned when a parameter has an invalid format.
type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

// TooManyValuesForParamError is returned when a parameter has too many values.
type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

type TreePlantedJSONRequestBody = TreePlantingResult

// RequestEditorFn is the function signature for the RequestEditor callback function.
// It may already be defined if client code is also generated; this is a compatible redeclaration.
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// HttpRequestDoer performs HTTP requests.
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// CallbackInitiator sends callback requests to target URLs.
// Unlike Client, it has no stored base URL — the full target URL is provided per-call.
type CallbackInitiator struct {
	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// CallbackInitiatorOption allows setting custom parameters during construction.
type CallbackInitiatorOption func(*CallbackInitiator) error

// NewCallbackInitiator creates a new CallbackInitiator with reasonable defaults.
func NewCallbackInitiator(opts ...CallbackInitiatorOption) (*CallbackInitiator, error) {
	initiator := CallbackInitiator{}
	for _, o := range opts {
		if err := o(&initiator); err != nil {
			return nil, err
		}
	}
	if initiator.Client == nil {
		initiator.Client = &http.Client{}
	}
	return &initiator, nil
}

// WithCallbackHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithCallbackHTTPClient(doer HttpRequestDoer) CallbackInitiatorOption {
	return func(p *CallbackInitiator) error {
		p.Client = doer
		return nil
	}
}

// WithCallbackRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithCallbackRequestEditorFn(fn RequestEditorFn) CallbackInitiatorOption {
	return func(p *CallbackInitiator) error {
		p.RequestEditors = append(p.RequestEditors, fn)
		return nil
	}
}

func (p *CallbackInitiator) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range p.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// CallbackInitiatorInterface is the interface specification for the callback initiator.
type CallbackInitiatorInterface interface {
	// TreePlantedWithBody sends a POST callback request
	TreePlantedWithBody(ctx context.Context, targetURL string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	TreePlanted(ctx context.Context, targetURL string, body TreePlantedJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// TreePlantedWithBody sends a POST callback request
// Tree planting result notification
func (p *CallbackInitiator) TreePlantedWithBody(ctx context.Context, targetURL string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTreePlantedCallbackRequestWithBody(targetURL, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := p.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return p.Client.Do(req)
}

// TreePlanted sends a POST callback request with application/json body
func (p *CallbackInitiator) TreePlanted(ctx context.Context, targetURL string, body TreePlantedJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTreePlantedCallbackRequest(targetURL, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := p.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return p.Client.Do(req)
}

// NewTreePlantedCallbackRequest creates a POST request for the callback with application/json body
func NewTreePlantedCallbackRequest(targetURL string, body TreePlantedJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewTreePlantedCallbackRequestWithBody(targetURL, "application/json", bodyReader)
}

// NewTreePlantedCallbackRequestWithBody creates a POST request for the callback with any body
func NewTreePlantedCallbackRequestWithBody(targetURL string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	reqURL, err := url.Parse(targetURL)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// CallbackHttpError represents an HTTP error response from the callback.
// The type parameter E is the type of the parsed error body.
type CallbackHttpError[E any] struct {
	StatusCode int
	Body       E
	RawBody    []byte
}

func (e *CallbackHttpError[E]) Error() string {
	return fmt.Sprintf("HTTP %d", e.StatusCode)
}

// SimpleCallbackInitiator wraps CallbackInitiator with typed responses for operations that have
// unambiguous response types. Methods return the success type directly,
// and HTTP errors are returned as *CallbackHttpError[E] where E is the error type.
type SimpleCallbackInitiator struct {
	*CallbackInitiator
}

// NewSimpleCallbackInitiator creates a new SimpleCallbackInitiator which wraps a CallbackInitiator.
func NewSimpleCallbackInitiator(opts ...CallbackInitiatorOption) (*SimpleCallbackInitiator, error) {
	inner, err := NewCallbackInitiator(opts...)
	if err != nil {
		return nil, err
	}
	return &SimpleCallbackInitiator{CallbackInitiator: inner}, nil
}

// CallbackReceiverInterface represents handlers for receiving callback requests.
type CallbackReceiverInterface interface {
	// Tree planting result notification
	// HandleTreePlantedCallback handles the POST callback request.
	HandleTreePlantedCallback(w http.ResponseWriter, r *http.Request)
}

// CallbackReceiverMiddlewareFunc is a middleware function for callback receiver handlers.
type CallbackReceiverMiddlewareFunc func(http.Handler) http.Handler

// TreePlantedCallbackHandler returns an http.Handler for the TreePlanted callback.
// The caller is responsible for registering this handler at the appropriate path.
func TreePlantedCallbackHandler(si CallbackReceiverInterface, errHandler func(w http.ResponseWriter, r *http.Request, err error), middlewares ...CallbackReceiverMiddlewareFunc) http.Handler {
	if errHandler == nil {
		errHandler = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			si.HandleTreePlantedCallback(w, r)
		}))

		for _, middleware := range middlewares {
			handler = middleware(handler)
		}

		handler.ServeHTTP(w, r)
	})
}

// MarshalText implements encoding.TextMarshaler for Date.

// Format returns the date formatted according to layout.

// ErrValidationEmail is the sentinel error returned when an email fails validation

// Email represents an email address.
// It is a string type that must pass regex validation before being marshalled
// to JSON or unmarshalled from JSON.

// Nullable is a generic type that can distinguish between:
// - Field not provided (unspecified)
// - Field explicitly set to null
// - Field has a value
//
// This is implemented as a map[bool]T where:
// - Empty map: unspecified
// - map[false]T: explicitly null
// - map[true]T: has a value

// NewNullableWithValue creates a Nullable with the given value.

// NewNullNullable creates a Nullable that is explicitly null.

// Get returns the value if set, or an error if null or unspecified.

// MustGet returns the value or panics if null or unspecified.

// Set assigns a value.

// SetNull marks the field as explicitly null.

// SetUnspecified clears the field (as if it was never set).

// IsNull returns true if the field is explicitly null.

// IsSpecified returns true if the field was provided (either null or a value).

// MarshalJSON implements json.Marshaler.

// Unspecified - this shouldn't be called if omitempty is used correctly

// UnmarshalJSON implements json.Unmarshaler.

// ErrNullableIsNull is returned when trying to get a value from a null Nullable.

// ErrNullableNotSpecified is returned when trying to get a value from an unspecified Nullable.

type UUID = uuid.UUID

// BindParameter binds a styled parameter from a single string value to a Go
// object. This is the entry point for path, header, and cookie parameters
// where the HTTP framework has already extracted the raw value.
//
// The Style field in opts selects how the value is split into parts (simple,
// label, matrix, form). If Style is empty, "simple" is assumed.

// Unescape based on parameter location.

// If the destination implements encoding.TextUnmarshaler, use it directly.

// Primitive types: only label and matrix need prefix stripping via
// splitStyledParameter. Simple and form can bind the raw value directly —
// splitting on commas would incorrectly reject values that contain commas.

// BindQueryParameter binds a query parameter from pre-parsed url.Values.
// The Style field in opts selects parsing behavior. If Style is empty, "form"
// is assumed. Supports form, spaceDelimited, pipeDelimited, and deepObject.

// Destination value management for optional (pointer) parameters.

// Exploded: each value is a separate key=value pair.
// spaceDelimited and pipeDelimited with explode=true are
// serialized identically to form explode=true.

// Non-exploded: single value, delimiter-separated.

// Primitive types: use the raw value as-is without splitting.

// Some struct types (e.g. Date, time.Time) are scalar values
// that should be bound from a single string, not decomposed as
// key-value objects.

// BindRawQueryParameter works like BindQueryParameter but operates on the raw
// (undecoded) query string. This correctly handles form/explode=false
// parameters whose values contain literal commas encoded as %2C — something
// that BindQueryParameter cannot do because url.Values has already decoded
// %2C to ',' before we can split on the delimiter comma.

// For explode, url.ParseQuery is fine — no delimiter commas to
// confuse with literal commas.

// explode=false — use findRawQueryParam to get the still-encoded
// value, split on the style-specific delimiter, then URL-decode
// each resulting part individually.

// Primitive types: decode as-is without splitting.

// ---------------------------------------------------------------------------
// Deep object internals
// ---------------------------------------------------------------------------

// unmarshalDeepObject is the internal implementation of deep object
// unmarshaling that supports the required parameter.

// UnmarshalDeepObject unmarshals deepObject-style query parameters to a
// destination. Exported for use by generated code and tests.

// ---------------------------------------------------------------------------
// Exploded object binding
// ---------------------------------------------------------------------------

// bindParamsToExplodedObject reflects the destination structure and pulls the
// value for each settable field from the given query parameters. Returns
// whether any fields were bound.

// indirectBinder checks if dest implements Binder and returns reflect values.

// ParamLocation indicates where a parameter is located in an HTTP request.

// Binder is an interface for types that can bind themselves from a string value.

// MissingRequiredParameterError is returned when a required parameter is not
// present in the request. Upper layers can use errors.As to detect this and
// produce an appropriate HTTP error response.

// primitiveToString converts a primitive value to a string representation.
// It handles basic Go types, time.Time, Date, and types that implement
// json.Marshaler or fmt.Stringer.

// Check for known types first (time, date, uuid)

// Dereference pointers for optional values

// Check if it's a UUID

// Check if it implements json.Marshaler

// marshalKnownTypes checks for special types (time.Time, Date, UUID) and marshals them.

// escapeParameterName escapes a parameter name for use in query strings and
// paths. This ensures characters like [] in parameter names (e.g. user_ids[])
// are properly percent-encoded per RFC 3986.

// Parameter names should always be encoded regardless of allowReserved,
// which only applies to values per the OpenAPI spec.

// escapeParameterString escapes a parameter value based on its location.
// Query and path parameters need URL escaping; headers and cookies do not.
// When allowReserved is true and the location is query, RFC 3986 reserved
// characters are left unencoded per the OpenAPI allowReserved specification.

// escapeQueryAllowReserved percent-encodes a query parameter value while
// leaving RFC 3986 reserved characters (:/?#[]@!$&'()*+,;=) unencoded, as
// specified by OpenAPI's allowReserved parameter option.

// isUnreserved reports whether the byte is an RFC 3986 unreserved character:
// ALPHA / DIGIT / "-" / "." / "_" / "~"

// unescapeParameterString unescapes a parameter value based on its location.

// sortedKeys returns the keys of a map in sorted order.

// BindStringToObject binds a string value to a destination object.
// It handles primitives, encoding.TextUnmarshaler, and the Binder interface.

// Check for TextUnmarshaler

// Check for Binder interface

// Try JSON unmarshal as a fallback

// bindSplitPartsToDestinationArray binds a slice of string parts to a destination slice.

// bindSplitPartsToDestinationStruct binds string parts to a destination struct via JSON.

// splitStyledParameter splits a styled parameter string value into parts based
// on the OpenAPI style. The object flag indicates whether the destination is a
// struct/map (affects matrix explode handling).

// In the simple case, we always split on comma

// Exploded: .a.b.c or .key=value.key=value

// Unexploded: .a,b,c

// Exploded: ;a;b;c or ;key=value;key=value

// Unexploded: ;paramName=a,b,c

// findRawQueryParam extracts values for a named parameter from a raw
// (undecoded) query string. The parameter key is decoded for comparison
// purposes, but the returned values remain in their original encoded form.

// Skip malformed keys.

// isByteSlice reports whether t is []byte (or equivalently []uint8).

// base64Decode decodes s as base64.
//
// Per OpenAPI 3.0, format: byte uses RFC 4648 Section 4 (standard alphabet,
// padded). We use padding presence to select the right decoder, rather than
// blindly cascading (which can produce corrupt output when RawStdEncoding
// silently accepts padded input and treats '=' as data).

// structToFieldDict converts a struct to a map of field names to string values.

// Skip nil optional fields

// ParameterOptions carries OpenAPI parameter metadata to bind and style
// functions so they can handle style dispatch, explode, required,
// type-aware coercions, and location-aware escaping from a single
// uniform call site. All fields have sensible zero-value defaults.

// OpenAPI style: "simple", "form", "label", "matrix", "deepObject", "pipeDelimited", "spaceDelimited"
// Where the parameter appears: query, path, header, cookie

// OpenAPI type: "string", "integer", "array", "object"
// OpenAPI format: "int32", "date-time", etc.
// When true, reserved characters in query values are not percent-encoded

// StyleParameter serializes a Go value into an OpenAPI-styled parameter string.
// This is the entry point for client-side parameter serialization. The Style
// field in opts selects the serialization format. If Style is empty, "simple"
// is assumed.

// Dereference pointers; error on nil.

// If the value implements encoding.TextMarshaler, use it — but not for
// time.Time or Date which have their own formatting logic.

// ---------------------------------------------------------------------------
// Internal style helpers
// ---------------------------------------------------------------------------

// If input implements json.Marshaler (e.g. objects with additional properties
// or anyOf), marshal to JSON and re-style the generic structure.

// Build a dictionary of the struct's fields.

// Skip nil optional fields.

// ---------------------------------------------------------------------------
// Deep object marshaling
// ---------------------------------------------------------------------------

// MarshalDeepObject marshals an object to deepObject style query parameters.

// JSONMerge merges two JSON-encoded objects. Fields from patch override
// fields in base. Both arguments must be valid JSON objects (or nil/null).

// MarshalForm marshals a struct into url.Values using the struct's json tags
// as field names. It handles nested structs, slices, pointers, and
// AdditionalProperties maps.
