// Code generated by oapi-codegen; DO NOT EDIT.

package output

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"
	"sync"

	oapiCodegenHelpersPkg "github.com/oapi-codegen/oapi-codegen-exp/runtime/helpers"
)

// #/components/schemas/test

type Test struct {
	union json.RawMessage
}

// AsTestAnyOf0 returns the union data inside the Test as a TestAnyOf0.
func (t Test) AsTestAnyOf0() (TestAnyOf0, error) {
	var body TestAnyOf0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTestAnyOf0 overwrites any union data inside the Test as the provided TestAnyOf0.
func (t *Test) FromTestAnyOf0(v TestAnyOf0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTestAnyOf0 performs a merge with any union data inside the Test, using the provided TestAnyOf0.
func (t *Test) MergeTestAnyOf0(v TestAnyOf0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTestAnyOf1 returns the union data inside the Test as a TestAnyOf1.
func (t Test) AsTestAnyOf1() (TestAnyOf1, error) {
	var body TestAnyOf1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTestAnyOf1 overwrites any union data inside the Test as the provided TestAnyOf1.
func (t *Test) FromTestAnyOf1(v TestAnyOf1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTestAnyOf1 performs a merge with any union data inside the Test, using the provided TestAnyOf1.
func (t *Test) MergeTestAnyOf1(v TestAnyOf1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Test) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Test) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *Test) ApplyDefaults() {
}

// #/components/schemas/test/anyOf/0
type TestAnyOf0 struct {
	Item1 string `form:"item1" json:"item1"`
	Item2 string `form:"item2" json:"item2"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *TestAnyOf0) ApplyDefaults() {
}

// #/components/schemas/test/anyOf/1
type TestAnyOf1 struct {
	Item2 *string `form:"item2,omitempty" json:"item2,omitempty"`
	Item3 *string `form:"item3,omitempty" json:"item3,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *TestAnyOf1) ApplyDefaults() {
}

// #/components/schemas/test2

type Test2 struct {
	union json.RawMessage
}

// AsInt0 returns the union data inside the Test2 as a int.
func (t Test2) AsInt0() (int, error) {
	var body int
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInt0 overwrites any union data inside the Test2 as the provided int.
func (t *Test2) FromInt0(v int) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInt0 performs a merge with any union data inside the Test2, using the provided int.
func (t *Test2) MergeInt0(v int) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsString1 returns the union data inside the Test2 as a string.
func (t Test2) AsString1() (string, error) {
	var body string
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromString1 overwrites any union data inside the Test2 as the provided string.
func (t *Test2) FromString1(v string) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeString1 performs a merge with any union data inside the Test2, using the provided string.
func (t *Test2) MergeString1(v string) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Test2) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Test2) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *Test2) ApplyDefaults() {
}

// #/paths//test/get/parameters/1/schema
type GetTestParameter = []Test2

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/5SSTVLDMAyF9znFm8JMV/1Ld94xHIAzmFRtBI3tSioz4fRM0rRJIVC6cz496T0rjomC",
	"T+wwWc+X8+Uk47CNLgM+SJRjcFg1PAOMbU8OT6F+2SJ58RUZSQZsSAvhZK36uaTiXfs6lIT9nj8JpddT",
	"d5a8ldqYLIzUmgOwo+6AvlnPZIbgK3Jo5B0CODgcjiT1hWhRUuXd5Rt4FNo6TB8WRaxSDBRMFyeVtt7T",
	"EYP8LgerEzl4EV8PKBtVOpTdjpJPs77StHbF05R+UYBvltgPn3UZ4usbFTbwFDocWWhznWPWhluNsHzA",
	"ksREYkzfbtH2XqPzDtSEw+6HOv+X+tdL/BUkvyvI+qa6/Q1nVQw0tmUORrv23V/zbsxXAAAA//8J8F+B",
	"UAMAAA==",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}
