// Code generated by oapi-codegen; DO NOT EDIT.

package output

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"mime/multipart"
	"regexp"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"
)

// #/components/schemas/AllTypesRequired
type AllTypesRequired struct {
	IntField      int       `form:"intField" json:"intField"`
	Int32Field    int32     `form:"int32Field" json:"int32Field"`
	Int64Field    int64     `form:"int64Field" json:"int64Field"`
	FloatField    float32   `form:"floatField" json:"floatField"`
	DoubleField   float64   `form:"doubleField" json:"doubleField"`
	NumberField   float32   `form:"numberField" json:"numberField"`
	StringField   string    `form:"stringField" json:"stringField"`
	BoolField     bool      `form:"boolField" json:"boolField"`
	DateField     Date      `form:"dateField" json:"dateField"`
	DateTimeField time.Time `form:"dateTimeField" json:"dateTimeField"`
	UUIDField     UUID      `form:"uuidField" json:"uuidField"`
	EmailField    Email     `form:"emailField" json:"emailField"`
	URIField      string    `form:"uriField" json:"uriField"`
	HostnameField string    `form:"hostnameField" json:"hostnameField"`
	Ipv4Field     string    `form:"ipv4Field" json:"ipv4Field"`
	Ipv6Field     string    `form:"ipv6Field" json:"ipv6Field"`
	ByteField     []byte    `form:"byteField" json:"byteField"`
	BinaryField   File      `form:"binaryField" json:"binaryField"`
	PasswordField string    `form:"passwordField" json:"passwordField"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AllTypesRequired) ApplyDefaults() {
}

// #/components/schemas/AllTypesOptional
type AllTypesOptional struct {
	IntField      *int       `form:"intField,omitempty" json:"intField,omitempty"`
	Int32Field    *int32     `form:"int32Field,omitempty" json:"int32Field,omitempty"`
	Int64Field    *int64     `form:"int64Field,omitempty" json:"int64Field,omitempty"`
	FloatField    *float32   `form:"floatField,omitempty" json:"floatField,omitempty"`
	DoubleField   *float64   `form:"doubleField,omitempty" json:"doubleField,omitempty"`
	NumberField   *float32   `form:"numberField,omitempty" json:"numberField,omitempty"`
	StringField   *string    `form:"stringField,omitempty" json:"stringField,omitempty"`
	BoolField     *bool      `form:"boolField,omitempty" json:"boolField,omitempty"`
	DateField     *Date      `form:"dateField,omitempty" json:"dateField,omitempty"`
	DateTimeField *time.Time `form:"dateTimeField,omitempty" json:"dateTimeField,omitempty"`
	UUIDField     *UUID      `form:"uuidField,omitempty" json:"uuidField,omitempty"`
	EmailField    *Email     `form:"emailField,omitempty" json:"emailField,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AllTypesOptional) ApplyDefaults() {
}

// #/components/schemas/NullableRequired
type NullableRequired struct {
	NullableString Nullable[string]                         `form:"nullableString" json:"nullableString"`
	NullableInt    Nullable[int]                            `form:"nullableInt" json:"nullableInt"`
	NullableObject Nullable[NullableRequiredNullableObject] `form:"nullableObject" json:"nullableObject"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *NullableRequired) ApplyDefaults() {
}

// #/components/schemas/NullableRequired/properties/nullableObject
type NullableRequiredNullableObject struct {
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *NullableRequiredNullableObject) ApplyDefaults() {
}

// #/components/schemas/NullableOptional
type NullableOptional struct {
	NullableString Nullable[string] `form:"nullableString,omitempty" json:"nullableString,omitempty"`
	NullableInt    Nullable[int]    `form:"nullableInt,omitempty" json:"nullableInt,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *NullableOptional) ApplyDefaults() {
}

// #/components/schemas/NullableRefOneOf
type NullableRefOneOf struct {
	NullableObject         Nullable[SimpleObject] `form:"nullableObject" json:"nullableObject"`
	NullableObjectOptional Nullable[SimpleObject] `form:"nullableObjectOptional,omitempty" json:"nullableObjectOptional,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *NullableRefOneOf) ApplyDefaults() {
}

// #/components/schemas/NullableRefAnyOf
type NullableRefAnyOf struct {
	NullableObject Nullable[SimpleObject] `form:"nullableObject" json:"nullableObject"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *NullableRefAnyOf) ApplyDefaults() {
}

// #/components/schemas/ArrayTypes
type ArrayTypes struct {
	StringArray          []string                          `form:"stringArray,omitempty" json:"stringArray,omitempty"`
	IntArray             []int                             `form:"intArray,omitempty" json:"intArray,omitempty"`
	ObjectArray          []SimpleObject                    `form:"objectArray,omitempty" json:"objectArray,omitempty"`
	InlineObjectArray    []ArrayTypesInlineObjectArrayItem `form:"inlineObjectArray,omitempty" json:"inlineObjectArray,omitempty"`
	NestedArray          [][]string                        `form:"nestedArray,omitempty" json:"nestedArray,omitempty"`
	NullableArray        []string                          `form:"nullableArray,omitempty" json:"nullableArray,omitempty"`
	ArrayWithConstraints []string                          `form:"arrayWithConstraints,omitempty" json:"arrayWithConstraints,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ArrayTypes) ApplyDefaults() {
}

// #/components/schemas/ArrayTypes/properties/objectArray
type ArrayTypesObjectArray = []SimpleObject

// #/components/schemas/ArrayTypes/properties/inlineObjectArray
type ArrayTypesInlineObjectArray = []ArrayTypesInlineObjectArrayItem

// #/components/schemas/ArrayTypes/properties/inlineObjectArray/items
type ArrayTypesInlineObjectArrayItem struct {
	ID   *int    `form:"id,omitempty" json:"id,omitempty"`
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ArrayTypesInlineObjectArrayItem) ApplyDefaults() {
}

// #/components/schemas/SimpleObject
type SimpleObject struct {
	ID   int     `form:"id" json:"id"`
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *SimpleObject) ApplyDefaults() {
}

// #/components/schemas/NestedObject
type NestedObject struct {
	Outer *NestedObjectOuter `form:"outer,omitempty" json:"outer,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *NestedObject) ApplyDefaults() {
	if s.Outer != nil {
		s.Outer.ApplyDefaults()
	}
}

// #/components/schemas/NestedObject/properties/outer
type NestedObjectOuter struct {
	Inner *NestedObjectOuterInner `form:"inner,omitempty" json:"inner,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *NestedObjectOuter) ApplyDefaults() {
	if s.Inner != nil {
		s.Inner.ApplyDefaults()
	}
}

// #/components/schemas/NestedObject/properties/outer/properties/inner
type NestedObjectOuterInner struct {
	Value *string `form:"value,omitempty" json:"value,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *NestedObjectOuterInner) ApplyDefaults() {
}

// #/components/schemas/AdditionalPropsAny
type AdditionalPropsAny = map[string]any

// #/components/schemas/AdditionalPropsNone
type AdditionalPropsNone struct {
	Known                *string        `form:"known,omitempty" json:"known,omitempty"`
	AdditionalProperties map[string]any `json:"-"`
}

func (s AdditionalPropsNone) MarshalJSON() ([]byte, error) {
	result := make(map[string]any)

	if s.Known != nil {
		result["known"] = s.Known
	}

	// Add additional properties
	for k, v := range s.AdditionalProperties {
		result[k] = v
	}

	return json.Marshal(result)
}

func (s *AdditionalPropsNone) UnmarshalJSON(data []byte) error {
	// Known fields
	knownFields := map[string]bool{
		"known": true,
	}

	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	if v, ok := raw["known"]; ok {
		var val string
		if err := json.Unmarshal(v, &val); err != nil {
			return err
		}
		s.Known = &val
	}

	// Collect additional properties
	s.AdditionalProperties = make(map[string]any)
	for k, v := range raw {
		if !knownFields[k] {
			var val any
			if err := json.Unmarshal(v, &val); err != nil {
				return err
			}
			s.AdditionalProperties[k] = val
		}
	}

	return nil
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AdditionalPropsNone) ApplyDefaults() {
}

// #/components/schemas/AdditionalPropsTyped
type AdditionalPropsTyped = map[string]int

// #/components/schemas/AdditionalPropsObject
type AdditionalPropsObject = map[string]any

// #/components/schemas/AdditionalPropsWithProps
type AdditionalPropsWithProps struct {
	ID                   *int              `form:"id,omitempty" json:"id,omitempty"`
	AdditionalProperties map[string]string `json:"-"`
}

func (s AdditionalPropsWithProps) MarshalJSON() ([]byte, error) {
	result := make(map[string]any)

	if s.ID != nil {
		result["id"] = s.ID
	}

	// Add additional properties
	for k, v := range s.AdditionalProperties {
		result[k] = v
	}

	return json.Marshal(result)
}

func (s *AdditionalPropsWithProps) UnmarshalJSON(data []byte) error {
	// Known fields
	knownFields := map[string]bool{
		"id": true,
	}

	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	if v, ok := raw["id"]; ok {
		var val int
		if err := json.Unmarshal(v, &val); err != nil {
			return err
		}
		s.ID = &val
	}

	// Collect additional properties
	s.AdditionalProperties = make(map[string]string)
	for k, v := range raw {
		if !knownFields[k] {
			var val string
			if err := json.Unmarshal(v, &val); err != nil {
				return err
			}
			s.AdditionalProperties[k] = val
		}
	}

	return nil
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AdditionalPropsWithProps) ApplyDefaults() {
}

// #/components/schemas/StringEnum
type StringEnum string

const (
	Value1 StringEnum = "value1"
	Value2 StringEnum = "value2"
	Value3 StringEnum = "value3"
)

// #/components/schemas/IntegerEnum
type IntegerEnum int

const (
	IntegerEnumN1 IntegerEnum = 1
	IntegerEnumN2 IntegerEnum = 2
	IntegerEnumN3 IntegerEnum = 3
)

// #/components/schemas/ObjectWithEnum
type ObjectWithEnum struct {
	Status   *string `form:"status,omitempty" json:"status,omitempty"`
	Priority *int    `form:"priority,omitempty" json:"priority,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ObjectWithEnum) ApplyDefaults() {
}

// #/components/schemas/ObjectWithEnum/properties/status
type ObjectWithEnumStatus string

const (
	Pending   ObjectWithEnumStatus = "pending"
	Active    ObjectWithEnumStatus = "active"
	Completed ObjectWithEnumStatus = "completed"
)

// #/components/schemas/ObjectWithEnum/properties/priority
type ObjectWithEnumPriority int

const (
	ObjectWithEnumPriorityN1 ObjectWithEnumPriority = 1
	ObjectWithEnumPriorityN2 ObjectWithEnumPriority = 2
	ObjectWithEnumPriorityN3 ObjectWithEnumPriority = 3
)

// #/components/schemas/InlineEnumInProperty
type InlineEnumInProperty struct {
	InlineStatus *string `form:"inlineStatus,omitempty" json:"inlineStatus,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *InlineEnumInProperty) ApplyDefaults() {
}

// #/components/schemas/InlineEnumInProperty/properties/inlineStatus
type InlineEnumInPropertyInlineStatus string

const (
	On  InlineEnumInPropertyInlineStatus = "on"
	Off InlineEnumInPropertyInlineStatus = "off"
)

// #/components/schemas/BaseProperties
type BaseProperties struct {
	ID        *int       `form:"id,omitempty" json:"id,omitempty"`
	CreatedAt *time.Time `form:"createdAt,omitempty" json:"createdAt,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *BaseProperties) ApplyDefaults() {
}

// #/components/schemas/ExtendedObject
type ExtendedObject struct {
	ID          *int       `form:"id,omitempty" json:"id,omitempty"`
	CreatedAt   *time.Time `form:"createdAt,omitempty" json:"createdAt,omitempty"`
	Name        string     `form:"name" json:"name"`
	Description *string    `form:"description,omitempty" json:"description,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ExtendedObject) ApplyDefaults() {
}

// #/components/schemas/DeepInheritance
type DeepInheritance struct {
	ID          *int       `form:"id,omitempty" json:"id,omitempty"`
	CreatedAt   *time.Time `form:"createdAt,omitempty" json:"createdAt,omitempty"`
	Name        string     `form:"name" json:"name"`
	Description *string    `form:"description,omitempty" json:"description,omitempty"`
	Extra       *string    `form:"extra,omitempty" json:"extra,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *DeepInheritance) ApplyDefaults() {
}

// #/components/schemas/AllOfMultipleRefs
type AllOfMultipleRefs struct {
	ID        int        `form:"id" json:"id"`
	CreatedAt *time.Time `form:"createdAt,omitempty" json:"createdAt,omitempty"`
	Name      *string    `form:"name,omitempty" json:"name,omitempty"`
	Merged    *bool      `form:"merged,omitempty" json:"merged,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AllOfMultipleRefs) ApplyDefaults() {
}

// #/components/schemas/AllOfInlineOnly
type AllOfInlineOnly struct {
	First  *string `form:"first,omitempty" json:"first,omitempty"`
	Second *int    `form:"second,omitempty" json:"second,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AllOfInlineOnly) ApplyDefaults() {
}

// #/components/schemas/AnyOfPrimitives
type AnyOfPrimitives struct {
	String0 *string
	Int1    *int
}

func (u AnyOfPrimitives) MarshalJSON() ([]byte, error) {
	if u.String0 != nil {
		return json.Marshal(u.String0)
	}
	if u.Int1 != nil {
		return json.Marshal(u.Int1)
	}
	return []byte("null"), nil
}

func (u *AnyOfPrimitives) UnmarshalJSON(data []byte) error {
	var v0 string
	if err := json.Unmarshal(data, &v0); err == nil {
		u.String0 = &v0
	}

	var v1 int
	if err := json.Unmarshal(data, &v1); err == nil {
		u.Int1 = &v1
	}

	return nil
}

// ApplyDefaults sets default values for fields that are nil.
func (u *AnyOfPrimitives) ApplyDefaults() {
}

// #/components/schemas/AnyOfObjects
type AnyOfObjects struct {
	SimpleObject   *SimpleObject
	BaseProperties *BaseProperties
}

func (u AnyOfObjects) MarshalJSON() ([]byte, error) {
	result := make(map[string]any)

	if u.SimpleObject != nil {
		data, err := json.Marshal(u.SimpleObject)
		if err != nil {
			return nil, err
		}
		var m map[string]any
		if err := json.Unmarshal(data, &m); err == nil {
			for k, v := range m {
				result[k] = v
			}
		}
	}
	if u.BaseProperties != nil {
		data, err := json.Marshal(u.BaseProperties)
		if err != nil {
			return nil, err
		}
		var m map[string]any
		if err := json.Unmarshal(data, &m); err == nil {
			for k, v := range m {
				result[k] = v
			}
		}
	}

	return json.Marshal(result)
}

func (u *AnyOfObjects) UnmarshalJSON(data []byte) error {
	var v0 SimpleObject
	if err := json.Unmarshal(data, &v0); err == nil {
		u.SimpleObject = &v0
	}

	var v1 BaseProperties
	if err := json.Unmarshal(data, &v1); err == nil {
		u.BaseProperties = &v1
	}

	return nil
}

// ApplyDefaults sets default values for fields that are nil.
func (u *AnyOfObjects) ApplyDefaults() {
	if u.SimpleObject != nil {
		u.SimpleObject.ApplyDefaults()
	}
	if u.BaseProperties != nil {
		u.BaseProperties.ApplyDefaults()
	}
}

// #/components/schemas/AnyOfMixed
type AnyOfMixed struct {
	String0          *string
	SimpleObject     *SimpleObject
	AnyOfMixedAnyOf2 *AnyOfMixedAnyOf2
}

func (u AnyOfMixed) MarshalJSON() ([]byte, error) {
	result := make(map[string]any)

	if u.String0 != nil {
		return json.Marshal(u.String0)
	}
	if u.SimpleObject != nil {
		data, err := json.Marshal(u.SimpleObject)
		if err != nil {
			return nil, err
		}
		var m map[string]any
		if err := json.Unmarshal(data, &m); err == nil {
			for k, v := range m {
				result[k] = v
			}
		}
	}
	if u.AnyOfMixedAnyOf2 != nil {
		data, err := json.Marshal(u.AnyOfMixedAnyOf2)
		if err != nil {
			return nil, err
		}
		var m map[string]any
		if err := json.Unmarshal(data, &m); err == nil {
			for k, v := range m {
				result[k] = v
			}
		}
	}

	return json.Marshal(result)
}

func (u *AnyOfMixed) UnmarshalJSON(data []byte) error {
	var v0 string
	if err := json.Unmarshal(data, &v0); err == nil {
		u.String0 = &v0
	}

	var v1 SimpleObject
	if err := json.Unmarshal(data, &v1); err == nil {
		u.SimpleObject = &v1
	}

	var v2 AnyOfMixedAnyOf2
	if err := json.Unmarshal(data, &v2); err == nil {
		u.AnyOfMixedAnyOf2 = &v2
	}

	return nil
}

// ApplyDefaults sets default values for fields that are nil.
func (u *AnyOfMixed) ApplyDefaults() {
	if u.SimpleObject != nil {
		u.SimpleObject.ApplyDefaults()
	}
	if u.AnyOfMixedAnyOf2 != nil {
		u.AnyOfMixedAnyOf2.ApplyDefaults()
	}
}

// #/components/schemas/AnyOfMixed/anyOf/2
type AnyOfMixedAnyOf2 struct {
	Inline *bool `form:"inline,omitempty" json:"inline,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AnyOfMixedAnyOf2) ApplyDefaults() {
}

// #/components/schemas/AnyOfNullable
type AnyOfNullable = Nullable[string]

// #/components/schemas/ObjectWithAnyOfProperty
type ObjectWithAnyOfProperty struct {
	Value *ObjectWithAnyOfPropertyValue `form:"value,omitempty" json:"value,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ObjectWithAnyOfProperty) ApplyDefaults() {
}

// #/components/schemas/ObjectWithAnyOfProperty/properties/value
type ObjectWithAnyOfPropertyValue struct {
	String0 *string
	Int1    *int
	Bool2   *bool
}

func (u ObjectWithAnyOfPropertyValue) MarshalJSON() ([]byte, error) {
	if u.String0 != nil {
		return json.Marshal(u.String0)
	}
	if u.Int1 != nil {
		return json.Marshal(u.Int1)
	}
	if u.Bool2 != nil {
		return json.Marshal(u.Bool2)
	}
	return []byte("null"), nil
}

func (u *ObjectWithAnyOfPropertyValue) UnmarshalJSON(data []byte) error {
	var v0 string
	if err := json.Unmarshal(data, &v0); err == nil {
		u.String0 = &v0
	}

	var v1 int
	if err := json.Unmarshal(data, &v1); err == nil {
		u.Int1 = &v1
	}

	var v2 bool
	if err := json.Unmarshal(data, &v2); err == nil {
		u.Bool2 = &v2
	}

	return nil
}

// ApplyDefaults sets default values for fields that are nil.
func (u *ObjectWithAnyOfPropertyValue) ApplyDefaults() {
}

// #/components/schemas/ArrayOfAnyOf
type ArrayOfAnyOf = []ArrayOfAnyOfItem

// #/components/schemas/ArrayOfAnyOf/items
type ArrayOfAnyOfItem struct {
	SimpleObject   *SimpleObject
	BaseProperties *BaseProperties
}

func (u ArrayOfAnyOfItem) MarshalJSON() ([]byte, error) {
	result := make(map[string]any)

	if u.SimpleObject != nil {
		data, err := json.Marshal(u.SimpleObject)
		if err != nil {
			return nil, err
		}
		var m map[string]any
		if err := json.Unmarshal(data, &m); err == nil {
			for k, v := range m {
				result[k] = v
			}
		}
	}
	if u.BaseProperties != nil {
		data, err := json.Marshal(u.BaseProperties)
		if err != nil {
			return nil, err
		}
		var m map[string]any
		if err := json.Unmarshal(data, &m); err == nil {
			for k, v := range m {
				result[k] = v
			}
		}
	}

	return json.Marshal(result)
}

func (u *ArrayOfAnyOfItem) UnmarshalJSON(data []byte) error {
	var v0 SimpleObject
	if err := json.Unmarshal(data, &v0); err == nil {
		u.SimpleObject = &v0
	}

	var v1 BaseProperties
	if err := json.Unmarshal(data, &v1); err == nil {
		u.BaseProperties = &v1
	}

	return nil
}

// ApplyDefaults sets default values for fields that are nil.
func (u *ArrayOfAnyOfItem) ApplyDefaults() {
	if u.SimpleObject != nil {
		u.SimpleObject.ApplyDefaults()
	}
	if u.BaseProperties != nil {
		u.BaseProperties.ApplyDefaults()
	}
}

// #/components/schemas/OneOfSimple
type OneOfSimple struct {
	SimpleObject   *SimpleObject
	BaseProperties *BaseProperties
}

func (u OneOfSimple) MarshalJSON() ([]byte, error) {
	var count int
	var data []byte
	var err error

	if u.SimpleObject != nil {
		count++
		data, err = json.Marshal(u.SimpleObject)
		if err != nil {
			return nil, err
		}
	}
	if u.BaseProperties != nil {
		count++
		data, err = json.Marshal(u.BaseProperties)
		if err != nil {
			return nil, err
		}
	}

	if count != 1 {
		return nil, fmt.Errorf("OneOfSimple: exactly one member must be set, got %d", count)
	}

	return data, nil
}

func (u *OneOfSimple) UnmarshalJSON(data []byte) error {
	var successCount int

	var v0 SimpleObject
	if err := json.Unmarshal(data, &v0); err == nil {
		u.SimpleObject = &v0
		successCount++
	}

	var v1 BaseProperties
	if err := json.Unmarshal(data, &v1); err == nil {
		u.BaseProperties = &v1
		successCount++
	}

	if successCount != 1 {
		return fmt.Errorf("OneOfSimple: expected exactly one type to match, got %d", successCount)
	}

	return nil
}

// ApplyDefaults sets default values for fields that are nil.
func (u *OneOfSimple) ApplyDefaults() {
	if u.SimpleObject != nil {
		u.SimpleObject.ApplyDefaults()
	}
	if u.BaseProperties != nil {
		u.BaseProperties.ApplyDefaults()
	}
}

// #/components/schemas/OneOfWithDiscriminator
type OneOfWithDiscriminator struct {
	Cat *Cat
	Dog *Dog
}

func (u OneOfWithDiscriminator) MarshalJSON() ([]byte, error) {
	var count int
	var data []byte
	var err error

	if u.Cat != nil {
		count++
		data, err = json.Marshal(u.Cat)
		if err != nil {
			return nil, err
		}
	}
	if u.Dog != nil {
		count++
		data, err = json.Marshal(u.Dog)
		if err != nil {
			return nil, err
		}
	}

	if count != 1 {
		return nil, fmt.Errorf("OneOfWithDiscriminator: exactly one member must be set, got %d", count)
	}

	return data, nil
}

func (u *OneOfWithDiscriminator) UnmarshalJSON(data []byte) error {
	var successCount int

	var v0 Cat
	if err := json.Unmarshal(data, &v0); err == nil {
		u.Cat = &v0
		successCount++
	}

	var v1 Dog
	if err := json.Unmarshal(data, &v1); err == nil {
		u.Dog = &v1
		successCount++
	}

	if successCount != 1 {
		return fmt.Errorf("OneOfWithDiscriminator: expected exactly one type to match, got %d", successCount)
	}

	return nil
}

// ApplyDefaults sets default values for fields that are nil.
func (u *OneOfWithDiscriminator) ApplyDefaults() {
	if u.Cat != nil {
		u.Cat.ApplyDefaults()
	}
	if u.Dog != nil {
		u.Dog.ApplyDefaults()
	}
}

// #/components/schemas/OneOfWithDiscriminatorMapping
type OneOfWithDiscriminatorMapping struct {
	Cat *Cat
	Dog *Dog
}

func (u OneOfWithDiscriminatorMapping) MarshalJSON() ([]byte, error) {
	var count int
	var data []byte
	var err error

	if u.Cat != nil {
		count++
		data, err = json.Marshal(u.Cat)
		if err != nil {
			return nil, err
		}
	}
	if u.Dog != nil {
		count++
		data, err = json.Marshal(u.Dog)
		if err != nil {
			return nil, err
		}
	}

	if count != 1 {
		return nil, fmt.Errorf("OneOfWithDiscriminatorMapping: exactly one member must be set, got %d", count)
	}

	return data, nil
}

func (u *OneOfWithDiscriminatorMapping) UnmarshalJSON(data []byte) error {
	var successCount int

	var v0 Cat
	if err := json.Unmarshal(data, &v0); err == nil {
		u.Cat = &v0
		successCount++
	}

	var v1 Dog
	if err := json.Unmarshal(data, &v1); err == nil {
		u.Dog = &v1
		successCount++
	}

	if successCount != 1 {
		return fmt.Errorf("OneOfWithDiscriminatorMapping: expected exactly one type to match, got %d", successCount)
	}

	return nil
}

// ApplyDefaults sets default values for fields that are nil.
func (u *OneOfWithDiscriminatorMapping) ApplyDefaults() {
	if u.Cat != nil {
		u.Cat.ApplyDefaults()
	}
	if u.Dog != nil {
		u.Dog.ApplyDefaults()
	}
}

// #/components/schemas/Cat
type Cat struct {
	PetType       string   `form:"petType" json:"petType"`
	Meow          string   `form:"meow" json:"meow"`
	WhiskerLength *float32 `form:"whiskerLength,omitempty" json:"whiskerLength,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Cat) ApplyDefaults() {
}

// #/components/schemas/Dog
type Dog struct {
	PetType    string   `form:"petType" json:"petType"`
	Bark       string   `form:"bark" json:"bark"`
	TailLength *float32 `form:"tailLength,omitempty" json:"tailLength,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Dog) ApplyDefaults() {
}

// #/components/schemas/OneOfInline
type OneOfInline struct {
	OneOfInlineOneOf0 *OneOfInlineOneOf0
	OneOfInlineOneOf1 *OneOfInlineOneOf1
}

func (u OneOfInline) MarshalJSON() ([]byte, error) {
	var count int
	var data []byte
	var err error

	if u.OneOfInlineOneOf0 != nil {
		count++
		data, err = json.Marshal(u.OneOfInlineOneOf0)
		if err != nil {
			return nil, err
		}
	}
	if u.OneOfInlineOneOf1 != nil {
		count++
		data, err = json.Marshal(u.OneOfInlineOneOf1)
		if err != nil {
			return nil, err
		}
	}

	if count != 1 {
		return nil, fmt.Errorf("OneOfInline: exactly one member must be set, got %d", count)
	}

	return data, nil
}

func (u *OneOfInline) UnmarshalJSON(data []byte) error {
	var successCount int

	var v0 OneOfInlineOneOf0
	if err := json.Unmarshal(data, &v0); err == nil {
		u.OneOfInlineOneOf0 = &v0
		successCount++
	}

	var v1 OneOfInlineOneOf1
	if err := json.Unmarshal(data, &v1); err == nil {
		u.OneOfInlineOneOf1 = &v1
		successCount++
	}

	if successCount != 1 {
		return fmt.Errorf("OneOfInline: expected exactly one type to match, got %d", successCount)
	}

	return nil
}

// ApplyDefaults sets default values for fields that are nil.
func (u *OneOfInline) ApplyDefaults() {
	if u.OneOfInlineOneOf0 != nil {
		u.OneOfInlineOneOf0.ApplyDefaults()
	}
	if u.OneOfInlineOneOf1 != nil {
		u.OneOfInlineOneOf1.ApplyDefaults()
	}
}

// #/components/schemas/OneOfInline/oneOf/0
type OneOfInlineOneOf0 struct {
	OptionA *string `form:"optionA,omitempty" json:"optionA,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *OneOfInlineOneOf0) ApplyDefaults() {
}

// #/components/schemas/OneOfInline/oneOf/1
type OneOfInlineOneOf1 struct {
	OptionB *int `form:"optionB,omitempty" json:"optionB,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *OneOfInlineOneOf1) ApplyDefaults() {
}

// #/components/schemas/OneOfPrimitives
type OneOfPrimitives struct {
	String0  *string
	Float321 *float32
	Bool2    *bool
}

func (u OneOfPrimitives) MarshalJSON() ([]byte, error) {
	var count int
	var data []byte
	var err error

	if u.String0 != nil {
		count++
		data, err = json.Marshal(u.String0)
		if err != nil {
			return nil, err
		}
	}
	if u.Float321 != nil {
		count++
		data, err = json.Marshal(u.Float321)
		if err != nil {
			return nil, err
		}
	}
	if u.Bool2 != nil {
		count++
		data, err = json.Marshal(u.Bool2)
		if err != nil {
			return nil, err
		}
	}

	if count != 1 {
		return nil, fmt.Errorf("OneOfPrimitives: exactly one member must be set, got %d", count)
	}

	return data, nil
}

func (u *OneOfPrimitives) UnmarshalJSON(data []byte) error {
	var successCount int

	var v0 string
	if err := json.Unmarshal(data, &v0); err == nil {
		u.String0 = &v0
		successCount++
	}

	var v1 float32
	if err := json.Unmarshal(data, &v1); err == nil {
		u.Float321 = &v1
		successCount++
	}

	var v2 bool
	if err := json.Unmarshal(data, &v2); err == nil {
		u.Bool2 = &v2
		successCount++
	}

	if successCount != 1 {
		return fmt.Errorf("OneOfPrimitives: expected exactly one type to match, got %d", successCount)
	}

	return nil
}

// ApplyDefaults sets default values for fields that are nil.
func (u *OneOfPrimitives) ApplyDefaults() {
}

// #/components/schemas/ObjectWithOneOfProperty
type ObjectWithOneOfProperty struct {
	ID      *int                            `form:"id,omitempty" json:"id,omitempty"`
	Variant *ObjectWithOneOfPropertyVariant `form:"variant,omitempty" json:"variant,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ObjectWithOneOfProperty) ApplyDefaults() {
}

// #/components/schemas/ObjectWithOneOfProperty/properties/variant
type ObjectWithOneOfPropertyVariant struct {
	Cat *Cat
	Dog *Dog
}

func (u ObjectWithOneOfPropertyVariant) MarshalJSON() ([]byte, error) {
	var count int
	var data []byte
	var err error

	if u.Cat != nil {
		count++
		data, err = json.Marshal(u.Cat)
		if err != nil {
			return nil, err
		}
	}
	if u.Dog != nil {
		count++
		data, err = json.Marshal(u.Dog)
		if err != nil {
			return nil, err
		}
	}

	if count != 1 {
		return nil, fmt.Errorf("ObjectWithOneOfPropertyVariant: exactly one member must be set, got %d", count)
	}

	return data, nil
}

func (u *ObjectWithOneOfPropertyVariant) UnmarshalJSON(data []byte) error {
	var successCount int

	var v0 Cat
	if err := json.Unmarshal(data, &v0); err == nil {
		u.Cat = &v0
		successCount++
	}

	var v1 Dog
	if err := json.Unmarshal(data, &v1); err == nil {
		u.Dog = &v1
		successCount++
	}

	if successCount != 1 {
		return fmt.Errorf("ObjectWithOneOfPropertyVariant: expected exactly one type to match, got %d", successCount)
	}

	return nil
}

// ApplyDefaults sets default values for fields that are nil.
func (u *ObjectWithOneOfPropertyVariant) ApplyDefaults() {
	if u.Cat != nil {
		u.Cat.ApplyDefaults()
	}
	if u.Dog != nil {
		u.Dog.ApplyDefaults()
	}
}

// #/components/schemas/AllOfWithOneOf
type AllOfWithOneOf struct {
	ID                   *int                  `form:"id,omitempty" json:"id,omitempty"`
	CreatedAt            *time.Time            `form:"createdAt,omitempty" json:"createdAt,omitempty"`
	AllOfWithOneOfAllOf1 *AllOfWithOneOfAllOf1 `json:"-"`
}

func (s AllOfWithOneOf) MarshalJSON() ([]byte, error) {
	result := make(map[string]any)

	if s.ID != nil {
		result["id"] = s.ID
	}
	if s.CreatedAt != nil {
		result["createdAt"] = s.CreatedAt
	}

	if s.AllOfWithOneOfAllOf1 != nil {
		unionData, err := json.Marshal(s.AllOfWithOneOfAllOf1)
		if err != nil {
			return nil, err
		}
		var unionMap map[string]any
		if err := json.Unmarshal(unionData, &unionMap); err == nil {
			for k, v := range unionMap {
				result[k] = v
			}
		}
	}

	return json.Marshal(result)
}

func (s *AllOfWithOneOf) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	if v, ok := raw["id"]; ok {
		var val int
		if err := json.Unmarshal(v, &val); err != nil {
			return err
		}
		s.ID = &val
	}
	if v, ok := raw["createdAt"]; ok {
		var val time.Time
		if err := json.Unmarshal(v, &val); err != nil {
			return err
		}
		s.CreatedAt = &val
	}

	var AllOfWithOneOfAllOf1Val AllOfWithOneOfAllOf1
	if err := json.Unmarshal(data, &AllOfWithOneOfAllOf1Val); err != nil {
		return err
	}
	s.AllOfWithOneOfAllOf1 = &AllOfWithOneOfAllOf1Val

	return nil
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AllOfWithOneOf) ApplyDefaults() {
}

// #/components/schemas/AllOfWithOneOf/allOf/1
type AllOfWithOneOfAllOf1 struct {
	Cat *Cat
	Dog *Dog
}

func (u AllOfWithOneOfAllOf1) MarshalJSON() ([]byte, error) {
	var count int
	var data []byte
	var err error

	if u.Cat != nil {
		count++
		data, err = json.Marshal(u.Cat)
		if err != nil {
			return nil, err
		}
	}
	if u.Dog != nil {
		count++
		data, err = json.Marshal(u.Dog)
		if err != nil {
			return nil, err
		}
	}

	if count != 1 {
		return nil, fmt.Errorf("AllOfWithOneOfAllOf1: exactly one member must be set, got %d", count)
	}

	return data, nil
}

func (u *AllOfWithOneOfAllOf1) UnmarshalJSON(data []byte) error {
	var successCount int

	var v0 Cat
	if err := json.Unmarshal(data, &v0); err == nil {
		u.Cat = &v0
		successCount++
	}

	var v1 Dog
	if err := json.Unmarshal(data, &v1); err == nil {
		u.Dog = &v1
		successCount++
	}

	if successCount != 1 {
		return fmt.Errorf("AllOfWithOneOfAllOf1: expected exactly one type to match, got %d", successCount)
	}

	return nil
}

// ApplyDefaults sets default values for fields that are nil.
func (u *AllOfWithOneOfAllOf1) ApplyDefaults() {
	if u.Cat != nil {
		u.Cat.ApplyDefaults()
	}
	if u.Dog != nil {
		u.Dog.ApplyDefaults()
	}
}

// #/components/schemas/OneOfWithAllOf
type OneOfWithAllOf struct {
	OneOfWithAllOfOneOf0 *OneOfWithAllOfOneOf0
	OneOfWithAllOfOneOf1 *OneOfWithAllOfOneOf1
}

func (u OneOfWithAllOf) MarshalJSON() ([]byte, error) {
	var count int
	var data []byte
	var err error

	if u.OneOfWithAllOfOneOf0 != nil {
		count++
		data, err = json.Marshal(u.OneOfWithAllOfOneOf0)
		if err != nil {
			return nil, err
		}
	}
	if u.OneOfWithAllOfOneOf1 != nil {
		count++
		data, err = json.Marshal(u.OneOfWithAllOfOneOf1)
		if err != nil {
			return nil, err
		}
	}

	if count != 1 {
		return nil, fmt.Errorf("OneOfWithAllOf: exactly one member must be set, got %d", count)
	}

	return data, nil
}

func (u *OneOfWithAllOf) UnmarshalJSON(data []byte) error {
	var successCount int

	var v0 OneOfWithAllOfOneOf0
	if err := json.Unmarshal(data, &v0); err == nil {
		u.OneOfWithAllOfOneOf0 = &v0
		successCount++
	}

	var v1 OneOfWithAllOfOneOf1
	if err := json.Unmarshal(data, &v1); err == nil {
		u.OneOfWithAllOfOneOf1 = &v1
		successCount++
	}

	if successCount != 1 {
		return fmt.Errorf("OneOfWithAllOf: expected exactly one type to match, got %d", successCount)
	}

	return nil
}

// ApplyDefaults sets default values for fields that are nil.
func (u *OneOfWithAllOf) ApplyDefaults() {
	if u.OneOfWithAllOfOneOf0 != nil {
		u.OneOfWithAllOfOneOf0.ApplyDefaults()
	}
	if u.OneOfWithAllOfOneOf1 != nil {
		u.OneOfWithAllOfOneOf1.ApplyDefaults()
	}
}

// #/components/schemas/OneOfWithAllOf/oneOf/0
type OneOfWithAllOfOneOf0 struct {
	ID        *int       `form:"id,omitempty" json:"id,omitempty"`
	CreatedAt *time.Time `form:"createdAt,omitempty" json:"createdAt,omitempty"`
	Variant   *string    `form:"variant,omitempty" json:"variant,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *OneOfWithAllOfOneOf0) ApplyDefaults() {
}

// #/components/schemas/OneOfWithAllOf/oneOf/1
type OneOfWithAllOfOneOf1 struct {
	ID        *int       `form:"id,omitempty" json:"id,omitempty"`
	CreatedAt *time.Time `form:"createdAt,omitempty" json:"createdAt,omitempty"`
	Variant   *string    `form:"variant,omitempty" json:"variant,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *OneOfWithAllOfOneOf1) ApplyDefaults() {
}

// #/components/schemas/TreeNode
type TreeNode struct {
	Value    *string    `form:"value,omitempty" json:"value,omitempty"`
	Children []TreeNode `form:"children,omitempty" json:"children,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *TreeNode) ApplyDefaults() {
}

// #/components/schemas/TreeNode/properties/children
type TreeNodeChildren = []TreeNode

// #/components/schemas/LinkedListNode
type LinkedListNode struct {
	Value *int            `form:"value,omitempty" json:"value,omitempty"`
	Next  *LinkedListNode `form:"next,omitempty" json:"next,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *LinkedListNode) ApplyDefaults() {
	if s.Next != nil {
		s.Next.ApplyDefaults()
	}
}

// #/components/schemas/RecursiveOneOf
type RecursiveOneOf struct {
	String0              *string
	RecursiveOneOfOneOf1 *RecursiveOneOfOneOf1
}

func (u RecursiveOneOf) MarshalJSON() ([]byte, error) {
	var count int
	var data []byte
	var err error

	if u.String0 != nil {
		count++
		data, err = json.Marshal(u.String0)
		if err != nil {
			return nil, err
		}
	}
	if u.RecursiveOneOfOneOf1 != nil {
		count++
		data, err = json.Marshal(u.RecursiveOneOfOneOf1)
		if err != nil {
			return nil, err
		}
	}

	if count != 1 {
		return nil, fmt.Errorf("RecursiveOneOf: exactly one member must be set, got %d", count)
	}

	return data, nil
}

func (u *RecursiveOneOf) UnmarshalJSON(data []byte) error {
	var successCount int

	var v0 string
	if err := json.Unmarshal(data, &v0); err == nil {
		u.String0 = &v0
		successCount++
	}

	var v1 RecursiveOneOfOneOf1
	if err := json.Unmarshal(data, &v1); err == nil {
		u.RecursiveOneOfOneOf1 = &v1
		successCount++
	}

	if successCount != 1 {
		return fmt.Errorf("RecursiveOneOf: expected exactly one type to match, got %d", successCount)
	}

	return nil
}

// ApplyDefaults sets default values for fields that are nil.
func (u *RecursiveOneOf) ApplyDefaults() {
	if u.RecursiveOneOfOneOf1 != nil {
		u.RecursiveOneOfOneOf1.ApplyDefaults()
	}
}

// #/components/schemas/RecursiveOneOf/oneOf/1
type RecursiveOneOfOneOf1 struct {
	Nested *RecursiveOneOf `form:"nested,omitempty" json:"nested,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *RecursiveOneOfOneOf1) ApplyDefaults() {
	if s.Nested != nil {
		s.Nested.ApplyDefaults()
	}
}

// #/components/schemas/ReadWriteOnly
type ReadWriteOnly struct {
	ID       int     `form:"id" json:"id"`
	Password string  `form:"password" json:"password"`
	Name     *string `form:"name,omitempty" json:"name,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ReadWriteOnly) ApplyDefaults() {
}

// #/components/schemas/WithDefaults
type WithDefaults struct {
	StringWithDefault *string  `form:"stringWithDefault,omitempty" json:"stringWithDefault,omitempty"`
	IntWithDefault    *int     `form:"intWithDefault,omitempty" json:"intWithDefault,omitempty"`
	BoolWithDefault   *bool    `form:"boolWithDefault,omitempty" json:"boolWithDefault,omitempty"`
	ArrayWithDefault  []string `form:"arrayWithDefault,omitempty" json:"arrayWithDefault,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *WithDefaults) ApplyDefaults() {
	if s.StringWithDefault == nil {
		v := "default_value"
		s.StringWithDefault = &v
	}
	if s.IntWithDefault == nil {
		v := 42
		s.IntWithDefault = &v
	}
	if s.BoolWithDefault == nil {
		v := true
		s.BoolWithDefault = &v
	}
}

// #/components/schemas/WithConst
type WithConst struct {
	Version *string `form:"version,omitempty" json:"version,omitempty"`
	Type    *string `form:"type,omitempty" json:"type,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *WithConst) ApplyDefaults() {
}

// #/components/schemas/WithConstraints
type WithConstraints struct {
	BoundedInt          *int     `form:"boundedInt,omitempty" json:"boundedInt,omitempty"`
	ExclusiveBoundedInt *int     `form:"exclusiveBoundedInt,omitempty" json:"exclusiveBoundedInt,omitempty"`
	MultipleOf          *int     `form:"multipleOf,omitempty" json:"multipleOf,omitempty"`
	BoundedString       *string  `form:"boundedString,omitempty" json:"boundedString,omitempty"`
	PatternString       *string  `form:"patternString,omitempty" json:"patternString,omitempty"`
	BoundedArray        []string `form:"boundedArray,omitempty" json:"boundedArray,omitempty"`
	UniqueArray         []string `form:"uniqueArray,omitempty" json:"uniqueArray,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *WithConstraints) ApplyDefaults() {
}

// #/components/schemas/TypeArray31
type TypeArray31 struct {
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *TypeArray31) ApplyDefaults() {
}

// #/components/schemas/PrefixItems31
type PrefixItems31 = []string

// #/components/schemas/EmptySchema
type EmptySchema = any

// #/components/schemas/AnyValue
// Accepts any JSON value
type AnyValue = any

// #/components/schemas/ExplicitAny
type ExplicitAny = Nullable[string]

// #/components/schemas/ComplexNested
type ComplexNested struct {
	Metadata map[string]any          `form:"metadata,omitempty" json:"metadata,omitempty"`
	Items    []ComplexNestedItemItem `form:"items,omitempty" json:"items,omitempty"`
	Config   *ComplexNestedConfig    `form:"config,omitempty" json:"config,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ComplexNested) ApplyDefaults() {
}

// #/components/schemas/ComplexNested/properties/metadata
type ComplexNestedMetadata = map[string]any

// #/components/schemas/ComplexNested/properties/metadata/additionalProperties
type ComplexNestedMetadataValue struct {
	String0         *string
	Int1            *int
	LBracketString2 *[]string
}

func (u ComplexNestedMetadataValue) MarshalJSON() ([]byte, error) {
	if u.String0 != nil {
		return json.Marshal(u.String0)
	}
	if u.Int1 != nil {
		return json.Marshal(u.Int1)
	}
	if u.LBracketString2 != nil {
		return json.Marshal(u.LBracketString2)
	}
	return []byte("null"), nil
}

func (u *ComplexNestedMetadataValue) UnmarshalJSON(data []byte) error {
	var v0 string
	if err := json.Unmarshal(data, &v0); err == nil {
		u.String0 = &v0
	}

	var v1 int
	if err := json.Unmarshal(data, &v1); err == nil {
		u.Int1 = &v1
	}

	var v2 []string
	if err := json.Unmarshal(data, &v2); err == nil {
		u.LBracketString2 = &v2
	}

	return nil
}

// ApplyDefaults sets default values for fields that are nil.
func (u *ComplexNestedMetadataValue) ApplyDefaults() {
}

// #/components/schemas/ComplexNested/properties/items
type ComplexNestedItem = []ComplexNestedItemItem

// #/components/schemas/ComplexNested/properties/items/items
type ComplexNestedItemItem struct {
	ID        *int       `form:"id,omitempty" json:"id,omitempty"`
	CreatedAt *time.Time `form:"createdAt,omitempty" json:"createdAt,omitempty"`
	Tags      []string   `form:"tags,omitempty" json:"tags,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ComplexNestedItemItem) ApplyDefaults() {
}

// #/components/schemas/ComplexNested/properties/config
type ComplexNestedConfig struct {
	ComplexNestedConfigOneOf0 *ComplexNestedConfigOneOf0
	ComplexNestedConfigOneOf1 *ComplexNestedConfigOneOf1
}

func (u ComplexNestedConfig) MarshalJSON() ([]byte, error) {
	var count int
	var data []byte
	var err error

	if u.ComplexNestedConfigOneOf0 != nil {
		count++
		data, err = json.Marshal(u.ComplexNestedConfigOneOf0)
		if err != nil {
			return nil, err
		}
	}
	if u.ComplexNestedConfigOneOf1 != nil {
		count++
		data, err = json.Marshal(u.ComplexNestedConfigOneOf1)
		if err != nil {
			return nil, err
		}
	}

	if count != 1 {
		return nil, fmt.Errorf("ComplexNestedConfig: exactly one member must be set, got %d", count)
	}

	return data, nil
}

func (u *ComplexNestedConfig) UnmarshalJSON(data []byte) error {
	var successCount int

	var v0 ComplexNestedConfigOneOf0
	if err := json.Unmarshal(data, &v0); err == nil {
		u.ComplexNestedConfigOneOf0 = &v0
		successCount++
	}

	var v1 ComplexNestedConfigOneOf1
	if err := json.Unmarshal(data, &v1); err == nil {
		u.ComplexNestedConfigOneOf1 = &v1
		successCount++
	}

	if successCount != 1 {
		return fmt.Errorf("ComplexNestedConfig: expected exactly one type to match, got %d", successCount)
	}

	return nil
}

// ApplyDefaults sets default values for fields that are nil.
func (u *ComplexNestedConfig) ApplyDefaults() {
	if u.ComplexNestedConfigOneOf0 != nil {
		u.ComplexNestedConfigOneOf0.ApplyDefaults()
	}
	if u.ComplexNestedConfigOneOf1 != nil {
		u.ComplexNestedConfigOneOf1.ApplyDefaults()
	}
}

// #/components/schemas/ComplexNested/properties/config/oneOf/0
type ComplexNestedConfigOneOf0 struct {
	Mode  *string `form:"mode,omitempty" json:"mode,omitempty"`
	Value *string `form:"value,omitempty" json:"value,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ComplexNestedConfigOneOf0) ApplyDefaults() {
}

// #/components/schemas/ComplexNested/properties/config/oneOf/1
type ComplexNestedConfigOneOf1 struct {
	Mode    *string           `form:"mode,omitempty" json:"mode,omitempty"`
	Options map[string]string `form:"options,omitempty" json:"options,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ComplexNestedConfigOneOf1) ApplyDefaults() {
}

// #/components/schemas/ComplexNested/properties/config/oneOf/1/properties/options
type ComplexNestedConfigOneOf1Options = map[string]string

// #/components/schemas/StringMap
type StringMap = map[string]string

// #/components/schemas/ObjectMap
type ObjectMap = map[string]any

// #/components/schemas/NestedMap
type NestedMap = map[string]map[string]string

// #/components/schemas/NestedMap/additionalProperties
type NestedMapValue = map[string]string

// #/paths//inline-response/get/responses/200/content/application/json/schema
type GetInlineResponseJSONResponse struct {
	ID   int    `form:"id" json:"id"`
	Name string `form:"name" json:"name"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *GetInlineResponseJSONResponse) ApplyDefaults() {
}

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/+w8W28iOdbv/AqLmbdPNEm6px+QvgdCaIlZAgjI9Eaj2ZVDHYKnq+wal0nCjkbaH7G/",
	"cH/Jyq6CKl/qZtKtntbkifhybj43Hx9gMVAckwHqvn1z+eai2yF0ywYdhAQRIQzQiEUxhx3QhDwBWkMi",
	"0Gqzgwh3EHoCnhBGB6h7+eZC7kUogGTDSSzUsFydIByGKFFbUIyFAE4TtGUcMRyT3oYF8Ai004mx2CUS",
	"bz8hURyC/IjQI4j0A0IsBo4l3EkwkOMrtSyb5JDEjCaQHFcj1L26uOjm/xqkpbtP+wrLNowKoKK4EyEc",
	"xyHZKPT9XxNG9VmU8WeOIvQ9h+0Adb/rb1gUMwpUJP10bdJPSZg//Aob0e1IzgkNCYXekahaEUzU+qXO",
	"Q2tRpFAQU4QgQj+7UMQhhkGGz5rk8NuecAjsbQj1EAmcwxRHYE3EXMpLkKIk8j/ixHAkjlABj8AdKySq",
	"qp2J4IQ+quOMMccRCOBJ/3ep3gv5/x/p5nzuCCzlYoBOK09ICE1HO5aMkOD7nHFb3hpJ+fCW8QiLAdrv",
	"M3lW6NhHkpGjiM0W2dTn9P+2B35YmSglD2qmU60fToo10BMqvOGax6oBHnKOD96gsbEbISIgslSvkr8d",
	"4AC4fvgpHelMe9m1dgbzv30drlCqOCSi98CCQ2YxLHErqZxYpsuvWXDo5DaSjQzqDMfBZzWXbh6rOByG",
	"4foQQ7LMKOj+2Q8o2odChu8CAZUndCvXj9LlVUf0Bc5CZ8aN56X3/Pzck46yt+chUJmnBJ8LsZJljLno",
	"K4QBFrgJqoo4WhX7tiR0RrCSYGEGjQdCMT9YCyIQ2Cb823JMGk/wIvpxiEnLtOeYH+TI5MoMX7rpO/T/",
	"zf+yHYvl5Haynvw0Ruv7xXiFemgYhtmZJR5Q1RbTaR15ciienbb1ZLT9QCAM9KG3V47B9+/MwW3IsLU9",
	"YPuHEMxRuo8egJujqaDN0QfGQgsqFuAaW5PIGpcpkzkGESYW0D0n5tCOJUIGeov/+OmdY+y9RfvBpjO1",
	"RnM0xknyzLhGqcslHE/IzhnNTCk/uPq1ua9Qu4owsnNuCeP9u9N4rhY2jFQPHCDUptN4QYlawEh3nSYK",
	"OlcLpKCJtcn5ST/tlXIKMM35OKpti4xf7tEAnHS8JZCeIIUr18kqfC4f8i83oRYQ1Kachszg2pDAyWlU",
	"M84WMI77ci0/WnMLIHJPEcB7DwDvcx06tFcMuScHkDuVNiD0xEDzQS3AHPfpIWiu0gAcVoSgvxzcXw7u",
	"W3Rw3jnh7G46HV5Ps5TQNwmc7cMQP4TgmQTSbPvKKnlkE8V6Tj46r7NsHa4l1I5eIHTcanqoK2F0LYgT",
	"/WLhAucqD5bCS1mpA+m4xlkQy+91rqqkWY/Mj9LTmX69Is90ex4DHS4m6O2byxNodb1DTwQjRmG+7WN6",
	"mG/Rf//9HyR2gBgND+gZH5BgKMKfIAOEEYctcKAbCBQ1ObiE0A2gA9ujDaaUCbRh0QOhGZ5nInbpBlUP",
	"TN4YJrSdSyI8TaixTdgax4poj3D9Lr69jOxKbTc17PPSYAp5KM/4ywsZF9G+PoM+IWC4XA7vvV2/qoir",
	"9Kulp0htX223w51ZKXfUyZ1xkVBxLkTTiaSM+ENtf7jpE9/8TLyllb/yup/rvavqrcv9zuU8GAqJgOBc",
	"bs55QDnapJsGw7JsRI5A21QpFbCPROxGjCaCY5IV9Kp5iwidKATosjiKX46jFy1I8XYO8+sfx6O1t3co",
	"KnjbymBlUarB7cnUTkeuo5SyljoXAWwvgNvQLXMrMzZCqb7/jGL9Ew739dV6//hwczNZT+az4RQtlvPF",
	"eLme+N8UhkFA0rC/4CxOhvRQIXisLc7YT5/lXMBmjEJraFscnroYXEL+RNkzrVYjgwwZDIO2dHTcuuyC",
	"X6uv1QhaPeFZyNVTv/zQtshSa7BNxHKuKo9nd7f+vkwhH9N9pPOueXsoTEsvpmzz0hy4MgfepigmqURs",
	"HLqoTCRF+EXQGdT0POXJ2YAbpGlY7JMGBQmdqOyNAWhgX/DwRpAnMAalNoYgIC+HxJwwTsShSZ3MhfzS",
	"+P/K+P8kc5ltSclMaKZ5h9YVRAlidY6kGDUHttszXPZ0Ov+AemhCd8CJwHQD/ZE090SZmK8FXOMEbON8",
	"NQ+A0IYDlmmi8CrEqcnxiwAamFEdh2Hx2lV95dLZ7HbMC5cVoN39aFbLmXdhpjhRfPCuLebcAMQFHfCS",
	"hi7QBtIoYxNeBMf1NA8lcaoTJFYX9eSVz7D9faw1pxHwR7s7US9g57ymDmhOw0Mppy3xbwlPRMOuspag",
	"E9gwWsKalrR4ua3ZvXJbd5QwilRRwTvPpIf5dsFJRGSsyXVIL7/0qqWiZ2Fya6oa5eB8lKuNGueU3JKX",
	"XMWasvUFdD+NhU10X9J8LMj5nU+x8pUnOdnRe0Vy6yrlrNeVOudeRbmk5xSCvPTPXcXIYjnAuN1bNPlV",
	"ED00z6uCMBsro74hMnBFhMoIn5q4t3WrCvmq8B0Aq3L8hUxRESKVrsAd4140jXBjUm7Y43Fp4MJ70u3D",
	"LG0XByGdaRXJtziOCw82XxvleflLI1PljDIJbEAYQgF7rKRLLR3htoUqk8YeioA9VziZbENtjivB1C56",
	"3pHkE/Ap0EexK32FT7NB9ng2aw+Yf3oF1iSY2kUCk7AJX0qjJ1rcsfS3ZRRjKsEefp4cKgV+3SCJUpzZ",
	"WUwJdyV0GY0YzjiUR88Mpd89uMEV7wlzgul5D4+GXbdwOhWOp8Zt+oS+0fz2ejIb38gPi/lKVVHP6LNN",
	"3bb2OvxKd6I/xQmcAtewyLRlC4ZI/MVSadv1NXlLzRv20G8YTWREw91vkKmHMxLJ5Xh0t1yd2td9DWnN",
	"AWYsgHNvBk6ONzsSBhzoq78UH6nO5Dcl9BMEU5KI12PFej+DF+2oq8jT6cmIXMJmzxPyBJrLahe8GgfV",
	"9IG5zTdtdPLOUszhTf/jcrIeo/lseu+rmEvAwUdOhFYKavtYWuzsPzNSS0w4UMToX4U7wm9QpH0+8aOD",
	"qH+b9TmIm/GH4d10vULDmYy5s9Xa9yzU/Qi2eB8Kv76WAoAGYgqylaibffqnstFiS4iohGif3Qnkuyut",
	"r7YSjNldWwCjHd+po6EUkm8DTwHjz7/kZ6E6J9q6ueyXB+rFf4xOp18ocDeG1OzekhcIuudki7PVejmc",
	"zPzbLUqaTBoK7IHtaQCBq9HSoWARoSTaRwN0obenpIOXF/kwvGzCvXS0160QnLbdujDlsy6UUfZ+oCdN",
	"pazkq9EPpjhKOlltPYgIzW6rZsfOcfjqhx8KTlT9zEVj6Nn6Aer+42fc+9cv//d916S0YXfVqzYWnZrf",
	"KfltDw0pSBdn6DTH8jk7mRbj2bHxd7UYjyYfJiPvHPIQp7y+vdRsrFPaq220jzmbRmtj4oLDlqTHZCDW",
	"RBzny1o/dZRVCZyH80pNGbeL9T3qo+HsXmX2vocyjmJxSH93ZoB+/+P0yvBTMd3Vvi883GwgFgnC9IB+",
	"XM1naWZ8fEeOQ7IhwuxQ6pR2r/fsSostVTPCmq2G5YpzThViMR3/Hc3Gq/X4Bq3Wy7vR+m7pf4MaqVaN",
	"l5mWcTeMMa6vgJdk+tUNQSWPM5XPM9UPNPms3f1Z2mpa3olsrm6cFznu+ufc9mvu+3W/gSPwY1L1WzZu",
	"WVXKq/z2zOiWPNaWBj2rF1HhpuxRukh/cqrr2X35NXCAgydMN/nvipgV6QrlLlGdJkb6usHidrg4s4Hv",
	"FsdnNmcWeUgL5+fAbNmPmXrd85kwTrTuHDXO/xcAAP//5miNURBOAAA=",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}

const DateFormat = "2006-01-02"

type Date struct {
	time.Time
}

func (d Date) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.Format(DateFormat))
}

func (d *Date) UnmarshalJSON(data []byte) error {
	var dateStr string
	err := json.Unmarshal(data, &dateStr)
	if err != nil {
		return err
	}
	parsed, err := time.Parse(DateFormat, dateStr)
	if err != nil {
		return err
	}
	d.Time = parsed
	return nil
}

func (d Date) String() string {
	return d.Format(DateFormat)
}

func (d *Date) UnmarshalText(data []byte) error {
	parsed, err := time.Parse(DateFormat, string(data))
	if err != nil {
		return err
	}
	d.Time = parsed
	return nil
}

// MarshalText implements encoding.TextMarshaler for Date.
func (d Date) MarshalText() ([]byte, error) {
	return []byte(d.Format(DateFormat)), nil
}

// Format returns the date formatted according to layout.
func (d Date) Format(layout string) string {
	return d.Time.Format(layout)
}

const (
	emailRegexString = "^(?:(?:(?:(?:[a-zA-Z]|\\d|[!#\\$%&'\\*\\+\\-\\/=\\?\\^_`{\\|}~]|[\\x{00A0}-\\x{D7FF}\\x{F900}-\\x{FDCF}\\x{FDF0}-\\x{FFEF}])+(?:\\.([a-zA-Z]|\\d|[!#\\$%&'\\*\\+\\-\\/=\\?\\^_`{\\|}~]|[\\x{00A0}-\\x{D7FF}\\x{F900}-\\x{FDCF}\\x{FDF0}-\\x{FFEF}])+)*)|(?:(?:\\x22)(?:(?:(?:(?:\\x20|\\x09)*(?:\\x0d\\x0a))?(?:\\x20|\\x09)+)?(?:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x7f]|\\x21|[\\x23-\\x5b]|[\\x5d-\\x7e]|[\\x{00A0}-\\x{D7FF}\\x{F900}-\\x{FDCF}\\x{FDF0}-\\x{FFEF}])|(?:(?:[\\x01-\\x09\\x0b\\x0c\\x0d-\\x7f]|[\\x{00A0}-\\x{D7FF}\\x{F900}-\\x{FDCF}\\x{FDF0}-\\x{FFEF}]))))*(?:(?:(?:\\x20|\\x09)*(?:\\x0d\\x0a))?(\\x20|\\x09)+)?(?:\\x22))))@(?:(?:(?:[a-zA-Z]|\\d|[\\x{00A0}-\\x{D7FF}\\x{F900}-\\x{FDCF}\\x{FDF0}-\\x{FFEF}])|(?:(?:[a-zA-Z]|\\d|[\\x{00A0}-\\x{D7FF}\\x{F900}-\\x{FDCF}\\x{FDF0}-\\x{FFEF}])(?:[a-zA-Z]|\\d|-|\\.|~|[\\x{00A0}-\\x{D7FF}\\x{F900}-\\x{FDCF}\\x{FDF0}-\\x{FFEF}])*(?:[a-zA-Z]|\\d|[\\x{00A0}-\\x{D7FF}\\x{F900}-\\x{FDCF}\\x{FDF0}-\\x{FFEF}])))\\.)+(?:(?:[a-zA-Z]|[\\x{00A0}-\\x{D7FF}\\x{F900}-\\x{FDCF}\\x{FDF0}-\\x{FFEF}])|(?:(?:[a-zA-Z]|[\\x{00A0}-\\x{D7FF}\\x{F900}-\\x{FDCF}\\x{FDF0}-\\x{FFEF}])(?:[a-zA-Z]|\\d|-|\\.|~|[\\x{00A0}-\\x{D7FF}\\x{F900}-\\x{FDCF}\\x{FDF0}-\\x{FFEF}])*(?:[a-zA-Z]|[\\x{00A0}-\\x{D7FF}\\x{F900}-\\x{FDCF}\\x{FDF0}-\\x{FFEF}])))\\.?$"
)

var (
	emailRegex = regexp.MustCompile(emailRegexString)
)

// ErrValidationEmail is the sentinel error returned when an email fails validation
var ErrValidationEmail = errors.New("email: failed to pass regex validation")

// Email represents an email address.
// It is a string type that must pass regex validation before being marshalled
// to JSON or unmarshalled from JSON.
type Email string

func (e Email) MarshalJSON() ([]byte, error) {
	if !emailRegex.MatchString(string(e)) {
		return nil, ErrValidationEmail
	}

	return json.Marshal(string(e))
}

func (e *Email) UnmarshalJSON(data []byte) error {
	if e == nil {
		return nil
	}

	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	*e = Email(s)
	if !emailRegex.MatchString(s) {
		return ErrValidationEmail
	}

	return nil
}

type File struct {
	multipart *multipart.FileHeader
	data      []byte
	filename  string
}

func (file *File) InitFromMultipart(header *multipart.FileHeader) {
	file.multipart = header
	file.data = nil
	file.filename = ""
}

func (file *File) InitFromBytes(data []byte, filename string) {
	file.data = data
	file.filename = filename
	file.multipart = nil
}

func (file File) MarshalJSON() ([]byte, error) {
	b, err := file.Bytes()
	if err != nil {
		return nil, err
	}
	return json.Marshal(b)
}

func (file *File) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &file.data)
}

func (file File) Bytes() ([]byte, error) {
	if file.multipart != nil {
		f, err := file.multipart.Open()
		if err != nil {
			return nil, err
		}
		defer func() { _ = f.Close() }()
		return io.ReadAll(f)
	}
	return file.data, nil
}

func (file File) Reader() (io.ReadCloser, error) {
	if file.multipart != nil {
		return file.multipart.Open()
	}
	return io.NopCloser(bytes.NewReader(file.data)), nil
}

func (file File) Filename() string {
	if file.multipart != nil {
		return file.multipart.Filename
	}
	return file.filename
}

func (file File) FileSize() int64 {
	if file.multipart != nil {
		return file.multipart.Size
	}
	return int64(len(file.data))
}

// Nullable is a generic type that can distinguish between:
// - Field not provided (unspecified)
// - Field explicitly set to null
// - Field has a value
//
// This is implemented as a map[bool]T where:
// - Empty map: unspecified
// - map[false]T: explicitly null
// - map[true]T: has a value
type Nullable[T any] map[bool]T

// NewNullableWithValue creates a Nullable with the given value.
func NewNullableWithValue[T any](value T) Nullable[T] {
	return Nullable[T]{true: value}
}

// NewNullNullable creates a Nullable that is explicitly null.
func NewNullNullable[T any]() Nullable[T] {
	return Nullable[T]{false: *new(T)}
}

// Get returns the value if set, or an error if null or unspecified.
func (n Nullable[T]) Get() (T, error) {
	if v, ok := n[true]; ok {
		return v, nil
	}
	var zero T
	if n.IsNull() {
		return zero, ErrNullableIsNull
	}
	return zero, ErrNullableNotSpecified
}

// MustGet returns the value or panics if null or unspecified.
func (n Nullable[T]) MustGet() T {
	v, err := n.Get()
	if err != nil {
		panic(err)
	}
	return v
}

// Set assigns a value.
func (n *Nullable[T]) Set(value T) {
	*n = Nullable[T]{true: value}
}

// SetNull marks the field as explicitly null.
func (n *Nullable[T]) SetNull() {
	*n = Nullable[T]{false: *new(T)}
}

// SetUnspecified clears the field (as if it was never set).
func (n *Nullable[T]) SetUnspecified() {
	*n = nil
}

// IsNull returns true if the field is explicitly null.
func (n Nullable[T]) IsNull() bool {
	if n == nil {
		return false
	}
	_, ok := n[false]
	return ok
}

// IsSpecified returns true if the field was provided (either null or a value).
func (n Nullable[T]) IsSpecified() bool {
	return len(n) > 0
}

// MarshalJSON implements json.Marshaler.
func (n Nullable[T]) MarshalJSON() ([]byte, error) {
	if n.IsNull() {
		return []byte("null"), nil
	}
	if v, ok := n[true]; ok {
		return json.Marshal(v)
	}
	// Unspecified - this shouldn't be called if omitempty is used correctly
	return []byte("null"), nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (n *Nullable[T]) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		n.SetNull()
		return nil
	}
	var v T
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	n.Set(v)
	return nil
}

// ErrNullableIsNull is returned when trying to get a value from a null Nullable.
var ErrNullableIsNull = errors.New("nullable value is null")

// ErrNullableNotSpecified is returned when trying to get a value from an unspecified Nullable.
var ErrNullableNotSpecified = errors.New("nullable value is not specified")

type UUID = uuid.UUID
