// Code generated by oapi-codegen; DO NOT EDIT.

package petstore

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"strings"
	"sync"
)

// #/components/schemas/Pet
type Pet struct {
	// Name of the pet
	Name string `form:"name" json:"name"`
	// Type of the pet
	Tag *string `form:"tag,omitempty" json:"tag,omitempty"`
	// Unique id of the pet
	ID int64 `form:"id" json:"id"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Pet) ApplyDefaults() {
}

// #/components/schemas/NewPet
type NewPet struct {
	// Name of the pet
	Name string `form:"name" json:"name"`
	// Type of the pet
	Tag *string `form:"tag,omitempty" json:"tag,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *NewPet) ApplyDefaults() {
}

// #/components/schemas/Error
type Error struct {
	// Error code
	Code int32 `form:"code" json:"code"`
	// Error message
	Message string `form:"message" json:"message"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Error) ApplyDefaults() {
}

// #/paths//pets/get/responses/200/content/application/json/schema
type FindPetsJSONResponse = []Pet

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/+xXXW9byQ19168gtgXyoly5yaIPemo2TgED3cStd/tOz6UkLubLQ44coe1/Lzj3Srqy",
	"ZG+CYvuF9YMNz3A4hzyHHN6UKWLmJXzztrvqrr6ZcVyl5QxgS0U4xSX8ztZnAMrqaQl3j7heU4FbUtFU",
	"aAbQk7jCWZv5OxAM2RO8u70B3aBCFRJAyOMBQAGMQJ8HM03QU0hRtKASrAi1FhLgCLoh+JQpmqe33RVI",
	"Jscrdmg3GSIqQT6t7qhs2dESNqpZlouFDBA7TotmspgBuBQVnVpkABHDJBJz/wNhaFsUkP0SMLMShj8c",
	"XbXdWvyla2YAnh1Foan/dxndhuBNy96Ts4+Pjx22/S6V9WI8LYs/3bz/8PHuw+s33VW30eBnQsWYML+v",
	"T13s89lNwsXMs4y6afbNYgC0pjFyAKkhYNkt4S+ktUQB9L5xM+6fkPn3cRHOrGFVUmgMyU6UwkC1/V+F",
	"CmyMZOdIBDQdnHzEAEK9kdFzoKg1AIl28D2So4gCSiGnAoJrVmUBwcwU5xDJQdmk6KqAUJgYsAIG0g7e",
	"USSMgArrglvuEbCuK80BHTC66rkd7eB9LXjPWguknhP4VCjMIZWIhYDWpECeRnSR3BxcLVIFuAdPTqt0",
	"cF1ZIDBoLZllDrn6LUcsdheVZLHPQTk67mtU2GLhKvBTFU0d3ETYoIONgUARguxRCaFnpzVYOm6ikikT",
	"FbDnzOI4rgGjWjTH2D2vq8dD5HmDhbTgPolmDyF5EmUCDplKz5apv/IWwxAQen6oGKBntMwUFHiw2Lbk",
	"WSGmCJqKpmIp4RXF/nB7B7cFSSiqwaTI4QigloiwTb5qRoUtRYpogIfk2q+AtZiPm3j0vKIyZn2Fjj3L",
	"ySXtBvs1P/LrQFKPnozYfm55dFRQLTD728FdlUyxZ8uyRxNPn3wqc1OgkFMTdYuyScWinsOWNuyqR+Co",
	"VPoawPM9ldTB96ncM1BlCamf0mDbTdgeHUfGbnaQ/B31jY8qsCKToE/3qbRjlI66KVVLDV2rkIDN7UgB",
	"i58D1ZOaGYgHX02NptEObjco5P1QHpnKeLwlu5FMCiusju/rkHbc32N20/Nb8iOBvKVScH56tVULcD8/",
	"lGPk+00HPypk8p6ikjxUgpykktXTvpS6lgrc14KV3j6je0/7sFo+5w3IQRyxRgdaWNRigS0rUgd/rOII",
	"SFtP6CsfasH6hTjyVLjBGVS8PxBMMxWbhFwNghECri1k8iNbHfy5DkdD8sbbwB7VQUFHKPNDCwKszkpl",
	"sBxFOoQ9SmRsNYeaNMkYwcBxfoQylm9k4T1gMQyOtfZsUEUQqu7VNhI53HSStHZfB7dTYlrmRoy5kHIN",
	"k/41iKbOJyq3BtyNek7Z6opTvOmXsOLY3x4fjozFsjA+VsPP6/EpVFzLYRGA4xIeKpXdZO3k3TF7mwxW",
	"7JUK3E8NCz1ULmQA0AtNdkR3NqGsUgnTVbehgMvJCoDuMi0BS8HdyTorBTk13RuLFo7rs8g8B9avCS3g",
	"Zw72stRwTwXSCgpJ9driLe2V/bJgnw2Lh9fjZMdygtr23r6Z7X1LtjY4CfjVm6urV8vnoGfSw6GJjY1W",
	"FPUUCubsx0lt8ZOk+DSpl+C/xMyz7NjPbwutlvDqNwuXQk6RospiuEAWt6SvZsdwVli9PhthjfQ527tg",
	"D0hJ5ZeK8iXAH+ziAXJOcj63vS+E2ibqSI/GyaXB7cxoP08PIyNc1wG4mdhI7n16pP5SlWNvRT47ypFE",
	"v0v9bjm7mMFbUhMy9r39Odw4Oxe0lnpcvpDdl3N7ObMv5fUjPU608F8p/v9PHbfvkMXfuP/HF3yMtDzf",
	"7+Dm+pKsn5ihPaA2vYFwXHs6nrr0UH23O2y/9FZx/6Sd2wfVc4m+ubYOngfRr0jd5mLzPtH6v9C7f//t",
	"r/L997fhnjwpnWn2ui3/rGb7g9ko0hPpWoe8uQapFsLlDjw4ODbhX0a8wy3/SfV++7J6B4D9/6KIjjt2",
	"fNwcPN0emyF6/2k1pfTLXzOzPvB1gvD1qSRyMWkp05M5ivvLU+8lRi9zepGDH2P7WuPehGZSt3GlHRjw",
	"L2dPtPZE0LPnUTe9z35mSn8C5yMGmiI5nMX117r6YZfpLKhG90sxudTT5N9AIrh+KUo7cA7tnJVL8/0Z",
	"5gbvFMOI4GujHzzt4f8zAAD//6ZcwVZEFgAA",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}

// MarshalText implements encoding.TextMarshaler for Date.

// Format returns the date formatted according to layout.

// ErrValidationEmail is the sentinel error returned when an email fails validation

// Email represents an email address.
// It is a string type that must pass regex validation before being marshalled
// to JSON or unmarshalled from JSON.

// Nullable is a generic type that can distinguish between:
// - Field not provided (unspecified)
// - Field explicitly set to null
// - Field has a value
//
// This is implemented as a map[bool]T where:
// - Empty map: unspecified
// - map[false]T: explicitly null
// - map[true]T: has a value

// NewNullableWithValue creates a Nullable with the given value.

// NewNullNullable creates a Nullable that is explicitly null.

// Get returns the value if set, or an error if null or unspecified.

// MustGet returns the value or panics if null or unspecified.

// Set assigns a value.

// SetNull marks the field as explicitly null.

// SetUnspecified clears the field (as if it was never set).

// IsNull returns true if the field is explicitly null.

// IsSpecified returns true if the field was provided (either null or a value).

// MarshalJSON implements json.Marshaler.

// Unspecified - this shouldn't be called if omitempty is used correctly

// UnmarshalJSON implements json.Unmarshaler.

// ErrNullableIsNull is returned when trying to get a value from a null Nullable.

// ErrNullableNotSpecified is returned when trying to get a value from an unspecified Nullable.

// BindParameter binds a styled parameter from a single string value to a Go
// object. This is the entry point for path, header, and cookie parameters
// where the HTTP framework has already extracted the raw value.
//
// The Style field in opts selects how the value is split into parts (simple,
// label, matrix, form). If Style is empty, "simple" is assumed.

// Unescape based on parameter location.

// If the destination implements encoding.TextUnmarshaler, use it directly.

// Primitive types: only label and matrix need prefix stripping via
// splitStyledParameter. Simple and form can bind the raw value directly —
// splitting on commas would incorrectly reject values that contain commas.

// BindQueryParameter binds a query parameter from pre-parsed url.Values.
// The Style field in opts selects parsing behavior. If Style is empty, "form"
// is assumed. Supports form, spaceDelimited, pipeDelimited, and deepObject.

// Destination value management for optional (pointer) parameters.

// Exploded: each value is a separate key=value pair.
// spaceDelimited and pipeDelimited with explode=true are
// serialized identically to form explode=true.

// Non-exploded: single value, delimiter-separated.

// Primitive types: use the raw value as-is without splitting.

// Some struct types (e.g. Date, time.Time) are scalar values
// that should be bound from a single string, not decomposed as
// key-value objects.

// BindRawQueryParameter works like BindQueryParameter but operates on the raw
// (undecoded) query string. This correctly handles form/explode=false
// parameters whose values contain literal commas encoded as %2C — something
// that BindQueryParameter cannot do because url.Values has already decoded
// %2C to ',' before we can split on the delimiter comma.

// For explode, url.ParseQuery is fine — no delimiter commas to
// confuse with literal commas.

// explode=false — use findRawQueryParam to get the still-encoded
// value, split on the style-specific delimiter, then URL-decode
// each resulting part individually.

// Primitive types: decode as-is without splitting.

// ---------------------------------------------------------------------------
// Deep object internals
// ---------------------------------------------------------------------------

// unmarshalDeepObject is the internal implementation of deep object
// unmarshaling that supports the required parameter.

// UnmarshalDeepObject unmarshals deepObject-style query parameters to a
// destination. Exported for use by generated code and tests.

// ---------------------------------------------------------------------------
// Exploded object binding
// ---------------------------------------------------------------------------

// bindParamsToExplodedObject reflects the destination structure and pulls the
// value for each settable field from the given query parameters. Returns
// whether any fields were bound.

// indirectBinder checks if dest implements Binder and returns reflect values.

// ParamLocation indicates where a parameter is located in an HTTP request.

// Binder is an interface for types that can bind themselves from a string value.

// MissingRequiredParameterError is returned when a required parameter is not
// present in the request. Upper layers can use errors.As to detect this and
// produce an appropriate HTTP error response.

// primitiveToString converts a primitive value to a string representation.
// It handles basic Go types, time.Time, Date, and types that implement
// json.Marshaler or fmt.Stringer.

// Check for known types first (time, date, uuid)

// Dereference pointers for optional values

// Check if it's a UUID

// Check if it implements json.Marshaler

// marshalKnownTypes checks for special types (time.Time, Date, UUID) and marshals them.

// escapeParameterName escapes a parameter name for use in query strings and
// paths. This ensures characters like [] in parameter names (e.g. user_ids[])
// are properly percent-encoded per RFC 3986.

// Parameter names should always be encoded regardless of allowReserved,
// which only applies to values per the OpenAPI spec.

// escapeParameterString escapes a parameter value based on its location.
// Query and path parameters need URL escaping; headers and cookies do not.
// When allowReserved is true and the location is query, RFC 3986 reserved
// characters are left unencoded per the OpenAPI allowReserved specification.

// escapeQueryAllowReserved percent-encodes a query parameter value while
// leaving RFC 3986 reserved characters (:/?#[]@!$&'()*+,;=) unencoded, as
// specified by OpenAPI's allowReserved parameter option.

// isUnreserved reports whether the byte is an RFC 3986 unreserved character:
// ALPHA / DIGIT / "-" / "." / "_" / "~"

// unescapeParameterString unescapes a parameter value based on its location.

// sortedKeys returns the keys of a map in sorted order.

// BindStringToObject binds a string value to a destination object.
// It handles primitives, encoding.TextUnmarshaler, and the Binder interface.

// Check for TextUnmarshaler

// Check for Binder interface

// Try JSON unmarshal as a fallback

// bindSplitPartsToDestinationArray binds a slice of string parts to a destination slice.

// bindSplitPartsToDestinationStruct binds string parts to a destination struct via JSON.

// splitStyledParameter splits a styled parameter string value into parts based
// on the OpenAPI style. The object flag indicates whether the destination is a
// struct/map (affects matrix explode handling).

// In the simple case, we always split on comma

// Exploded: .a.b.c or .key=value.key=value

// Unexploded: .a,b,c

// Exploded: ;a;b;c or ;key=value;key=value

// Unexploded: ;paramName=a,b,c

// findRawQueryParam extracts values for a named parameter from a raw
// (undecoded) query string. The parameter key is decoded for comparison
// purposes, but the returned values remain in their original encoded form.

// Skip malformed keys.

// isByteSlice reports whether t is []byte (or equivalently []uint8).

// base64Decode decodes s as base64.
//
// Per OpenAPI 3.0, format: byte uses RFC 4648 Section 4 (standard alphabet,
// padded). We use padding presence to select the right decoder, rather than
// blindly cascading (which can produce corrupt output when RawStdEncoding
// silently accepts padded input and treats '=' as data).

// structToFieldDict converts a struct to a map of field names to string values.

// Skip nil optional fields

// ParameterOptions carries OpenAPI parameter metadata to bind and style
// functions so they can handle style dispatch, explode, required,
// type-aware coercions, and location-aware escaping from a single
// uniform call site. All fields have sensible zero-value defaults.

// OpenAPI style: "simple", "form", "label", "matrix", "deepObject", "pipeDelimited", "spaceDelimited"
// Where the parameter appears: query, path, header, cookie

// OpenAPI type: "string", "integer", "array", "object"
// OpenAPI format: "int32", "date-time", etc.
// When true, reserved characters in query values are not percent-encoded

// StyleParameter serializes a Go value into an OpenAPI-styled parameter string.
// This is the entry point for client-side parameter serialization. The Style
// field in opts selects the serialization format. If Style is empty, "simple"
// is assumed.

// Dereference pointers; error on nil.

// If the value implements encoding.TextMarshaler, use it — but not for
// time.Time or Date which have their own formatting logic.

// ---------------------------------------------------------------------------
// Internal style helpers
// ---------------------------------------------------------------------------

// If input implements json.Marshaler (e.g. objects with additional properties
// or anyOf), marshal to JSON and re-style the generic structure.

// Build a dictionary of the struct's fields.

// Skip nil optional fields.

// ---------------------------------------------------------------------------
// Deep object marshaling
// ---------------------------------------------------------------------------

// MarshalDeepObject marshals an object to deepObject style query parameters.

// JSONMerge merges two JSON-encoded objects. Fields from patch override
// fields in base. Both arguments must be valid JSON objects (or nil/null).

// MarshalForm marshals a struct into url.Values using the struct's json tags
// as field names. It handles nested structs, slices, pointers, and
// AdditionalProperties maps.
