// Code generated by oapi-codegen; DO NOT EDIT.

package output

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"
	"sync"

	oapiCodegenHelpersPkg "github.com/oapi-codegen/oapi-codegen-exp/runtime/helpers"
)

// #/components/schemas/Registration
type Registration struct {
	State *RegistrationState `form:"state,omitempty" json:"state,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Registration) ApplyDefaults() {
}

// #/components/schemas/Registration/properties/state

type RegistrationState struct {
	union json.RawMessage
}

// AsRegistrationStateOneOf0 returns the union data inside the RegistrationState as a RegistrationStateOneOf0.
func (t RegistrationState) AsRegistrationStateOneOf0() (RegistrationStateOneOf0, error) {
	var body RegistrationStateOneOf0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRegistrationStateOneOf0 overwrites any union data inside the RegistrationState as the provided RegistrationStateOneOf0.
func (t *RegistrationState) FromRegistrationStateOneOf0(v RegistrationStateOneOf0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRegistrationStateOneOf0 performs a merge with any union data inside the RegistrationState, using the provided RegistrationStateOneOf0.
func (t *RegistrationState) MergeRegistrationStateOneOf0(v RegistrationStateOneOf0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRegistrationStateOneOf1 returns the union data inside the RegistrationState as a RegistrationStateOneOf1.
func (t RegistrationState) AsRegistrationStateOneOf1() (RegistrationStateOneOf1, error) {
	var body RegistrationStateOneOf1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRegistrationStateOneOf1 overwrites any union data inside the RegistrationState as the provided RegistrationStateOneOf1.
func (t *RegistrationState) FromRegistrationStateOneOf1(v RegistrationStateOneOf1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRegistrationStateOneOf1 performs a merge with any union data inside the RegistrationState, using the provided RegistrationStateOneOf1.
func (t *RegistrationState) MergeRegistrationStateOneOf1(v RegistrationStateOneOf1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRegistrationStateOneOf2 returns the union data inside the RegistrationState as a RegistrationStateOneOf2.
func (t RegistrationState) AsRegistrationStateOneOf2() (RegistrationStateOneOf2, error) {
	var body RegistrationStateOneOf2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRegistrationStateOneOf2 overwrites any union data inside the RegistrationState as the provided RegistrationStateOneOf2.
func (t *RegistrationState) FromRegistrationStateOneOf2(v RegistrationStateOneOf2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRegistrationStateOneOf2 performs a merge with any union data inside the RegistrationState, using the provided RegistrationStateOneOf2.
func (t *RegistrationState) MergeRegistrationStateOneOf2(v RegistrationStateOneOf2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRegistrationStateOneOf3 returns the union data inside the RegistrationState as a RegistrationStateOneOf3.
func (t RegistrationState) AsRegistrationStateOneOf3() (RegistrationStateOneOf3, error) {
	var body RegistrationStateOneOf3
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRegistrationStateOneOf3 overwrites any union data inside the RegistrationState as the provided RegistrationStateOneOf3.
func (t *RegistrationState) FromRegistrationStateOneOf3(v RegistrationStateOneOf3) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRegistrationStateOneOf3 performs a merge with any union data inside the RegistrationState, using the provided RegistrationStateOneOf3.
func (t *RegistrationState) MergeRegistrationStateOneOf3(v RegistrationStateOneOf3) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RegistrationState) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RegistrationState) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *RegistrationState) ApplyDefaults() {
}

// #/components/schemas/Registration/properties/state/oneOf/0
type RegistrationStateOneOf0 string

const (
	Undefined RegistrationStateOneOf0 = "undefined"
)

// #/components/schemas/Registration/properties/state/oneOf/1
type RegistrationStateOneOf1 string

const (
	Registered RegistrationStateOneOf1 = "registered"
)

// #/components/schemas/Registration/properties/state/oneOf/2
type RegistrationStateOneOf2 string

const (
	Pending RegistrationStateOneOf2 = "pending"
)

// #/components/schemas/Registration/properties/state/oneOf/3
type RegistrationStateOneOf3 string

const (
	Active RegistrationStateOneOf3 = "active"
)

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/6yQzY7UMBCE736KknJlMrPsibwBJySExNmb1CQNjm2527MaId4dOeFnZw4Iob25q7vr",
	"a1eH96qVeDi9fTcgRX44Q61InMFYV8XZS2iVJcyMLN6IXFJmCVfXYTHLOhyPs9hSn/oxrcfksxzGNHFm",
	"vC2kofTYWK5zHT4vjKja7Hfys9iCtQaTHIjWCDxcfKi8OeqN62ALfx80oRGgS6qhvdcsgfBxwnMqXzGm",
	"UjhauPYuZUafZcBjf+ofncRzGhxgYoHDiyjwiWoOuLCopDjgoT/1J5e9LTrg23fXICkymrZ9HReufnsC",
	"HzmLWvHWFjcFsGvmgPT0haP9lPYQTai/hgA1b/xTYo/lpQActgxutV2vceJZIqe73g7fA/xHq7L9geU1",
	"vDLjdD/9X0Z+NLnwbz4/AgAA//+mSD78zgIAAA==",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}
