// Code generated by oapi-codegen; DO NOT EDIT.

package server

import (
	"encoding"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"reflect"
	"strconv"
	"strings"
	"time"

	"github.com/labstack/echo/v5"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Returns all pets
	// (GET /pets)
	FindPets(ctx *echo.Context, params FindPetsParams) error
	// Creates a new pet
	// (POST /pets)
	AddPet(ctx *echo.Context) error
	// Deletes a pet by ID
	// (DELETE /pets/{id})
	DeletePet(ctx *echo.Context, id int64) error
	// Returns a pet by ID
	// (GET /pets/{id})
	FindPetByID(ctx *echo.Context, id int64) error
}

// FindPetsParams defines parameters for FindPets.
type FindPetsParams struct {
	// tags (optional)
	Tags *[]string `form:"tags" json:"tags"`
	// limit (optional)
	Limit *int32 `form:"limit" json:"limit"`
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// FindPets converts echo context to params.
func (w *ServerInterfaceWrapper) FindPets(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params FindPetsParams

	// ------------- Optional query parameter "tags" -------------
	err = BindFormQueryParam("tags", ctx.QueryParams(), &params.Tags, ParameterOptions{ParamLocation: ParamLocationQuery, Explode: true, Required: false, Type: "array", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tags: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------
	err = BindFormQueryParam("limit", ctx.QueryParams(), &params.Limit, ParameterOptions{ParamLocation: ParamLocationQuery, Explode: true, Required: false, Type: "integer", Format: "int32"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.FindPets(ctx, params)
	return err
}

// AddPet converts echo context to params.
func (w *ServerInterfaceWrapper) AddPet(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AddPet(ctx)
	return err
}

// DeletePet converts echo context to params.
func (w *ServerInterfaceWrapper) DeletePet(ctx *echo.Context) error {
	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = BindSimpleParam("id", ctx.Param("id"), &id, ParameterOptions{ParamLocation: ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeletePet(ctx, id)
	return err
}

// FindPetByID converts echo context to params.
func (w *ServerInterfaceWrapper) FindPetByID(ctx *echo.Context) error {
	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = BindSimpleParam("id", ctx.Param("id"), &id, ParameterOptions{ParamLocation: ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.FindPetByID(ctx, id)
	return err
}

// EchoRouter is an interface for echo.Echo and echo.Group.
type EchoRouter interface {
	Add(method string, path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// RegisterHandlersWithBaseURL adds each server route to the EchoRouter with a base URL prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/pets", wrapper.FindPets)
	router.POST(baseURL+"/pets", wrapper.AddPet)
	router.DELETE(baseURL+"/pets/:id", wrapper.DeletePet)
	router.GET(baseURL+"/pets/:id", wrapper.FindPetByID)
}

// UnescapedCookieParamError is returned when a cookie parameter cannot be unescaped.
type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

// UnmarshalingParamError is returned when a parameter cannot be unmarshaled.
type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

// RequiredParamError is returned when a required parameter is missing.
type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

// RequiredHeaderError is returned when a required header is missing.
type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

// InvalidParamFormatError is returned when a parameter has an invalid format.
type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

// TooManyValuesForParamError is returned when a parameter has too many values.
type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

const DateFormat = "2006-01-02"

type Date struct {
	time.Time
}

func (d Date) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.Format(DateFormat))
}

func (d *Date) UnmarshalJSON(data []byte) error {
	var dateStr string
	err := json.Unmarshal(data, &dateStr)
	if err != nil {
		return err
	}
	parsed, err := time.Parse(DateFormat, dateStr)
	if err != nil {
		return err
	}
	d.Time = parsed
	return nil
}

func (d Date) String() string {
	return d.Format(DateFormat)
}

func (d *Date) UnmarshalText(data []byte) error {
	parsed, err := time.Parse(DateFormat, string(data))
	if err != nil {
		return err
	}
	d.Time = parsed
	return nil
}

// MarshalText implements encoding.TextMarshaler for Date.
func (d Date) MarshalText() ([]byte, error) {
	return []byte(d.Format(DateFormat)), nil
}

// Format returns the date formatted according to layout.
func (d Date) Format(layout string) string {
	return d.Time.Format(layout)
}

// ErrValidationEmail is the sentinel error returned when an email fails validation

// Email represents an email address.
// It is a string type that must pass regex validation before being marshalled
// to JSON or unmarshalled from JSON.

// Nullable is a generic type that can distinguish between:
// - Field not provided (unspecified)
// - Field explicitly set to null
// - Field has a value
//
// This is implemented as a map[bool]T where:
// - Empty map: unspecified
// - map[false]T: explicitly null
// - map[true]T: has a value

// NewNullableWithValue creates a Nullable with the given value.

// NewNullNullable creates a Nullable that is explicitly null.

// Get returns the value if set, or an error if null or unspecified.

// MustGet returns the value or panics if null or unspecified.

// Set assigns a value.

// SetNull marks the field as explicitly null.

// SetUnspecified clears the field (as if it was never set).

// IsNull returns true if the field is explicitly null.

// IsSpecified returns true if the field was provided (either null or a value).

// MarshalJSON implements json.Marshaler.

// Unspecified - this shouldn't be called if omitempty is used correctly

// UnmarshalJSON implements json.Unmarshaler.

// ErrNullableIsNull is returned when trying to get a value from a null Nullable.

// ErrNullableNotSpecified is returned when trying to get a value from an unspecified Nullable.

// BindDeepObjectQueryParam binds a deepObject-style query parameter to a destination.
// DeepObject style is only valid for query parameters and is always exploded.
// Objects: ?paramName[key1]=value1&paramName[key2]=value2 -> struct{Key1, Key2}
// Nested: ?paramName[outer][inner]=value -> struct{Outer: {Inner: value}}

// UnmarshalDeepObject unmarshals deepObject-style query parameters to a destination.

// Find all params that look like "paramName[..."

// Trim the parameter name prefix

// Reconstruct subscript paths

// BindFormParam binds a form-style parameter from a single string value.
// Used for path, header, and cookie parameters where the value has already
// been extracted from the request.
//
// Non-explode (default for form):
//
//	Arrays:  a,b,c -> []string{"a", "b", "c"}
//	Objects: key1,value1,key2,value2 -> struct{Key1, Key2}
//
// Explode:
//
//	Primitives and arrays: same comma-separated format
//	Objects: key1=value1,key2=value2 -> struct{Key1, Key2}
func BindFormParam(paramName string, value string, dest any, opts ParameterOptions) error {
	if value == "" {
		return fmt.Errorf("parameter '%s' is empty, can't bind its value", paramName)
	}

	var err error
	value, err = unescapeParameterString(value, opts.ParamLocation)
	if err != nil {
		return fmt.Errorf("error unescaping parameter '%s': %w", paramName, err)
	}

	if tu, ok := dest.(encoding.TextUnmarshaler); ok {
		return tu.UnmarshalText([]byte(value))
	}

	v := reflect.Indirect(reflect.ValueOf(dest))
	t := v.Type()

	switch t.Kind() {
	case reflect.Struct:
		parts := strings.Split(value, ",")
		return bindSplitPartsToDestinationStruct(paramName, parts, opts.Explode, dest)
	case reflect.Slice:
		parts := strings.Split(value, ",")
		return bindSplitPartsToDestinationArray(parts, dest)
	default:
		return BindStringToObject(value, dest)
	}
}

// BindFormQueryParam binds a form-style query parameter from url.Values.
// The function looks up the parameter by name and handles both exploded
// and non-exploded formats.
//
// Non-explode: ?param=a,b,c (single query key, comma-separated value)
// Explode:     ?param=a&param=b&param=c (multiple query keys)
func BindFormQueryParam(paramName string, queryParams url.Values, dest any, opts ParameterOptions) error {
	if opts.Explode {
		return bindFormExplodeQuery(paramName, queryParams, dest, opts)
	}
	// Non-explode: single value, comma-separated
	value := queryParams.Get(paramName)
	if value == "" {
		if opts.Required {
			return fmt.Errorf("query parameter '%s' is required", paramName)
		}
		return nil
	}
	return BindFormParam(paramName, value, dest, opts)
}

// bindFormExplodeQuery handles the exploded form-style query parameter case.
func bindFormExplodeQuery(paramName string, queryParams url.Values, dest any, opts ParameterOptions) error {
	dv := reflect.Indirect(reflect.ValueOf(dest))
	v := dv
	var output any

	if opts.Required {
		output = dest
	} else {
		if v.IsNil() {
			t := v.Type()
			newValue := reflect.New(t.Elem())
			output = newValue.Interface()
		} else {
			output = v.Interface()
		}
		v = reflect.Indirect(reflect.ValueOf(output))
	}

	t := v.Type()
	k := t.Kind()

	values, found := queryParams[paramName]

	switch k {
	case reflect.Slice:
		if !found {
			if opts.Required {
				return fmt.Errorf("query parameter '%s' is required", paramName)
			}
			return nil
		}
		err := bindSplitPartsToDestinationArray(values, output)
		if err != nil {
			return err
		}
	case reflect.Struct:
		fieldsPresent, err := bindParamsToExplodedObject(paramName, queryParams, output)
		if err != nil {
			return err
		}
		if !fieldsPresent {
			return nil
		}
	default:
		if len(values) == 0 {
			if opts.Required {
				return fmt.Errorf("query parameter '%s' is required", paramName)
			}
			return nil
		}
		if len(values) != 1 {
			return fmt.Errorf("multiple values for single value parameter '%s'", paramName)
		}
		if !found {
			if opts.Required {
				return fmt.Errorf("query parameter '%s' is required", paramName)
			}
			return nil
		}
		err := BindStringToObject(values[0], output)
		if err != nil {
			return err
		}
	}

	if !opts.Required {
		dv.Set(reflect.ValueOf(output))
	}
	return nil
}

// bindParamsToExplodedObject binds query params to struct fields for exploded objects.
func bindParamsToExplodedObject(paramName string, values url.Values, dest any) (bool, error) {
	binder, v, t := indirectBinder(dest)
	if binder != nil {
		_, found := values[paramName]
		if !found {
			return false, nil
		}
		return true, BindStringToObject(values.Get(paramName), dest)
	}
	if t.Kind() != reflect.Struct {
		return false, fmt.Errorf("unmarshaling query arg '%s' into wrong type", paramName)
	}

	fieldsPresent := false
	for i := 0; i < t.NumField(); i++ {
		fieldT := t.Field(i)
		if !v.Field(i).CanSet() {
			continue
		}

		tag := fieldT.Tag.Get("json")
		fieldName := fieldT.Name
		if tag != "" {
			tagParts := strings.Split(tag, ",")
			if tagParts[0] != "" {
				fieldName = tagParts[0]
			}
		}

		fieldVal, found := values[fieldName]
		if found {
			if len(fieldVal) != 1 {
				return false, fmt.Errorf("field '%s' specified multiple times for param '%s'", fieldName, paramName)
			}
			err := BindStringToObject(fieldVal[0], v.Field(i).Addr().Interface())
			if err != nil {
				return false, fmt.Errorf("could not bind query arg '%s': %w", paramName, err)
			}
			fieldsPresent = true
		}
	}
	return fieldsPresent, nil
}

// indirectBinder checks if dest implements Binder and returns reflect values.
func indirectBinder(dest any) (any, reflect.Value, reflect.Type) {
	v := reflect.ValueOf(dest)
	if v.Type().NumMethod() > 0 && v.CanInterface() {
		if u, ok := v.Interface().(Binder); ok {
			return u, reflect.Value{}, nil
		}
	}
	v = reflect.Indirect(v)
	t := v.Type()
	if t.ConvertibleTo(reflect.TypeOf(time.Time{})) {
		return dest, reflect.Value{}, nil
	}
	if t.ConvertibleTo(reflect.TypeOf(Date{})) {
		return dest, reflect.Value{}, nil
	}
	return nil, v, t
}

// BindLabelParam binds a label-style parameter to a destination.
// Label style values are prefixed with a dot. Path parameters only.
//
// Non-explode:
//
//	Primitives: .value          Arrays: .a,b,c          Objects: .key1,value1,key2,value2
//
// Explode:
//
//	Primitives: .value          Arrays: .a.b.c          Objects: .key1=value1.key2=value2

// Explode: split on dot, skip first empty part

// Non-explode: strip leading dot, split on comma

// BindMatrixParam binds a matrix-style parameter to a destination.
// Matrix style values are prefixed with semicolons. Path parameters only.
//
// Non-explode:
//
//	Primitives: ;paramName=value
//	Arrays:     ;paramName=a,b,c
//	Objects:    ;paramName=key1,value1,key2,value2
//
// Explode:
//
//	Primitives: ;paramName=value
//	Arrays:     ;paramName=a;paramName=b;paramName=c
//	Objects:    ;key1=value1;key2=value2

// BindPipeDelimitedQueryParam binds a pipeDelimited-style query parameter.
// Pipe-delimited style uses pipes as array separators. Query only.
//
// Non-explode: ?param=a|b|c -> []string{"a", "b", "c"}
// Explode:     ?param=a&param=b -> []string{"a", "b"} (same as form explode)

// Exploded pipe-delimited is same as exploded form

// BindSimpleParam binds a simple-style parameter to a destination.
// Simple style is the default for path and header parameters.
// Only used as a single-value entry point (no query variant needed).
//
// Non-explode: Arrays: a,b,c  Objects: key1,value1,key2,value2
// Explode:     Arrays: a,b,c  Objects: key1=value1,key2=value2
func BindSimpleParam(paramName string, value string, dest any, opts ParameterOptions) error {
	if value == "" {
		return fmt.Errorf("parameter '%s' is empty, can't bind its value", paramName)
	}

	var err error
	value, err = unescapeParameterString(value, opts.ParamLocation)
	if err != nil {
		return fmt.Errorf("error unescaping parameter '%s': %w", paramName, err)
	}

	if tu, ok := dest.(encoding.TextUnmarshaler); ok {
		return tu.UnmarshalText([]byte(value))
	}

	v := reflect.Indirect(reflect.ValueOf(dest))
	t := v.Type()

	switch t.Kind() {
	case reflect.Struct:
		parts := strings.Split(value, ",")
		return bindSplitPartsToDestinationStruct(paramName, parts, opts.Explode, dest)
	case reflect.Slice:
		parts := strings.Split(value, ",")
		return bindSplitPartsToDestinationArray(parts, dest)
	default:
		return BindStringToObject(value, dest)
	}
}

// BindSpaceDelimitedQueryParam binds a spaceDelimited-style query parameter.
// Space-delimited style uses spaces as array separators. Query only.
//
// Non-explode: ?param=a%20b%20c -> []string{"a", "b", "c"}
// Explode:     ?param=a&param=b -> []string{"a", "b"} (same as form explode)

// Exploded space-delimited is same as exploded form

// ParamLocation indicates where a parameter is located in an HTTP request.
type ParamLocation int

const (
	ParamLocationUndefined ParamLocation = iota
	ParamLocationQuery
	ParamLocationPath
	ParamLocationHeader
	ParamLocationCookie
)

// Binder is an interface for types that can bind themselves from a string value.
type Binder interface {
	Bind(value string) error
}

// primitiveToString converts a primitive value to a string representation.
// It handles basic Go types, time.Time, Date, and types that implement
// json.Marshaler or fmt.Stringer.

// Check for known types first (time, date, uuid)

// Dereference pointers for optional values

// Check if it's a UUID

// Check if it implements json.Marshaler

// marshalKnownTypes checks for special types (time.Time, Date, UUID) and marshals them.

// escapeParameterString escapes a parameter value based on its location.
// Query and path parameters need URL escaping; headers and cookies do not.

// unescapeParameterString unescapes a parameter value based on its location.
func unescapeParameterString(value string, paramLocation ParamLocation) (string, error) {
	switch paramLocation {
	case ParamLocationQuery, ParamLocationUndefined:
		return url.QueryUnescape(value)
	case ParamLocationPath:
		return url.PathUnescape(value)
	default:
		return value, nil
	}
}

// sortedKeys returns the keys of a map in sorted order.

// BindStringToObject binds a string value to a destination object.
// It handles primitives, encoding.TextUnmarshaler, and the Binder interface.
func BindStringToObject(src string, dst any) error {
	// Check for TextUnmarshaler
	if tu, ok := dst.(encoding.TextUnmarshaler); ok {
		return tu.UnmarshalText([]byte(src))
	}

	// Check for Binder interface
	if b, ok := dst.(Binder); ok {
		return b.Bind(src)
	}

	v := reflect.ValueOf(dst)
	if v.Kind() != reflect.Ptr {
		return fmt.Errorf("dst must be a pointer, got %T", dst)
	}
	v = v.Elem()

	switch v.Kind() {
	case reflect.String:
		v.SetString(src)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		i, err := strconv.ParseInt(src, 10, 64)
		if err != nil {
			return fmt.Errorf("failed to parse int: %w", err)
		}
		v.SetInt(i)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		u, err := strconv.ParseUint(src, 10, 64)
		if err != nil {
			return fmt.Errorf("failed to parse uint: %w", err)
		}
		v.SetUint(u)
	case reflect.Float32, reflect.Float64:
		f, err := strconv.ParseFloat(src, 64)
		if err != nil {
			return fmt.Errorf("failed to parse float: %w", err)
		}
		v.SetFloat(f)
	case reflect.Bool:
		b, err := strconv.ParseBool(src)
		if err != nil {
			return fmt.Errorf("failed to parse bool: %w", err)
		}
		v.SetBool(b)
	default:
		// Try JSON unmarshal as a fallback
		return json.Unmarshal([]byte(src), dst)
	}
	return nil
}

// bindSplitPartsToDestinationArray binds a slice of string parts to a destination slice.
func bindSplitPartsToDestinationArray(parts []string, dest any) error {
	v := reflect.Indirect(reflect.ValueOf(dest))
	t := v.Type()

	newArray := reflect.MakeSlice(t, len(parts), len(parts))
	for i, p := range parts {
		err := BindStringToObject(p, newArray.Index(i).Addr().Interface())
		if err != nil {
			return fmt.Errorf("error setting array element: %w", err)
		}
	}
	v.Set(newArray)
	return nil
}

// bindSplitPartsToDestinationStruct binds string parts to a destination struct via JSON.
func bindSplitPartsToDestinationStruct(paramName string, parts []string, explode bool, dest any) error {
	var fields []string
	if explode {
		fields = make([]string, len(parts))
		for i, property := range parts {
			propertyParts := strings.Split(property, "=")
			if len(propertyParts) != 2 {
				return fmt.Errorf("parameter '%s' has invalid exploded format", paramName)
			}
			fields[i] = "\"" + propertyParts[0] + "\":\"" + propertyParts[1] + "\""
		}
	} else {
		if len(parts)%2 != 0 {
			return fmt.Errorf("parameter '%s' has invalid format, property/values need to be pairs", paramName)
		}
		fields = make([]string, len(parts)/2)
		for i := 0; i < len(parts); i += 2 {
			key := parts[i]
			value := parts[i+1]
			fields[i/2] = "\"" + key + "\":\"" + value + "\""
		}
	}
	jsonParam := "{" + strings.Join(fields, ",") + "}"
	return json.Unmarshal([]byte(jsonParam), dest)
}

// structToFieldDict converts a struct to a map of field names to string values.

// Skip nil optional fields

// ParameterOptions carries OpenAPI parameter metadata to bind and style
// functions so they can handle explode, required, type-aware coercions,
// and location-aware escaping from a single uniform call site.
type ParameterOptions struct {
	ParamLocation ParamLocation
	Explode       bool
	Required      bool
	Type          string // OpenAPI type: "string", "integer", "array", "object"
	Format        string // OpenAPI format: "int32", "date-time", etc.
}

// StyleDeepObjectParam serializes a value using deepObject style.
// DeepObject style is only valid for query parameters with object values and must be exploded.
// Objects: paramName[key1]=value1&paramName[key2]=value2
// Nested: paramName[outer][inner]=value

// deepObject always requires explode=true

// MarshalDeepObject marshals an object to deepObject style query parameters.

// Marshal to JSON first to handle all field annotations

// Prefix the param name to each subscripted field

// Arrays use numerical subscripts [0], [1], etc.

// Maps use key subscripts [key1], [key2], etc.

// Concrete value: turn path into [a][b][c] format

// StyleFormParam serializes a value using form style (RFC 6570).
// Form style is the default for query and cookie parameters.
//
// Non-explode: Primitives: paramName=value  Arrays: paramName=a,b,c  Objects: paramName=key1,value1,key2,value2
// Explode:     Primitives: paramName=value  Arrays: paramName=a&paramName=b  Objects: key1=value1&key2=value2

// paramName=a&paramName=b&paramName=c

// paramName=a,b,c

// key1=value1&key2=value2

// paramName=key1,value1,key2,value2

// StyleLabelParam serializes a value using label style (RFC 6570).
// Label style prefixes values with a dot. Path parameters only.
//
// Non-explode: Primitives: .value  Arrays: .a,b,c          Objects: .key1,value1,key2,value2
// Explode:     Primitives: .value  Arrays: .a.b.c          Objects: .key1=value1.key2=value2

// StyleMatrixParam serializes a value using matrix style (RFC 6570).
// Matrix style prefixes values with ;paramName=. Path parameters only.
//
// Non-explode: Primitives: ;p=val   Arrays: ;p=a,b,c           Objects: ;p=k1,v1,k2,v2
// Explode:     Primitives: ;p=val   Arrays: ;p=a;p=b;p=c       Objects: ;k1=v1;k2=v2

// ;paramName=a;paramName=b;paramName=c

// ;paramName=a,b,c

// ;key1=value1;key2=value2

// ;paramName=key1,value1,key2,value2

// StylePipeDelimitedParam serializes a value using pipeDelimited style.
// Pipe-delimited style is used for query parameters with array values.
//
// Non-explode: paramName=a|b|c
// Explode:     paramName=a&paramName=b&paramName=c

// StyleSimpleParam serializes a value using simple style (RFC 6570).
// Simple style is the default for path and header parameters.
//
// Non-explode: Arrays: a,b,c  Objects: key1,value1,key2,value2
// Explode:     Arrays: a,b,c  Objects: key1=value1,key2=value2

// Simple arrays are always comma-separated regardless of explode

// StyleSpaceDelimitedParam serializes a value using spaceDelimited style.
// Space-delimited style is used for query parameters with array values.
//
// Non-explode: paramName=a b c
// Explode:     paramName=a&paramName=b&paramName=c

// JSONMerge merges two JSON-encoded objects. Fields from patch override
// fields in base. Both arguments must be valid JSON objects (or nil/null).

// MarshalForm marshals a struct into url.Values using the struct's json tags
// as field names. It handles nested structs, slices, pointers, and
// AdditionalProperties maps.
