// Code generated by oapi-codegen; DO NOT EDIT.

package output

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"sync"

	oapiCodegenHelpersPkg "github.com/oapi-codegen/oapi-codegen-exp/runtime/helpers"
)

// #/components/schemas/ConfigHttp
type ConfigHTTP struct {
	ConfigType string  `form:"config_type" json:"config_type"`
	Host       string  `form:"host" json:"host"`
	Port       int     `form:"port" json:"port"`
	User       *string `form:"user,omitempty" json:"user,omitempty"`
	Password   *string `form:"password,omitempty" json:"password,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ConfigHTTP) ApplyDefaults() {
}

// #/components/schemas/ConfigSaveReq

type ConfigSaveReq struct {
	union json.RawMessage
}

// AsConfigHTTP returns the union data inside the ConfigSaveReq as a ConfigHTTP.
func (t ConfigSaveReq) AsConfigHTTP() (ConfigHTTP, error) {
	var body ConfigHTTP
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConfigHTTP overwrites any union data inside the ConfigSaveReq as the provided ConfigHTTP.
func (t *ConfigSaveReq) FromConfigHTTP(v ConfigHTTP) error {
	v.ConfigType = "apache_server"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConfigHTTP performs a merge with any union data inside the ConfigSaveReq, using the provided ConfigHTTP.
func (t *ConfigSaveReq) MergeConfigHTTP(v ConfigHTTP) error {
	v.ConfigType = "apache_server"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsConfigSSH returns the union data inside the ConfigSaveReq as a ConfigSSH.
func (t ConfigSaveReq) AsConfigSSH() (ConfigSSH, error) {
	var body ConfigSSH
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConfigSSH overwrites any union data inside the ConfigSaveReq as the provided ConfigSSH.
func (t *ConfigSaveReq) FromConfigSSH(v ConfigSSH) error {
	v.ConfigType = "ssh_server"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConfigSSH performs a merge with any union data inside the ConfigSaveReq, using the provided ConfigSSH.
func (t *ConfigSaveReq) MergeConfigSSH(v ConfigSSH) error {
	v.ConfigType = "ssh_server"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := oapiCodegenHelpersPkg.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// Discriminator extracts the discriminator property value from the union data.
func (t ConfigSaveReq) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"config_type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

// ValueByDiscriminator returns the union member based on the discriminator value.
func (t ConfigSaveReq) ValueByDiscriminator() (any, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "apache_server":
		return t.AsConfigHTTP()
	case "web_server":
		return t.AsConfigHTTP()
	case "another_server":
		return t.AsConfigHTTP()
	case "ssh_server":
		return t.AsConfigSSH()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ConfigSaveReq) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ConfigSaveReq) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *ConfigSaveReq) ApplyDefaults() {
}

// #/components/schemas/ConfigSsh
type ConfigSSH struct {
	ConfigType string  `form:"config_type" json:"config_type"`
	Host       *string `form:"host,omitempty" json:"host,omitempty"`
	Port       *int    `form:"port,omitempty" json:"port,omitempty"`
	User       *string `form:"user,omitempty" json:"user,omitempty"`
	PrivateKey *string `form:"private_key,omitempty" json:"private_key,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ConfigSSH) ApplyDefaults() {
}

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/9xTPXPUMBDt/St2DC1nBzqXpIECmCHpbxR5fVawtcru2hn/e0aW706ZCXM56Ojsp/ee",
	"3n6IAnoTXAPlp129uykL5ztqCoAZWRz5Bm529a4uANTpgA3co2gBMDiLXjAyAbwZsYFvX++LYLSXCFaW",
	"fOcO6TyQaPoCkGkcDS8N3JkZIbEmNurIbwzGpwlFP1O7HEUQiYpezwCACWFwdlVWj0I+PwMQ2+NoXmIA",
	"7xm7Bsp3laUxkEevUiWmVLdrlhjrJz6VpzASyAvK2an8WNdlbtyiWHZB13bd5hWBmBlbkMlaFOmmYViK",
	"883RY7s82SXtF9VwtNclYAP08IhWNygwBWR1eaTUxv3KzoIltSg7fzjBfTaMP5IC8Ssk5xUPyCd8EuTL",
	"Vkbkmbi9QIxTd4wZ7UNeVobGArLfGDXr3ja/ow15/NHlnpc3IPa/vEpxJ/1R0Lq4C6PzRinrzTa05fv6",
	"Ul6razQhOH/IuyTS7wV5Rn7z9eldGNvjm5QvSwV4xoe/0hlP2iNfqT2l/5+2nd1sFPe/cPm3hf8dAAD/",
	"/3I5IYWZBQAA",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}
