// Code generated by oapi-codegen; DO NOT EDIT.

package output

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"strings"
	"sync"
)

// #/components/schemas/RecursiveObject
type RecursiveObject struct {
	FieldInNonRecursive *string `form:"FieldInNonRecursive,omitempty" json:"FieldInNonRecursive,omitempty"`
	FieldInRecursive    *string `form:"FieldInRecursive:,omitempty" json:"FieldInRecursive:,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *RecursiveObject) ApplyDefaults() {
}

// #/components/schemas/NonRecursiveObject
type NonRecursiveObject struct {
	FieldInNonRecursive *string `form:"FieldInNonRecursive,omitempty" json:"FieldInNonRecursive,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *NonRecursiveObject) ApplyDefaults() {
}

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/4yRTU7DMBCF9z7FU0DyiiSUnQ8AqhBU4gYmmTYurm3Z04pKHB7lj6ShQmSVZL5533js",
	"AzkdjMJDXuYrYdzWKwGcKCbjnYIs8zK/lwJgw5YU6FMfgiUB1JSqaAJ33JcAgBf9QUjHSOBGMyJVx5jM",
	"iXAbaQvjoK3dbKEjodGutlQjRB8o2rMImpvUuotBobrIHXH/ArSgbnXr+meOJ+KhGikF7xKlEQfkqizl",
	"9LkYOds8Z7Na5R2T4zkOSB2CNVVnLfbJO3lZB1LV0EEv/6I7sYK8KSp/CN6R41T0bCrexr1s3vdUsRRi",
	"gtqkgetDF/Bo6jY5ae8GYXZV+OrdIib7Z+cfbf3NsZlvvH0eDdl6PQnVcjl8DqSQOBq3E13t93xjzzXJ",
	"IJg3zRUX8d8BAAD///aKDBzgAgAA",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}
